"""
paper_trading.operations — Session Operations & Observability v1.6.3

PAPER SESSION OPERATIONS ONLY. RESEARCH ONLY. NO REAL ORDERS.
NO BROKER. NO REAL ACCOUNT. PRODUCTION TRADING BLOCKED.
"""
from __future__ import annotations

VERSION = "1.6.3"
RELEASE_NAME = "Session Operations & Observability"
BASE_RELEASE = "1.6.2.1 Paper Strategy Orchestration Integrity Hotfix"

SESSION_OPERATIONS_AVAILABLE               = True
SESSION_OBSERVABILITY_AVAILABLE            = True
SESSION_OPERATIONS_STAGE                   = "FOUNDATION"
SESSION_OPERATIONS_RESEARCH_ONLY           = True

SESSION_SUPERVISOR_ENABLED                 = True
SESSION_HEALTH_AGGREGATION_ENABLED         = True
SESSION_ALERTING_ENABLED                   = True
SESSION_INCIDENT_TIMELINE_ENABLED          = True
SESSION_RECOVERY_DRILL_ENABLED             = True
SESSION_OPERATIONAL_SNAPSHOT_ENABLED       = True

REAL_SESSION_OPERATIONS_ENABLED            = False
BROKER_MONITORING_ENABLED                  = False
REAL_ACCOUNT_MONITORING_ENABLED            = False
REAL_ORDER_MONITORING_ENABLED              = False
REAL_POSITION_MONITORING_ENABLED           = False
PRODUCTION_INCIDENT_AUTOMATION_ENABLED     = False
AUTOMATIC_BROKER_RECOVERY_ENABLED          = False
AUTOMATIC_REAL_ORDER_RECOVERY_ENABLED      = False
REAL_PORTFOLIO_LEDGER_WRITE_ENABLED        = False

NO_REAL_ORDERS                             = True
BROKER_EXECUTION_ENABLED                   = False
PRODUCTION_TRADING_BLOCKED                 = True

AUTO_RESUME_RUNNING                        = False

SAFETY_MARKERS = [
    "PAPER_ONLY",
    "RESEARCH_ONLY",
    "SIMULATION_ONLY",
    "NO_BROKER",
    "NO_REAL_ACCOUNT",
    "NO_REAL_ORDERS",
    "NO_PRODUCTION_CONTROL",
    "NO_FORMAL_PORTFOLIO_LEDGER_WRITE",
]

__all__ = [
    "VERSION", "RELEASE_NAME", "BASE_RELEASE",
    "SESSION_OPERATIONS_AVAILABLE", "SESSION_OBSERVABILITY_AVAILABLE",
    "SESSION_OPERATIONS_STAGE", "SESSION_OPERATIONS_RESEARCH_ONLY",
    "SESSION_SUPERVISOR_ENABLED", "SESSION_HEALTH_AGGREGATION_ENABLED",
    "SESSION_ALERTING_ENABLED", "SESSION_INCIDENT_TIMELINE_ENABLED",
    "SESSION_RECOVERY_DRILL_ENABLED", "SESSION_OPERATIONAL_SNAPSHOT_ENABLED",
    "REAL_SESSION_OPERATIONS_ENABLED", "BROKER_MONITORING_ENABLED",
    "REAL_ACCOUNT_MONITORING_ENABLED", "REAL_ORDER_MONITORING_ENABLED",
    "REAL_POSITION_MONITORING_ENABLED", "PRODUCTION_INCIDENT_AUTOMATION_ENABLED",
    "AUTOMATIC_BROKER_RECOVERY_ENABLED", "AUTOMATIC_REAL_ORDER_RECOVERY_ENABLED",
    "REAL_PORTFOLIO_LEDGER_WRITE_ENABLED",
    "NO_REAL_ORDERS", "BROKER_EXECUTION_ENABLED", "PRODUCTION_TRADING_BLOCKED",
    "AUTO_RESUME_RUNNING", "SAFETY_MARKERS",
]
