"""
paper_trading/analytics/__init__.py — Operational Analytics & Review v1.6.4

RESEARCH ONLY. PAPER SIMULATION ONLY. NO REAL ORDERS. NO BROKER.
NO AUTO STRATEGY CHANGES. NO AUTO RISK CHANGES. NOT INVESTMENT ADVICE.
"""
from __future__ import annotations

VERSION = "1.6.4"
PACKAGE_NAME = "operational_analytics_review"

RESEARCH_ONLY = True
PAPER_ONLY = True
NO_REAL_ORDERS = True
NO_BROKER = True
AUTO_STRATEGY_CHANGE_ENABLED = False
AUTO_PARAMETER_CHANGE_ENABLED = False
AUTO_RISK_LIMIT_CHANGE_ENABLED = False
AUTO_DEPLOYMENT_ENABLED = False
AUTO_LIVE_ACTION_ENABLED = False
