"""
reports/replay_session_manager_report.py — ReplaySessionManagerReportBuilder v1.2.1

Output: reports/replay_session_manager_report_YYYY-MM-DD.md

[!] Research Only. No Real Orders. Replay Training Only.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

RESEARCH_ONLY = True
NO_REAL_ORDERS = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class ReplaySessionManagerReportBuilder:
    """
    Builds the Replay Session Manager report.
    Output: reports/replay_session_manager_report_YYYY-MM-DD.md

    [!] Research Only. No Real Orders. Replay Training Only.
    """

    RESEARCH_ONLY = True
    NO_REAL_ORDERS = True

    def __init__(self, repo_root: Optional[str] = None):
        self._repo_root = repo_root or BASE_DIR

    def build(self, session_manager=None) -> str:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# Replay Session Manager Report",
            f"",
            f"**Date:** {today}",
            f"",
            f"> [!] Research Only | No Real Orders | Replay Training Only",
            f"> [!] No Auto Decision | No Auto Scoring | No Future Performance Evaluation",
            f"",
        ]

        sessions = []
        if session_manager:
            try:
                sessions = session_manager.list_sessions(include_hidden=False, include_archived=True)
            except Exception as exc:
                logger.warning("[SessionManagerReport] list_sessions: %s", exc)

        active = [s for s in sessions if s.get("_state", {}).get("status") in ("PLAYING", "READY", "PAUSED")]
        completed = [s for s in sessions if s.get("_state", {}).get("status") == "COMPLETED"]
        archived = [s for s in sessions if s.get("_state", {}).get("status") == "ARCHIVED"]
        blocked = [s for s in sessions if s.get("_state", {}).get("status") == "BLOCKED"]

        lines += [
            f"## Session Summary",
            f"",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Total Sessions | {len(sessions)} |",
            f"| Active/Paused | {len(active)} |",
            f"| Completed | {len(completed)} |",
            f"| Archived | {len(archived)} |",
            f"| Blocked | {len(blocked)} |",
            f"",
        ]

        # Session details table
        lines += [
            f"## Session Details",
            f"",
            f"| ID | Name | Symbol | Status | Scenario | Qualification |",
            f"|----|------|--------|--------|----------|---------------|",
        ]
        for s in sessions[:50]:
            state = s.get("_state", {})
            lines.append(
                f"| {s.get('session_id','')[:20]} | {s.get('session_name','')[:20]} "
                f"| {s.get('symbol','')} | {state.get('status','')} "
                f"| {s.get('scenario_id','N/A')} | {state.get('qualification','')} |"
            )
        if len(sessions) > 50:
            lines.append(f"*... and {len(sessions) - 50} more sessions*")
        lines.append("")

        # Safety Declaration
        lines += [
            f"## Safety Declaration",
            f"",
            f"- Research Only: True",
            f"- No Real Orders: True",
            f"- No Auto Decision: True",
            f"- No Auto Scoring: True",
            f"- No Auto Execution: True",
            f"- No Trade Execution: True",
            f"- No Future Performance Evaluation",
            f"",
            f"---",
            f"*Generated by TW Quant Cockpit v1.2.1 — Not Investment Advice*",
        ]
        return "\n".join(lines)

    def save(self, content: str) -> str:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        reports_dir = Path(self._repo_root) / "reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        fname = f"replay_session_manager_report_{today}.md"
        fpath = reports_dir / fname
        with open(str(fpath), "w", encoding="utf-8") as f:
            f.write(content)
        return str(fpath)
