"""
reports/replay_review_dashboard_report.py — Replay Review Dashboard Report v1.2.6

Markdown report with sections: Session Overview, Review Progress, Decision Journal,
Process Score, Outcome Score (NOT_REVEALED if not revealed), Composite Classification,
Mistakes, Strategy Knowledge, Multi-timeframe, PIT Integrity, Review Queue,
Checklist, Notes/Tags, Reports, Limitations, Safety declaration.

[!] Research Only. No Real Orders. Outcome NOT_REVEALED until explicit reveal.
[!] Not Investment Advice.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

NO_REAL_ORDERS = True
RESEARCH_ONLY = True


def build_replay_review_dashboard_report(
    session_id: str,
    session_data: Optional[Dict[str, Any]] = None,
    mode: str = "real",
) -> str:
    """
    Build full markdown report for a replay review session.

    [!] Research Only. No Real Orders. Not Investment Advice.
    """
    data = session_data or {}
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    outcome_revealed = bool(data.get("outcome_revealed", False))

    lines = [
        f"# Replay Review Dashboard — Session {session_id}",
        f"**Generated:** {now}  ",
        f"**Version:** 1.2.6  ",
        f"**Mode:** {mode}  ",
        f"**Research Only:** True  ",
        f"**No Real Orders:** True  ",
        "",
        "---",
        "",
        "## Safety Declaration",
        "> **[!] Replay Review Only.** Process/Outcome Separated.",
        "> Outcome Hidden Until Explicit Reveal.",
        "> Suggested Mistakes Are Not Confirmed.",
        "> No Auto Review Completion. No Auto Decision.",
        "> No Auto Execution. No Real Orders. Broker Disabled.",
        "> Not Investment Advice.",
        "",
        "## Session Overview",
        f"- **Session ID:** {session_id}",
        f"- **Symbol:** {data.get('symbol', 'N/A')}",
        f"- **Scenario:** {data.get('scenario_id', 'N/A')}",
        f"- **Status:** {data.get('status', 'UNKNOWN')}",
        f"- **Mode:** {mode}",
        f"- **Created At:** {data.get('created_at', 'N/A')}",
        "",
        "## Review Progress",
        f"- **Review Progress:** {data.get('review_progress', 'NOT_STARTED')}",
        f"- **Review Complete:** {data.get('review_complete', False)}",
        f"- **Outcome Reveal Required:** False (optional)",
        "",
        "## Decision Journal",
        f"- **Journal Exists:** {data.get('journal_exists', 'UNKNOWN')}",
        "",
        "## Process Score",
        f"- **Process Score:** {data.get('process_score', 'N/A')}",
        "> [!] Process score uses NO future data, NO outcome, NO PnL.",
        "> [!] Calculated from process quality only.",
        "",
        "## Outcome Score",
        f"- **Outcome Revealed:** {outcome_revealed}",
        f"- **Outcome Score:** {'NOT_REVEALED' if not outcome_revealed else data.get('outcome_score', 'N/A')}",
        "> [!] Outcome hidden until explicit user reveal action.",
        "",
        "## Composite Classification",
        f"- **Classification:** {'NOT_REVEALED' if not outcome_revealed else data.get('classification', 'N/A')}",
        "> [!] Composite score and classification require outcome reveal.",
        "",
        "## Mistakes",
        f"- **Suggested Mistakes:** {data.get('mistake_count', 0)}",
        f"- **Confirmed Mistakes:** {data.get('confirmed_mistake_count', 0)}",
        "> [!] Suggested only. System cannot auto-confirm mistakes.",
        "",
        "## Strategy Knowledge",
        f"- **Strategy Conflicts:** {data.get('strategy_conflicts', 0)}",
        "> [!] Training Only. No Auto-Trade. No Auto-Block.",
        "",
        "## Multi-Timeframe",
        f"- **MTF Conflicts:** {data.get('mtf_conflicts', 0)}",
        "",
        "## PIT Integrity",
        f"- **Point-in-Time Verified:** {data.get('pit_verified', False)}",
        "",
        "## Review Queue",
        f"- **Queue Items:** {data.get('queue_count', 'N/A')}",
        "",
        "## Checklist",
        "- See session checklist for detailed item status.",
        "",
        "## Notes / Tags",
        "- See session notes and tags.",
        "",
        "## Reports",
        "- Session report generated by ReplayReviewReportBuilder.",
        "",
        "## Limitations",
        "- This report reflects replay training data only.",
        "- No real orders, no broker execution, no live trading.",
        "- Process and outcome are strictly separated.",
        "- Outcome data excluded unless explicitly revealed.",
        "- Not Investment Advice.",
        "",
        "---",
        "> [!] Research Only. No Real Orders. Not Investment Advice.",
    ]
    return "\n".join(lines)
