"""
reports/replay_scenario_library_report.py — ReplayScenarioLibraryReportBuilder v1.2.1

Output: reports/replay_scenario_library_report_YYYY-MM-DD.md

[!] Research Only. No Real Orders. Replay Training Only.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

RESEARCH_ONLY = True
NO_REAL_ORDERS = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class ReplayScenarioLibraryReportBuilder:
    """
    Builds the Replay Scenario Library report.
    Output: reports/replay_scenario_library_report_YYYY-MM-DD.md

    [!] Research Only. No Real Orders. Replay Training Only.
    """

    RESEARCH_ONLY = True
    NO_REAL_ORDERS = True

    def __init__(self, repo_root: Optional[str] = None):
        self._repo_root = repo_root or BASE_DIR

    def build(self, scenario_query=None, session_query=None) -> str:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines = [
            f"# Replay Scenario Library Report",
            f"",
            f"**Date:** {today}",
            f"",
            f"> [!] Research Only | No Real Orders | Replay Training Only",
            f"> [!] No Auto Decision | No Auto Scoring | No Future Data",
            f"",
        ]

        # Scenario Summary
        scenarios = []
        if scenario_query:
            try:
                scenarios = scenario_query.list_scenarios(limit=200, include_archived=True)
            except Exception as exc:
                logger.warning("[ScenarioLibraryReport] list_scenarios: %s", exc)

        active = [s for s in scenarios if not s.get("archived", False)]
        archived = [s for s in scenarios if s.get("archived", False)]

        lines += [
            f"## Scenario Summary",
            f"",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Total Templates | {len(scenarios)} |",
            f"| Active Templates | {len(active)} |",
            f"| Archived Templates | {len(archived)} |",
            f"",
        ]

        # Categories
        categories = {}
        for s in active:
            cat = s.get("category", "UNKNOWN")
            categories[cat] = categories.get(cat, 0) + 1

        if categories:
            lines += [
                f"## By Category",
                f"",
                f"| Category | Count |",
                f"|----------|-------|",
            ]
            for cat, cnt in sorted(categories.items()):
                lines.append(f"| {cat} | {cnt} |")
            lines.append("")

        # Templates Table
        lines += [
            f"## Scenario Templates",
            f"",
            f"| ID | Name | Category | Difficulty | Source | Archived |",
            f"|----|------|----------|------------|--------|----------|",
        ]
        for s in scenarios:
            lines.append(
                f"| {s.get('scenario_id','')} | {s.get('scenario_name','')} "
                f"| {s.get('category','')} | {s.get('difficulty','')} "
                f"| {s.get('source','')} | {s.get('archived', False)} |"
            )
        lines.append("")

        # Safety Declaration
        lines += [
            f"## Safety Declaration",
            f"",
            f"- Research Only: True",
            f"- No Real Orders: True",
            f"- No Auto Decision: True",
            f"- No Auto Scoring: True",
            f"- No Future Data in Templates: True",
            f"- strict_future_firewall enforced on all templates",
            f"",
            f"---",
            f"*Generated by TW Quant Cockpit v1.2.1 — Not Investment Advice*",
        ]
        return "\n".join(lines)

    def save(self, content: str) -> str:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        reports_dir = Path(self._repo_root) / "reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        fname = f"replay_scenario_library_report_{today}.md"
        fpath = reports_dir / fname
        with open(str(fpath), "w", encoding="utf-8") as f:
            f.write(content)
        return str(fpath)
