"""
reports/replay_multi_timeframe_report.py — MultiTimeframeReplayReport v1.2.5

Generates markdown report for multi-timeframe replay session.
Output: reports/replay_multi_timeframe_report_{session_id}.md

[!] Research Only. No Real Orders. Replay Training Only. Not Investment Advice.
[!] Multi-timeframe Replay Only. No Auto Decision. No Auto Execution.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

NO_REAL_ORDERS = True
RESEARCH_ONLY = True

SAFETY_DECLARATION = """
---

## Safety Declaration

- **Multi-timeframe Replay Only** — training and research use only
- **No Auto Decision** — all decisions require explicit human input
- **No Auto Execution** — no orders sent automatically
- **No Real Orders** — broker execution disabled
- **Broker Disabled** — no connection to broker API
- **Not Investment Advice** — analysis is for educational purposes only
- **Research Only** — VALIDATED does not enable trading

---
*Generated by TW Quant Cockpit v1.2.5 Multi-timeframe Replay*
"""


class MultiTimeframeReplayReport:
    """
    Generates multi-timeframe replay session report in Markdown.

    [!] Research Only. No Real Orders. Not Investment Advice.
    """

    RESEARCH_ONLY = True
    NO_REAL_ORDERS = True

    TIMEFRAME_ORDER = ["D1", "M60", "M20", "M5", "M1"]

    def __init__(self, repo_root: Optional[str] = None) -> None:
        self._repo_root = repo_root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self._reports_dir = os.path.join(self._repo_root, "reports")
        os.makedirs(self._reports_dir, exist_ok=True)

    def build(
        self,
        session_id: str,
        multi_context: Optional[Dict[str, Any]] = None,
        store=None,
    ) -> str:
        """Build and save report. Returns report path."""
        report_content = self._build_content(session_id, multi_context or {}, store)
        filename = f"replay_multi_timeframe_report_{session_id}.md"
        path = os.path.join(self._reports_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(report_content)
        logger.info("[MTFReport] Report saved: %s", path)
        return path

    def _build_content(
        self,
        session_id: str,
        context: Dict[str, Any],
        store,
    ) -> str:
        now = datetime.now(timezone.utc).isoformat()
        replay_ts = context.get("replay_timestamp", "N/A")
        symbol    = context.get("symbol", "N/A")

        lines = [
            "# Multi-timeframe Replay Report v1.2.5",
            "",
            f"> **Research Only | No Real Orders | No Auto Decision | Not Investment Advice**",
            "",
            "## Session Overview",
            "",
            f"- **Session ID**: {session_id}",
            f"- **Symbol**: {symbol}",
            f"- **Replay Timestamp**: {replay_ts}",
            f"- **Report Generated**: {now}",
            "",
            "## Data Availability",
            "",
            "| Timeframe | Status | Bar Timestamp | Source |",
            "|-----------|--------|---------------|--------|",
        ]

        for tf in self.TIMEFRAME_ORDER:
            tf_ctx = context.get(tf) or {}
            status    = "AVAILABLE" if tf_ctx.get("has_data") else "UNAVAILABLE"
            bar_ts    = ""
            source    = ""
            completed = tf_ctx.get("latest_completed_bar") or {}
            if completed:
                bar_ts = completed.get("timestamp", "")
                source = completed.get("source", "")
            lines.append(f"| {tf} | {status} | {bar_ts} | {source} |")

        lines += [
            "",
            "## Point-in-Time Verification",
            "",
            f"- **Overall Verified**: {context.get('point_in_time_verified', False)}",
            "- Future Rows Blocked: see firewall report",
            "- Incomplete Bars Blocked: see firewall report",
            "- Daily Close Leaks Blocked: see firewall report",
            "",
            "## Timeframe Snapshots",
            "",
        ]

        for tf in self.TIMEFRAME_ORDER:
            tf_ctx = context.get(tf) or {}
            lines += [
                f"### {tf}",
                "",
                f"- **Trend State**: {tf_ctx.get('trend_state', 'N/A')}",
                f"- **Volume State**: {tf_ctx.get('volume_state', 'N/A')}",
                f"- **Has Data**: {tf_ctx.get('has_data', False)}",
                f"- **PIT Verified**: {tf_ctx.get('point_in_time_verified', False)}",
                "",
            ]

        # Agreement
        agreement = context.get("agreement") or {}
        lines += [
            "## Agreement Analysis",
            "",
            f"- **Status**: {agreement.get('status', 'N/A')}",
            f"- **Agreement Score**: {agreement.get('agreement_score', 0.0):.3f}",
            f"- **Conflict Score**: {agreement.get('conflict_score', 0.0):.3f}",
            f"- **Dominant TF**: {agreement.get('dominant_timeframe', 'N/A')}",
            f"- **Trigger TF**: {agreement.get('trigger_timeframe', 'N/A')}",
            f"- **Training Only**: {agreement.get('training_only', True)}",
            f"- **No Auto Trade**: {agreement.get('no_auto_trade', True)}",
            "",
        ]

        # Conflicts
        conflicts_ctx = context.get("conflicts") or {}
        conflicts = conflicts_ctx.get("conflicts") or []
        lines += [
            "## Conflicts",
            "",
            f"- **Count**: {len(conflicts)}",
        ]
        for c in conflicts:
            lines.append(f"- [{c.get('severity','?')}] {c.get('conflict_type','?')}: {c.get('evidence','')}")

        lines += [
            "",
            "## Limitations",
            "",
            "- Indicators calculated on completed bars only",
            "- Partial bars clearly marked — not used for confirmed signals",
            "- Agreement analysis for training awareness only",
            "- No auto-decision generated from this report",
            "- Missing optional timeframes do not block analysis",
            "",
        ]

        lines.append(SAFETY_DECLARATION)
        return "\n".join(lines)


def build_report(session_id: str, **kwargs) -> str:
    """Convenience function to build multi-timeframe report."""
    report = MultiTimeframeReplayReport()
    return report.build(session_id, **kwargs)
