"""
reports/strategy_knowledge_ingestion_report.py — StrategyKnowledgeIngestionReportBuilder (v0.4.1.1).
[!] Knowledge Only. Research Only. No Real Orders. Production Trading: BLOCKED.
[!] auto_activated=False. Transcript-only confidence ≤ PARTIAL.
[!] Not investment advice. Long-cycle risk is NOT a short-term trading signal.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

_SAFETY_HEADER = """> [!] Knowledge Only. Research Only. No Real Orders. Production Trading: BLOCKED.
> [!] auto_activated=False. Transcript-only confidence ≤ PARTIAL.
> [!] Not investment advice. Long-cycle risk is NOT a short-term trading signal.
"""


class StrategyKnowledgeIngestionReportBuilder:
    """
    Generates a Markdown report from StrategyKnowledgeStore data.

    Safety invariants:
      read_only = True
      no_real_orders = True
      production_blocked = True
    """

    read_only: bool = True
    no_real_orders: bool = True
    production_blocked: bool = True

    VERSION = "v0.4.1.1"

    def __init__(self, report_dir: str = "reports", mode: str = "real"):
        self._report_dir = (
            report_dir if os.path.isabs(report_dir)
            else os.path.join(BASE_DIR, report_dir)
        )
        self._mode = mode

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def build(self) -> str:
        """
        Generate the Markdown report and write it to report_dir.

        Returns the absolute path of the generated file.
        """
        os.makedirs(self._report_dir, exist_ok=True)
        today = datetime.now().strftime("%Y-%m-%d")
        fname = f"strategy_knowledge_ingestion_report_{today}.md"
        path = os.path.join(self._report_dir, fname)

        content = self._render(today)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)

        logger.info("StrategyKnowledgeIngestionReport written → %s", path)
        return path

    # ------------------------------------------------------------------
    # Data loading
    # ------------------------------------------------------------------

    def _load_data(self) -> dict:
        """Load all persisted data from StrategyKnowledgeStore."""
        try:
            from knowledge.knowledge_store import StrategyKnowledgeStore
            store = StrategyKnowledgeStore()
            return {
                "items": store.load_items(),
                "sources": store.load_sources(),
                "rule_candidates": store.load_rule_candidates(),
                "avoid_conditions": store.load_avoid_conditions(),
                "risk_conditions": store.load_risk_conditions(),
                "factor_candidates": store.load_factor_candidates(),
                "summary": store.build_summary(),
            }
        except Exception as exc:
            logger.warning("StrategyKnowledgeIngestionReport: could not load data — %s", exc)
            return {
                "items": [],
                "sources": [],
                "rule_candidates": [],
                "avoid_conditions": [],
                "risk_conditions": [],
                "factor_candidates": [],
                "summary": {},
            }

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def _render(self, today: str) -> str:
        data = self._load_data()
        items = data["items"]
        sources = data["sources"]
        rule_candidates = data["rule_candidates"]
        avoid_conditions = data["avoid_conditions"]
        risk_conditions = data["risk_conditions"]
        factor_candidates = data["factor_candidates"]
        summary = data["summary"]

        # Categorise items for entry conditions
        entry_conditions = [i for i in items if i.get("category") == "entry_condition"]

        parts = [
            f"# Strategy Knowledge Ingestion Report — {today}\n",
            f"> Generated by TW Quant Cockpit {self.VERSION}\n",
            _SAFETY_HEADER,
            "\n---\n",
            self._section_overview(summary, items, sources, rule_candidates, avoid_conditions, risk_conditions, factor_candidates),
            self._section_sources(sources),
            self._section_rule_candidates(rule_candidates),
            self._section_entry_conditions(entry_conditions),
            self._section_avoid_conditions(avoid_conditions),
            self._section_risk_conditions(risk_conditions),
            self._section_factor_candidates(factor_candidates),
            self._section_rule_governance(rule_candidates),
            self._section_safety_declaration(),
        ]
        return "\n".join(parts)

    # ------------------------------------------------------------------
    # Sections
    # ------------------------------------------------------------------

    def _section_overview(
        self, summary: dict, items: list, sources: list,
        rule_candidates: list, avoid_conditions: list,
        risk_conditions: list, factor_candidates: list,
    ) -> str:
        total = len(items)
        no_data = total == 0 and not sources
        lines = [
            "## 1. 總覽 (Overview)\n",
            f"| 項目 | 值 |",
            f"|------|---|",
            f"| Mode | {self._mode} |",
            f"| Knowledge Only | True |",
            f"| No Real Orders | True |",
            f"| Production Blocked | True |",
            f"| Files / Sources | {len(sources)} |",
            f"| Knowledge Items | {total if not no_data else 'No knowledge items found'} |",
            f"| Rule Candidates | {len(rule_candidates)} |",
            f"| Avoid Conditions | {len(avoid_conditions)} |",
            f"| Risk Conditions | {len(risk_conditions)} |",
            f"| Factor Candidates | {len(factor_candidates)} |",
        ]
        if summary.get("latest_ingestion_at"):
            lines.append(f"| Latest Ingestion | {summary['latest_ingestion_at']} |")
        lines.append("")
        return "\n".join(lines)

    def _section_sources(self, sources: list) -> str:
        lines = ["## 2. Knowledge Sources\n"]
        if not sources:
            lines.append("_No knowledge sources found._\n")
            return "\n".join(lines)
        lines.append("| Source ID | Title | Type | Media Source | Generated At | Item Count |")
        lines.append("|-----------|-------|------|-------------|-------------|------------|")
        for s in sources:
            sid = s.get("source_id", "")
            title = _truncate(s.get("title", ""), 40)
            stype = s.get("source_type", "")
            media = s.get("media_source", "")
            gen_at = s.get("generated_at", "")
            item_count = s.get("item_count", "—")
            lines.append(f"| {sid} | {title} | {stype} | {media} | {gen_at} | {item_count} |")
        lines.append("")
        return "\n".join(lines)

    def _section_rule_candidates(self, rule_candidates: list) -> str:
        lines = ["## 3. Rule Candidates\n"]
        if not rule_candidates:
            lines.append("_No rule candidates found._\n")
            return "\n".join(lines)
        lines.append("| Suggested Rule ID | Category | Statement | Confidence | Existing Rule Match | Status | Auto Activated |")
        lines.append("|-------------------|----------|-----------|------------|--------------------|----|----------------|")
        for rc in rule_candidates:
            rule_id = rc.get("suggested_rule_id", "")
            cat = rc.get("category", "")
            stmt = _truncate(rc.get("statement", ""), 80)
            conf = rc.get("confidence", "")
            existing = rc.get("existing_rule_match", "")
            status = rc.get("governance_status", "")
            auto = rc.get("auto_activated", False)
            lines.append(f"| {rule_id} | {cat} | {stmt} | {conf} | {existing} | {status} | {auto} |")
        lines.append("")
        return "\n".join(lines)

    def _section_entry_conditions(self, entry_conditions: list) -> str:
        lines = ["## 4. Entry Conditions\n"]
        if not entry_conditions:
            lines.append("_No entry conditions extracted._\n")
            return "\n".join(lines)
        for item in entry_conditions:
            stmt = item.get("statement", "")
            conf = item.get("confidence", "")
            src = item.get("source_id", "")
            lines.append(f"- **[{conf}]** {stmt} _(source: {src})_")
        lines.append("")
        return "\n".join(lines)

    def _section_avoid_conditions(self, avoid_conditions: list) -> str:
        lines = ["## 5. Avoid Conditions\n"]
        if not avoid_conditions:
            lines.append("_No avoid conditions extracted._\n")
            return "\n".join(lines)
        for item in avoid_conditions:
            stmt = item.get("statement", "") if isinstance(item, dict) else item.statement
            conf = item.get("confidence", "") if isinstance(item, dict) else item.confidence
            src = item.get("source_id", "") if isinstance(item, dict) else item.source_id
            lines.append(f"- **[{conf}]** {stmt} _(source: {src})_")
        lines.append("")
        return "\n".join(lines)

    def _section_risk_conditions(self, risk_conditions: list) -> str:
        lines = ["## 6. Risk Conditions\n"]
        if not risk_conditions:
            lines.append("_No risk conditions extracted._\n")
            return "\n".join(lines)
        for item in risk_conditions:
            stmt = item.get("statement", "") if isinstance(item, dict) else item.statement
            conf = item.get("confidence", "") if isinstance(item, dict) else item.confidence
            src = item.get("source_id", "") if isinstance(item, dict) else item.source_id
            caveats = item.get("caveats", "") if isinstance(item, dict) else item.caveats
            line = f"- **[{conf}]** {stmt} _(source: {src})_"
            if caveats:
                line += f"\n  > {caveats}"
            lines.append(line)
        lines.append("")
        return "\n".join(lines)

    def _section_factor_candidates(self, factor_candidates: list) -> str:
        lines = ["## 7. Feature / Factor Candidate Mapping\n"]
        if not factor_candidates:
            lines.append("_No factor candidates extracted._\n")
            return "\n".join(lines)
        lines.append("| Knowledge ID | Statement | Suggested Feature Name | Source |")
        lines.append("|-------------|-----------|----------------------|--------|")
        for item in factor_candidates:
            kid = item.get("knowledge_id", "") if isinstance(item, dict) else item.knowledge_id
            stmt = _truncate(
                item.get("statement", "") if isinstance(item, dict) else item.statement, 60
            )
            feat = item.get("suggested_feature_name", "") if isinstance(item, dict) else item.suggested_feature_name
            src = item.get("source_id", "") if isinstance(item, dict) else item.source_id
            lines.append(f"| {kid} | {stmt} | {feat} | {src} |")
        lines.append("")
        return "\n".join(lines)

    def _section_rule_governance(self, rule_candidates: list) -> str:
        lines = ["## 8. Rule Governance Integration\n"]
        mapped = [rc for rc in rule_candidates if rc.get("governance_status") == "MAPPED_TO_EXISTING"]
        candidates = [rc for rc in rule_candidates if rc.get("governance_status") == "CANDIDATE"]
        lines.append(f"- **Mapped to Existing Rules**: {len(mapped)}")
        lines.append(f"- **New Candidates (needs review)**: {len(candidates)}")
        lines.append(f"- **auto_activated**: False (all candidates)")
        lines.append(f"- **needs_review**: True (all candidates)")
        lines.append("")
        if mapped:
            lines.append("### Mapped to Existing\n")
            for rc in mapped:
                lines.append(f"- `{rc.get('suggested_rule_id', '')}` → `{rc.get('existing_rule_match', '')}`")
            lines.append("")
        if candidates:
            lines.append("### New Candidates\n")
            for rc in candidates:
                lines.append(f"- `{rc.get('suggested_rule_id', '')}` — pending governance review")
            lines.append("")
        return "\n".join(lines)

    def _section_safety_declaration(self) -> str:
        return (
            "## 9. 安全聲明 (Safety Declaration)\n\n"
            "- **Knowledge Only** — This report contains extracted observations from transcripts only.\n"
            "- **Research Only** — No results here constitute actionable trading signals.\n"
            "- **No Real Orders** — No order generation. No brokerage connection. No execution.\n"
            "- **auto_activated=False** — No rule candidate is auto-activated. All require explicit human review and promotion.\n"
            "- **Transcript-only confidence ≤ PARTIAL** — Confidence is capped at PARTIAL for all transcript-sourced items.\n"
            "- **Not Investment Advice** — This system does not provide investment advice.\n"
            "- **Long-cycle Risk** — Long-cycle crash watch observations are NOT short-term sell signals. "
            "They are observational risk notes only.\n"
        )


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _truncate(text: str, max_len: int) -> str:
    """Truncate text to max_len characters, replacing | with / for Markdown tables."""
    text = str(text).replace("|", "/").replace("\n", " ")
    if len(text) > max_len:
        return text[:max_len - 1] + "…"
    return text
