"""paper_trading/__init__.py — Live Paper Trading Foundation v1.6.0.
[!] PAPER TRADING ONLY. NO REAL ORDERS. NO BROKER. PRODUCTION TRADING: BLOCKED.
[!] All paper objects are SIMULATION_ONLY. NOT_A_REAL_ORDER. NO_BROKER_CALL.
[!] NO_REAL_ACCOUNT. NO_FORMAL_PORTFOLIO_LEDGER_WRITE.
"""
PAPER_TRADING_VERSION = "1.6.0"
PAPER_TRADING_STAGE = "FOUNDATION"
PAPER_TRADING_RESEARCH_ONLY = True
NO_REAL_ORDERS = True
BROKER_EXECUTION_ENABLED = False
PRODUCTION_TRADING_BLOCKED = True
REAL_ORDER_CREATION_ENABLED = False
REAL_ORDER_EXECUTION_ENABLED = False
BROKER_CONNECTION_ENABLED = False
LIVE_ACCOUNT_SYNC_ENABLED = False
PRODUCTION_TRADING_ENABLED = False
REAL_PORTFOLIO_LEDGER_WRITE_ENABLED = False
AUTO_REAL_TRADING_ENABLED = False
REAL_AUTO_REBALANCE_ENABLED = False
REAL_HEDGING_EXECUTION_ENABLED = False
MARGIN_ENABLED = False
SHORT_SELLING_ENABLED = False
PAPER_ORDER_CREATION_ENABLED = True
PAPER_ORDER_EXECUTION_ENABLED = True
PAPER_FILL_SIMULATION_ENABLED = True
PAPER_LEDGER_WRITE_ENABLED = True
