"""paper_trading/enums_v160.py — Paper Trading Enumerations v1.6.0.
[!] PAPER TRADING ONLY. NO REAL ORDERS. SIMULATION_ONLY.
"""
from __future__ import annotations
from enum import Enum


class PaperSessionStatus(Enum):
    CREATED = "CREATED"
    READY = "READY"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    HALTED = "HALTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RECOVERED = "RECOVERED"
    CANCELLED = "CANCELLED"


class MarketSessionStatus(Enum):
    PRE_OPEN = "PRE_OPEN"
    OPEN = "OPEN"
    BREAK = "BREAK"
    CLOSED = "CLOSED"
    NON_TRADING_DAY = "NON_TRADING_DAY"
    UNKNOWN = "UNKNOWN"


class DataMode(Enum):
    LIVE = "LIVE"
    DELAYED = "DELAYED"
    REPLAY = "REPLAY"
    FIXTURE = "FIXTURE"
    OFFLINE = "OFFLINE"


class PaperOrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class PaperOrderSide(Enum):
    BUY = "BUY"
    SELL = "SELL"
    # SHORT and SELL_SHORT permanently excluded — no short selling


class PaperOrderStatus(Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    QUEUED = "QUEUED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    HALTED = "HALTED"


class PaperFillStatus(Enum):
    SIMULATED = "SIMULATED"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"
    REJECTED = "REJECTED"


class PaperRiskStatus(Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    RESTRICTED = "RESTRICTED"
    BLOCKED = "BLOCKED"


class PaperEventType(Enum):
    SESSION_CREATED = "SESSION_CREATED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_PAUSED = "SESSION_PAUSED"
    SESSION_RESUMED = "SESSION_RESUMED"
    SESSION_HALTED = "SESSION_HALTED"
    SESSION_COMPLETED = "SESSION_COMPLETED"
    MARKET_STATE_CHANGED = "MARKET_STATE_CHANGED"
    DATA_RECEIVED = "DATA_RECEIVED"
    SIGNAL_RECEIVED = "SIGNAL_RECEIVED"
    RISK_CHECKED = "RISK_CHECKED"
    PAPER_ORDER_CREATED = "PAPER_ORDER_CREATED"
    PAPER_ORDER_REJECTED = "PAPER_ORDER_REJECTED"
    PAPER_ORDER_QUEUED = "PAPER_ORDER_QUEUED"
    PAPER_ORDER_PARTIALLY_FILLED = "PAPER_ORDER_PARTIALLY_FILLED"
    PAPER_ORDER_FILLED = "PAPER_ORDER_FILLED"
    PAPER_ORDER_CANCELLED = "PAPER_ORDER_CANCELLED"
    POSITION_UPDATED = "POSITION_UPDATED"
    CASH_UPDATED = "CASH_UPDATED"
    PNL_UPDATED = "PNL_UPDATED"
    SNAPSHOT_CREATED = "SNAPSHOT_CREATED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"


class LatencyModel(Enum):
    ZERO_DISCLOSED = "ZERO_DISCLOSED"
    FIXED_MS = "FIXED_MS"
    EVENT_COUNT_DELAY = "EVENT_COUNT_DELAY"


class SlippageModel(Enum):
    FIXED_BPS = "FIXED_BPS"
    SPREAD_BASED = "SPREAD_BASED"
    PARTICIPATION_BASED = "PARTICIPATION_BASED"
    VOLATILITY_ADJUSTED = "VOLATILITY_ADJUSTED"


class KillSwitchReason(Enum):
    MANUAL_HALT = "MANUAL_HALT"
    MAX_SESSION_LOSS = "MAX_SESSION_LOSS"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    MAX_REJECTED_ORDERS = "MAX_REJECTED_ORDERS"
    MAX_MALFORMED_EVENTS = "MAX_MALFORMED_EVENTS"
    DATA_STALE = "DATA_STALE"
    DATA_FEED_LOST = "DATA_FEED_LOST"
    LEDGER_HASH_MISMATCH = "LEDGER_HASH_MISMATCH"
    RECONCILIATION_FAILURE = "RECONCILIATION_FAILURE"
    SAFETY_CONTRACT_VIOLATION = "SAFETY_CONTRACT_VIOLATION"
