"""
paper_trading/small_capital_strategy/__init__.py
Small Capital Growth Strategy Template v1.7.0.
[!] RESEARCH ONLY. PAPER ONLY. NO REAL ORDERS. NO BROKER. NOT INVESTMENT ADVICE.
[!] SMALL CAPITAL STRATEGY ONLY. NO REAL ACCOUNT. NO PRODUCTION TRADING.
"""
from __future__ import annotations

VERSION = "1.7.0"
RELEASE_NAME = "Small Capital Growth Strategy Template"
BASE_RELEASE = "1.6.9.1 Stable Rollup Compatibility Hotfix"

# Safety flags — small capital strategy specific
SMALL_CAPITAL_STRATEGY_AVAILABLE = True
SMALL_CAPITAL_STRATEGY_RESEARCH_ONLY = True
SMALL_CAPITAL_STRATEGY_PAPER_ONLY = True
SMALL_CAPITAL_STRATEGY_READ_ONLY = True
SMALL_CAPITAL_STRATEGY_DETERMINISTIC = True
SMALL_CAPITAL_STRATEGY_NOT_INVESTMENT_ADVICE = True

SMALL_CAPITAL_REAL_TRADING_ENABLED = False
SMALL_CAPITAL_REAL_ACCOUNT_ENABLED = False
SMALL_CAPITAL_REAL_ORDER_ENABLED = False
SMALL_CAPITAL_BROKER_EXECUTION_ENABLED = False
SMALL_CAPITAL_PRODUCTION_TRADING_ENABLED = False
SMALL_CAPITAL_LIVE_EXECUTION_ENABLED = False
SMALL_CAPITAL_AUTO_ORDER_ENABLED = False
SMALL_CAPITAL_AUTO_STOP_LOSS_ENABLED = False
SMALL_CAPITAL_AUTO_TAKE_PROFIT_ENABLED = False
SMALL_CAPITAL_MARGIN_ENABLED = False
SMALL_CAPITAL_DAY_TRADING_PRIMARY_ENABLED = False

# Canonical safety aliases (match paper_trading/__init__.py)
NO_REAL_ORDERS = True
BROKER_EXECUTION_ENABLED = False
PRODUCTION_TRADING_BLOCKED = True

# v1.7.1 Watchlist Strategy Layer safety flags
WATCHLIST_STRATEGY_AVAILABLE            = True
WATCHLIST_STRATEGY_RESEARCH_ONLY        = True
WATCHLIST_STRATEGY_PAPER_ONLY           = True
WATCHLIST_STRATEGY_READ_ONLY            = True
WATCHLIST_STRATEGY_DETERMINISTIC        = True
WATCHLIST_STRATEGY_NOT_INVESTMENT_ADVICE = True

WATCHLIST_REAL_TRADING_ENABLED          = False
WATCHLIST_REAL_ACCOUNT_ENABLED          = False
WATCHLIST_REAL_ORDER_ENABLED            = False
WATCHLIST_BROKER_EXECUTION_ENABLED      = False
WATCHLIST_PRODUCTION_TRADING_ENABLED    = False
WATCHLIST_LIVE_EXECUTION_ENABLED        = False
WATCHLIST_AUTO_ORDER_ENABLED            = False
WATCHLIST_MARGIN_ENABLED                = False
