"""
paper_trading/small_capital_strategy/abc_scenario_registry_v172.py
Scenario registry for A/B/C Buy Point Execution Plan v1.7.2.
70+ scenarios. No skip. No xfail.
[!] Research Only. Paper Only. No Real Orders. Not Investment Advice.
"""
from __future__ import annotations
from typing import List, Dict, Set

_DS = 172  # deterministic seed

ABC_SCENARIO_REGISTRY: List[Dict] = [
    # ── A Buy Point (18) ────────────────────────────────────────────────────
    {"scenario_id": "abc_sc_001", "category": "a_buy_point",
     "name": "a_valid_ready",
     "description": "A buy point with all conditions met => READY",
     "expected_status": "READY", "fixture_id": "abc_001", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_002", "category": "a_buy_point",
     "name": "a_missing_ma20_blocked",
     "description": "A: close below MA20 => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_002", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_003", "category": "a_buy_point",
     "name": "a_below_ma60_blocked",
     "description": "A: close below MA60 => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_003", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_004", "category": "a_buy_point",
     "name": "a_financing_overheated_blocked",
     "description": "A: financing > 30% => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_004", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_005", "category": "a_buy_point",
     "name": "a_institutional_selling_blocked",
     "description": "A: institutional net buy days < 0 => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_005", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_006", "category": "a_buy_point",
     "name": "a_volume_not_contracting_waiting",
     "description": "A: volume not contracting => WAITING_CONFIRMATION",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_006", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_007", "category": "a_buy_point",
     "name": "a_no_stop_loss_blocked",
     "description": "A: entry price <= stop loss => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_007", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_008", "category": "a_buy_point",
     "name": "a_bear_regime_core_allowed",
     "description": "A: Bear regime + CORE tier => allowed",
     "expected_status": "READY", "fixture_id": "abc_008", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_009", "category": "a_buy_point",
     "name": "a_bear_regime_non_core_blocked",
     "description": "A: Bear regime + MAIN_THEME tier => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_009", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_010", "category": "a_buy_point",
     "name": "a_weak_theme_blocked",
     "description": "A: WEAK theme => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_010", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_011", "category": "a_buy_point",
     "name": "a_excluded_tier_blocked",
     "description": "A: EXCLUDED tier => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_011", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_012", "category": "a_buy_point",
     "name": "a_kd_dead_cross_waiting",
     "description": "A: KD dead cross present => DEGRADED",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_012", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_013", "category": "a_buy_point",
     "name": "a_strong_theme_ready",
     "description": "A: STRONG theme, all conditions met => READY",
     "expected_status": "READY", "fixture_id": "abc_013", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_014", "category": "a_buy_point",
     "name": "a_leading_theme_core_ready",
     "description": "A: LEADING theme + CORE tier => READY",
     "expected_status": "READY", "fixture_id": "abc_014", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_015", "category": "a_buy_point",
     "name": "a_neutral_regime_ready",
     "description": "A: NEUTRAL regime + MAIN_THEME => READY",
     "expected_status": "READY", "fixture_id": "abc_015", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_016", "category": "a_buy_point",
     "name": "a_bull_regime_ready",
     "description": "A: BULL regime => READY",
     "expected_status": "READY", "fixture_id": "abc_016", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_017", "category": "a_buy_point",
     "name": "a_second_wave_tier_ready",
     "description": "A: SECOND_WAVE tier => READY",
     "expected_status": "READY", "fixture_id": "abc_017", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_018", "category": "a_buy_point",
     "name": "a_training_tier_cap_applied",
     "description": "A: TRAINING tier => training cap applied",
     "expected_status": "READY", "fixture_id": "abc_018", "deterministic_seed": _DS},

    # ── B Buy Point (16) ────────────────────────────────────────────────────
    {"scenario_id": "abc_sc_019", "category": "b_buy_point",
     "name": "b_valid_ready",
     "description": "B buy point with all conditions met => READY",
     "expected_status": "READY", "fixture_id": "abc_019", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_020", "category": "b_buy_point",
     "name": "b_low_volume_blocked",
     "description": "B: volume_ratio < 1.5 => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_020", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_021", "category": "b_buy_point",
     "name": "b_third_extended_candle_blocked",
     "description": "B: third extended red candle => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_021", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_022", "category": "b_buy_point",
     "name": "b_bear_regime_blocked",
     "description": "B: BEAR regime => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_022", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_023", "category": "b_buy_point",
     "name": "b_too_extended_degraded",
     "description": "B: breakout too extended from MA20 => DEGRADED",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_023", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_024", "category": "b_buy_point",
     "name": "b_no_stop_loss_blocked",
     "description": "B: no valid stop loss => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_024", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_025", "category": "b_buy_point",
     "name": "b_training_cap_enforced",
     "description": "B: TRAINING tier => position capped at 15000",
     "expected_status": "READY", "fixture_id": "abc_025", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_026", "category": "b_buy_point",
     "name": "b_financing_overheated_blocked",
     "description": "B: financing overheated => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_026", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_027", "category": "b_buy_point",
     "name": "b_core_tier_blocked",
     "description": "B: CORE tier not allowed for B => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_027", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_028", "category": "b_buy_point",
     "name": "b_excluded_tier_blocked",
     "description": "B: EXCLUDED tier => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_028", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_029", "category": "b_buy_point",
     "name": "b_consolidation_too_short",
     "description": "B: consolidation < 2 weeks => DEGRADED",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_029", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_030", "category": "b_buy_point",
     "name": "b_consolidation_too_long",
     "description": "B: consolidation > 6 weeks => DEGRADED",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_030", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_031", "category": "b_buy_point",
     "name": "b_main_theme_ready",
     "description": "B: MAIN_THEME tier => READY",
     "expected_status": "READY", "fixture_id": "abc_031", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_032", "category": "b_buy_point",
     "name": "b_second_wave_ready",
     "description": "B: SECOND_WAVE tier => READY (not preferred)",
     "expected_status": "READY", "fixture_id": "abc_032", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_033", "category": "b_buy_point",
     "name": "b_bull_regime_ready",
     "description": "B: BULL regime => READY",
     "expected_status": "READY", "fixture_id": "abc_033", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_034", "category": "b_buy_point",
     "name": "b_risk_off_blocked",
     "description": "B: RISK_OFF regime => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_034", "deterministic_seed": _DS},

    # ── C Buy Point (16) ────────────────────────────────────────────────────
    {"scenario_id": "abc_sc_035", "category": "c_buy_point",
     "name": "c_valid_ready",
     "description": "C buy point with all conditions met => READY",
     "expected_status": "READY", "fixture_id": "abc_035", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_036", "category": "c_buy_point",
     "name": "c_no_first_wave_blocked",
     "description": "C: had_first_wave=False => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_036", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_037", "category": "c_buy_point",
     "name": "c_pullback_incomplete_waiting",
     "description": "C: pullback not completed => WAITING_CONFIRMATION",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_037", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_038", "category": "c_buy_point",
     "name": "c_reclaim_failed_invalidated",
     "description": "C: MA20 reclaim fails => INVALIDATED",
     "expected_status": "INVALIDATED", "fixture_id": "abc_038", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_039", "category": "c_buy_point",
     "name": "c_risk_off_blocked",
     "description": "C: RISK_OFF regime => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_039", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_040", "category": "c_buy_point",
     "name": "c_institutional_reaccumulation_missing_waiting",
     "description": "C: institutional reaccumulation missing => WAITING_CONFIRMATION",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_040", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_041", "category": "c_buy_point",
     "name": "c_no_stop_loss_blocked",
     "description": "C: no valid stop loss => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_041", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_042", "category": "c_buy_point",
     "name": "c_second_wave_ready",
     "description": "C: SECOND_WAVE tier => READY",
     "expected_status": "READY", "fixture_id": "abc_042", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_043", "category": "c_buy_point",
     "name": "c_main_theme_ready",
     "description": "C: MAIN_THEME tier => READY",
     "expected_status": "READY", "fixture_id": "abc_043", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_044", "category": "c_buy_point",
     "name": "c_excluded_tier_blocked",
     "description": "C: EXCLUDED tier => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_044", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_045", "category": "c_buy_point",
     "name": "c_core_tier_blocked",
     "description": "C: CORE tier not allowed => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_045", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_046", "category": "c_buy_point",
     "name": "c_training_tier_blocked",
     "description": "C: TRAINING tier not in allowed tiers => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_046", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_047", "category": "c_buy_point",
     "name": "c_financing_overheated_blocked",
     "description": "C: financing overheated => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_047", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_048", "category": "c_buy_point",
     "name": "c_bull_regime_ready",
     "description": "C: BULL regime => READY",
     "expected_status": "READY", "fixture_id": "abc_048", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_049", "category": "c_buy_point",
     "name": "c_below_ma20_blocked",
     "description": "C: close below MA20 => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_049", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_050", "category": "c_buy_point",
     "name": "c_kd_golden_cross_ready",
     "description": "C: KD golden cross present => READY",
     "expected_status": "READY", "fixture_id": "abc_050", "deterministic_seed": _DS},

    # ── Paper Intent (8) ────────────────────────────────────────────────────
    {"scenario_id": "abc_sc_051", "category": "paper_intent",
     "name": "paper_buy",
     "description": "READY plan => PAPER_BUY intent",
     "expected_status": "READY", "fixture_id": "abc_051", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_052", "category": "paper_intent",
     "name": "paper_add",
     "description": "Existing position add => PAPER_ADD intent",
     "expected_status": "READY", "fixture_id": "abc_052", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_053", "category": "paper_intent",
     "name": "paper_reduce",
     "description": "Partial exit => PAPER_REDUCE intent",
     "expected_status": "READY", "fixture_id": "abc_053", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_054", "category": "paper_intent",
     "name": "paper_exit",
     "description": "Full exit => PAPER_EXIT intent",
     "expected_status": "READY", "fixture_id": "abc_054", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_055", "category": "paper_intent",
     "name": "paper_wait",
     "description": "Waiting confirmation => PAPER_WAIT intent",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_055", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_056", "category": "paper_intent",
     "name": "paper_block",
     "description": "Blocked plan => PAPER_BLOCK intent",
     "expected_status": "BLOCKED", "fixture_id": "abc_056", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_057", "category": "paper_intent",
     "name": "real_order_requested_blocked",
     "description": "real_order_requested=True => PAPER_BLOCK with REAL_ORDER_REQUESTED",
     "expected_status": "BLOCKED", "fixture_id": "abc_057", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_058", "category": "paper_intent",
     "name": "broker_requested_blocked",
     "description": "broker_execution_requested=True => PAPER_BLOCK with BROKER_REQUESTED",
     "expected_status": "BLOCKED", "fixture_id": "abc_058", "deterministic_seed": _DS},

    # ── Integration (13) ────────────────────────────────────────────────────
    {"scenario_id": "abc_sc_059", "category": "integration",
     "name": "core_a_conservative",
     "description": "CORE tier + A buy point + BULL regime => conservative entry",
     "expected_status": "READY", "fixture_id": "abc_059", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_060", "category": "integration",
     "name": "main_theme_abc_allowed",
     "description": "MAIN_THEME tier allows A/B/C buy points",
     "expected_status": "READY", "fixture_id": "abc_060", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_061", "category": "integration",
     "name": "second_wave_c_preferred",
     "description": "SECOND_WAVE tier prefers C/A buy points",
     "expected_status": "READY", "fixture_id": "abc_061", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_062", "category": "integration",
     "name": "training_cap_15000",
     "description": "TRAINING tier => position capped at 15000 TWD",
     "expected_status": "READY", "fixture_id": "abc_062", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_063", "category": "integration",
     "name": "excluded_blocked",
     "description": "EXCLUDED tier => BLOCKED for all buy points",
     "expected_status": "BLOCKED", "fixture_id": "abc_063", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_064", "category": "integration",
     "name": "unknown_regime_downgrade",
     "description": "UNKNOWN regime + non-CORE => degraded warning",
     "expected_status": "WAITING_CONFIRMATION", "fixture_id": "abc_064", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_065", "category": "integration",
     "name": "risk_exceeds_budget_blocked",
     "description": "Position risk > 2x max risk => BLOCKED",
     "expected_status": "BLOCKED", "fixture_id": "abc_065", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_066", "category": "integration",
     "name": "full_plan_a_main_theme_bull",
     "description": "Complete A plan: MAIN_THEME + BULL + all conditions => full scorecard",
     "expected_status": "READY", "fixture_id": "abc_066", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_067", "category": "integration",
     "name": "full_plan_b_training_bull",
     "description": "Complete B plan: TRAINING + BULL + cap applied",
     "expected_status": "READY", "fixture_id": "abc_067", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_068", "category": "integration",
     "name": "full_plan_c_second_wave_neutral",
     "description": "Complete C plan: SECOND_WAVE + NEUTRAL",
     "expected_status": "READY", "fixture_id": "abc_068", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_069", "category": "integration",
     "name": "forbidden_rules_all_pass",
     "description": "All forbidden rules pass for normal paper plan",
     "expected_status": "READY", "fixture_id": "abc_069", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_070", "category": "integration",
     "name": "scorecard_weights_sum_100",
     "description": "Scorecard weights always sum to 100",
     "expected_status": "PASS", "fixture_id": "abc_070", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_071", "category": "integration",
     "name": "no_a_plus_grade",
     "description": "Grade A+ is never returned — max is A",
     "expected_status": "PASS", "fixture_id": "abc_071", "deterministic_seed": _DS},

    # ── Reports (5) ─────────────────────────────────────────────────────────
    {"scenario_id": "abc_sc_072", "category": "reports",
     "name": "markdown_report",
     "description": "render_markdown returns string with 16 sections",
     "expected_status": "PASS", "fixture_id": "abc_072", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_073", "category": "reports",
     "name": "json_report",
     "description": "render_json returns valid JSON with not_investment_advice=True",
     "expected_status": "PASS", "fixture_id": "abc_073", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_074", "category": "reports",
     "name": "csv_report",
     "description": "render_csv returns CSV with header + data row",
     "expected_status": "PASS", "fixture_id": "abc_074", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_075", "category": "reports",
     "name": "not_investment_advice_marker",
     "description": "All report formats carry not_investment_advice marker",
     "expected_status": "PASS", "fixture_id": "abc_075", "deterministic_seed": _DS},
    {"scenario_id": "abc_sc_076", "category": "reports",
     "name": "console_summary",
     "description": "render_console_summary returns compact non-empty string",
     "expected_status": "PASS", "fixture_id": "abc_076", "deterministic_seed": _DS},
]


def get_scenario_count() -> int:
    """Return total number of registered scenarios."""
    return len(ABC_SCENARIO_REGISTRY)


def get_scenario_categories() -> Set[str]:
    """Return set of unique scenario categories."""
    return {s["category"] for s in ABC_SCENARIO_REGISTRY}


def get_scenarios_by_category(category: str) -> List[Dict]:
    """Return scenarios matching a category."""
    return [s for s in ABC_SCENARIO_REGISTRY if s["category"] == category]


def get_scenario_by_id(scenario_id: str) -> Dict:
    """Return scenario by ID or empty dict if not found."""
    for s in ABC_SCENARIO_REGISTRY:
        if s["scenario_id"] == scenario_id:
            return s
    return {}
