"""
paper_trading/small_capital_strategy/governance_stack_fixtures_v1910.py
v1.9.10 Paper Governance Stack Consolidation & Release Audit — Fixtures
[!] Paper Only. Research Only. Consolidation Only. Release Audit Only.
[!] No Real Orders. Not Investment Advice.
"""
from __future__ import annotations

_BASE = {
    "schema_version": "1910",
    "paper_only": True,
    "research_only": True,
    "simulate_only": True,
    "validation_only": True,
    "consolidation_only": True,
    "release_audit_only": True,
    "dashboard_only": True,
    "report_only": True,
    "audit_only": True,
    "no_real_orders": True,
    "no_broker": True,
    "no_margin": True,
    "no_leverage": True,
    "no_production_strategy_mutation": True,
    "no_automatic_rollback": True,
    "no_live_strategy_activation": True,
    "no_real_portfolio_rebalancing": True,
    "not_investment_advice": True,
    "demo_only": True,
    "not_for_production": True,
    "production_trading_blocked": True,
}

FIXTURES = [
    {**_BASE, "id": "GSFIX1910-001", "fixture_id": "GSFIX1910-001",
     "name": "governance_stack_version_info",
     "data": {"version": "1.9.10", "schema_version": "1910",
               "release_name": "Paper Governance Stack Consolidation & Release Audit",
               "model_count": 15, "cli_count": 14, "gui_tabs": 3}},
    {**_BASE, "id": "GSFIX1910-002", "fixture_id": "GSFIX1910-002",
     "name": "safety_flags_all_true",
     "data": {"paper_only": True, "research_only": True, "consolidation_only": True,
               "release_audit_only": True, "no_real_orders": True,
               "production_trading_blocked": True}},
    {**_BASE, "id": "GSFIX1910-003", "fixture_id": "GSFIX1910-003",
     "name": "safety_flags_blocking_false",
     "data": {"audit_executes_order": False, "audit_mutates_strategy": False,
               "audit_rebalances_real_portfolio": False,
               "dashboard_mutates_strategy": False,
               "dashboard_places_real_order": False,
               "export_triggers_real_order": False}},
    {**_BASE, "id": "GSFIX1910-004", "fixture_id": "GSFIX1910-004",
     "name": "covered_versions_list",
     "data": {"covered_versions": ["1.9.4", "1.9.5", "1.9.6", "1.9.7", "1.9.8", "1.9.9"]}},
    {**_BASE, "id": "GSFIX1910-005", "fixture_id": "GSFIX1910-005",
     "name": "cli_commands_list",
     "data": {"commands": [
         "governance-stack-version", "governance-stack-audit",
         "governance-stack-summary", "governance-stack-cli-audit",
         "governance-stack-gui-audit", "governance-stack-health-audit",
         "governance-stack-gate-audit", "governance-stack-fixture-audit",
         "governance-stack-scenario-audit", "governance-stack-safety-audit",
         "governance-stack-compatibility", "governance-stack-report",
         "governance-stack-health", "governance-stack-gate"]}},
    {**_BASE, "id": "GSFIX1910-006", "fixture_id": "GSFIX1910-006",
     "name": "gui_tabs_list",
     "data": {"tabs": ["governance_stack_audit", "release_audit", "compatibility_summary"]}},
    {**_BASE, "id": "GSFIX1910-007", "fixture_id": "GSFIX1910-007",
     "name": "model_names_list",
     "data": {"models": [
         "PaperGovernanceStackAuditInput", "PaperGovernanceStackAuditResult",
         "PaperGovernanceStackModule", "PaperGovernanceStackVersion",
         "PaperGovernanceStackCompatibilityResult"]}},
    {**_BASE, "id": "GSFIX1910-008", "fixture_id": "GSFIX1910-008",
     "name": "forbidden_actions_sample",
     "data": {"forbidden": ["BUY", "SELL", "ORDER", "BROKER_ORDER", "LIVE_ACTIVATE"]}},
    {**_BASE, "id": "GSFIX1910-009", "fixture_id": "GSFIX1910-009",
     "name": "allowed_audit_actions_sample",
     "data": {"allowed": ["PAPER_AUDIT", "PAPER_REPORT", "PAPER_VALIDATE",
                           "PAPER_CONSOLIDATE", "PAPER_RELEASE_AUDIT"]}},
    {**_BASE, "id": "GSFIX1910-010", "fixture_id": "GSFIX1910-010",
     "name": "full_audit_result_pass",
     "data": {"all_passed": True, "status": "PASS", "passed": 28, "failed": 0}},
    {**_BASE, "id": "GSFIX1910-011", "fixture_id": "GSFIX1910-011",
     "name": "module_v194_fixture",
     "data": {"version": "1.9.4", "module": "strategy_monitoring",
               "health_pass": True, "gate_pass": True, "cli_registered": True}},
    {**_BASE, "id": "GSFIX1910-012", "fixture_id": "GSFIX1910-012",
     "name": "module_v195_fixture",
     "data": {"version": "1.9.5", "module": "strategy_review_alert",
               "health_pass": True, "gate_pass": True, "cli_registered": True}},
    {**_BASE, "id": "GSFIX1910-013", "fixture_id": "GSFIX1910-013",
     "name": "module_v196_fixture",
     "data": {"version": "1.9.6", "module": "decision_registry",
               "health_pass": True, "gate_pass": True, "cli_registered": True}},
    {**_BASE, "id": "GSFIX1910-014", "fixture_id": "GSFIX1910-014",
     "name": "module_v197_fixture",
     "data": {"version": "1.9.7", "module": "strategy_governance_dashboard",
               "health_pass": True, "gate_pass": True, "cli_registered": True}},
    {**_BASE, "id": "GSFIX1910-015", "fixture_id": "GSFIX1910-015",
     "name": "module_v198_fixture",
     "data": {"version": "1.9.8", "module": "portfolio_governance",
               "health_pass": True, "gate_pass": True, "cli_registered": True}},
    {**_BASE, "id": "GSFIX1910-016", "fixture_id": "GSFIX1910-016",
     "name": "module_v199_fixture",
     "data": {"version": "1.9.9", "module": "portfolio_risk_report",
               "health_pass": True, "gate_pass": True, "cli_registered": True}},
    {**_BASE, "id": "GSFIX1910-017", "fixture_id": "GSFIX1910-017",
     "name": "cli_audit_all_registered",
     "data": {"all_registered": True, "missing_commands": [],
               "checked_count": 12, "total_commands": 300}},
    {**_BASE, "id": "GSFIX1910-018", "fixture_id": "GSFIX1910-018",
     "name": "gui_audit_all_tabs_present",
     "data": {"all_tabs_present": True, "missing_tabs": [],
               "panel_version": "1.9.10", "total_tabs": 170}},
    {**_BASE, "id": "GSFIX1910-019", "fixture_id": "GSFIX1910-019",
     "name": "health_audit_all_pass",
     "data": {"all_health_pass": True, "failing_modules": [], "pass_count": 6}},
    {**_BASE, "id": "GSFIX1910-020", "fixture_id": "GSFIX1910-020",
     "name": "gate_audit_all_pass",
     "data": {"all_gates_pass": True, "failing_modules": [], "pass_count": 6}},
    {**_BASE, "id": "GSFIX1910-021", "fixture_id": "GSFIX1910-021",
     "name": "fixture_schema_consistent",
     "data": {"all_consistent": True, "consistent_count": 6, "total": 6}},
    {**_BASE, "id": "GSFIX1910-022", "fixture_id": "GSFIX1910-022",
     "name": "scenario_schema_consistent",
     "data": {"all_consistent": True, "consistent_count": 6, "total": 6}},
    {**_BASE, "id": "GSFIX1910-023", "fixture_id": "GSFIX1910-023",
     "name": "safety_audit_all_safe",
     "data": {"all_safe": True, "errors": [], "safety_flags_count": 29,
               "forbidden_actions_count": 15, "allowed_actions_count": 15}},
    {**_BASE, "id": "GSFIX1910-024", "fixture_id": "GSFIX1910-024",
     "name": "backward_compat_panel_version",
     "data": {"panel_version": "1.9.10", "version_ok": True, "all_compatible": True}},
    {**_BASE, "id": "GSFIX1910-025", "fixture_id": "GSFIX1910-025",
     "name": "release_summary_fixture",
     "data": {"version": "1.9.10", "modules_audited": 6, "cli_commands_total": 14,
               "gui_tabs_total": 3, "health_checks_total": 6, "gates_total": 6,
               "all_pass": True}},
    {**_BASE, "id": "GSFIX1910-026", "fixture_id": "GSFIX1910-026",
     "name": "unsafe_path_fixture",
     "data": {"path": "C:/production/report", "safe": False}},
    {**_BASE, "id": "GSFIX1910-027", "fixture_id": "GSFIX1910-027",
     "name": "safe_path_fixture",
     "data": {"path": "C:/Users/paper_audit/report.json", "safe": True}},
    {**_BASE, "id": "GSFIX1910-028", "fixture_id": "GSFIX1910-028",
     "name": "paper_audit_input_valid",
     "data": {"paper_only": True, "research_only": True, "consolidation_only": True,
               "no_real_orders": True, "not_investment_advice": True}},
    {**_BASE, "id": "GSFIX1910-029", "fixture_id": "GSFIX1910-029",
     "name": "paper_audit_input_blocked",
     "data": {"paper_only": False, "blocked": True}},
    {**_BASE, "id": "GSFIX1910-030", "fixture_id": "GSFIX1910-030",
     "name": "recommendation_no_action",
     "data": {"recommendation": "NO_ACTION", "recommendation_executes_order": False,
               "recommendation_mutates_strategy": False}},
    {**_BASE, "id": "GSFIX1910-031", "fixture_id": "GSFIX1910-031",
     "name": "v194_schema_version",
     "data": {"version": "1.9.4", "schema_version": "194",
               "fixture_schema_consistent": True}},
    {**_BASE, "id": "GSFIX1910-032", "fixture_id": "GSFIX1910-032",
     "name": "v195_schema_version",
     "data": {"version": "1.9.5", "schema_version": "195",
               "fixture_schema_consistent": True}},
    {**_BASE, "id": "GSFIX1910-033", "fixture_id": "GSFIX1910-033",
     "name": "v196_schema_version",
     "data": {"version": "1.9.6", "schema_version": "196",
               "fixture_schema_consistent": True}},
    {**_BASE, "id": "GSFIX1910-034", "fixture_id": "GSFIX1910-034",
     "name": "v197_schema_version",
     "data": {"version": "1.9.7", "schema_version": "197",
               "fixture_schema_consistent": True}},
    {**_BASE, "id": "GSFIX1910-035", "fixture_id": "GSFIX1910-035",
     "name": "v198_schema_version",
     "data": {"version": "1.9.8", "schema_version": "198",
               "fixture_schema_consistent": True}},
    {**_BASE, "id": "GSFIX1910-036", "fixture_id": "GSFIX1910-036",
     "name": "v199_schema_version",
     "data": {"version": "1.9.9", "schema_version": "199",
               "fixture_schema_consistent": True}},
    {**_BASE, "id": "GSFIX1910-037", "fixture_id": "GSFIX1910-037",
     "name": "governance_stack_audit_tab",
     "data": {"tab": "governance_stack_audit", "dashboard_mutates_strategy": False,
               "dashboard_places_real_order": False, "schema_version": "1910"}},
    {**_BASE, "id": "GSFIX1910-038", "fixture_id": "GSFIX1910-038",
     "name": "release_audit_tab",
     "data": {"tab": "release_audit", "dashboard_mutates_strategy": False,
               "schema_version": "1910"}},
    {**_BASE, "id": "GSFIX1910-039", "fixture_id": "GSFIX1910-039",
     "name": "compatibility_summary_tab",
     "data": {"tab": "compatibility_summary", "compatibility_check_executes_order": False,
               "schema_version": "1910"}},
    {**_BASE, "id": "GSFIX1910-040", "fixture_id": "GSFIX1910-040",
     "name": "governance_stack_health_fixture",
     "data": {"health_version": "1.9.10", "all_passed": True, "status": "PASS",
               "paper_only": True, "production_trading_blocked": True}},
    {**_BASE, "id": "GSFIX1910-041", "fixture_id": "GSFIX1910-041",
     "name": "governance_stack_gate_fixture",
     "data": {"gate_version": "1.9.10", "all_passed": True, "status": "PASS",
               "baseline_tests": 31469, "min_new_tests": 300}},
    {**_BASE, "id": "GSFIX1910-042", "fixture_id": "GSFIX1910-042",
     "name": "compatibility_result_compatible",
     "data": {"all_compatible": True, "incompatible_modules": [],
               "compatible_count": 6, "total_count": 6}},
    {**_BASE, "id": "GSFIX1910-043", "fixture_id": "GSFIX1910-043",
     "name": "compatibility_result_incompatible",
     "data": {"all_compatible": False, "incompatible_modules": ["v1.9.4"],
               "compatible_count": 5, "total_count": 6}},
    {**_BASE, "id": "GSFIX1910-044", "fixture_id": "GSFIX1910-044",
     "name": "audit_report_all_pass",
     "data": {"all_passed": True, "audit_executes_order": False,
               "audit_mutates_strategy": False, "report_triggers_real_order": False}},
    {**_BASE, "id": "GSFIX1910-045", "fixture_id": "GSFIX1910-045",
     "name": "audit_report_with_failures",
     "data": {"all_passed": False, "cli_audit_passed": False,
               "missing_commands": ["governance-stack-version"]}},
    {**_BASE, "id": "GSFIX1910-046", "fixture_id": "GSFIX1910-046",
     "name": "stack_module_v194",
     "data": {"module_version": "1.9.4", "module_name": "strategy_monitoring",
               "module_present": True, "health_pass": True, "gate_pass": True}},
    {**_BASE, "id": "GSFIX1910-047", "fixture_id": "GSFIX1910-047",
     "name": "stack_module_missing",
     "data": {"module_version": "1.9.x", "module_name": "unknown",
               "module_present": False, "health_pass": False, "gate_pass": False}},
    {**_BASE, "id": "GSFIX1910-048", "fixture_id": "GSFIX1910-048",
     "name": "v1910_fixture_schema",
     "data": {"schema_version": "1910", "paper_only": True,
               "consolidation_only": True, "release_audit_only": True}},
    {**_BASE, "id": "GSFIX1910-049", "fixture_id": "GSFIX1910-049",
     "name": "no_margin_no_leverage_fixture",
     "data": {"no_margin": True, "no_leverage": True,
               "no_production_strategy_mutation": True}},
    {**_BASE, "id": "GSFIX1910-050", "fixture_id": "GSFIX1910-050",
     "name": "governance_stack_summary_fixture",
     "data": {"version": "1.9.10", "release_name": "Paper Governance Stack Consolidation & Release Audit",
               "model_count": 15, "safety_flags": 29, "all_pass": True,
               "paper_only": True, "not_investment_advice": True}},
]

assert len(FIXTURES) == 50, f"Expected 50 fixtures, got {len(FIXTURES)}"
