"""
paper_trading/small_capital_strategy/integrated_strategy_scenarios_v178.py
Scenarios for Small Capital Strategy Integration v1.7.8. 70 scenarios.
[!] Research Only. Paper Only. No Real Orders. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List, Optional

_SCHEMA  = "178"
_POLICY  = "1.7.8-small-capital-strategy-integration"

_SCENARIOS: List[Dict[str, Any]] = [
    # ── PAPER_ENTRY_ALLOWED scenarios (10) ──────────────────────────────────
    {
        "id": "SC178-001", "name": "Bull + Leader theme + Focus watchlist + A_READY ABC",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "final_score_min": 80.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-002", "name": "Bull + Leader theme + Focus watchlist + B_READY ABC",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "B_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "final_score_min": 78.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-003", "name": "Bull + Leader theme + Focus watchlist + C_READY ABC",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "C_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "final_score_min": 75.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-004", "name": "Bull + Strong theme + Focus watchlist + A_READY ABC",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "STRONG", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "final_score_min": 72.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-005", "name": "Bull_soft + Leader theme + Focus + A_READY, journal OK",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL_SOFT", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "journal_quality_score": 80.0,
        "final_score_min": 70.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-006", "name": "Bull + Leader + Focus + B_READY + high journal score",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "B_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "journal_quality_score": 90.0,
        "final_score_min": 78.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-007", "name": "Bull + Strong + Focus + A_READY + behavior clean",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "STRONG", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "behavior_score": 90.0,
        "final_score_min": 70.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-008", "name": "Bull + Leader + Focus + C_READY + safe risk",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "C_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "risk_score": 90.0,
        "final_score_min": 72.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-009", "name": "Bull + Leader + Focus + A_READY + full score 95",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "theme_score": 95.0,
        "watchlist_score": 95.0, "abc_score": 95.0, "regime_score": 95.0,
        "final_score_min": 85.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-010", "name": "Bull + Strong + Watch watchlist + A_READY (marginal entry)",
        "expected_action": "PAPER_ENTRY_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "STRONG", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "theme_score": 80.0, "watchlist_score": 85.0, "abc_score": 90.0,
        "final_score_min": 70.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    # ── PAPER_PLAN_READY scenarios (10) ─────────────────────────────────────
    {
        "id": "SC178-011", "name": "Bull + Strong theme + Watch watchlist + B_READY",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL", "theme": "STRONG", "watchlist": "WATCH", "abc": "B_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-012", "name": "Bull_soft + Strong + Focus + B_READY",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL_SOFT", "theme": "STRONG", "watchlist": "FOCUS", "abc": "B_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-013", "name": "Bull + Leader + Watch + C_READY",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "WATCH", "abc": "C_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-014", "name": "Bull + Leader + Focus + NOT_READY ABC → plan only",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "theme_score": 95.0,
        "watchlist_score": 90.0, "abc_score": 0.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-015", "name": "Bull + Strong + Focus + A_READY + moderate risk",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL", "theme": "STRONG", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "MODERATE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-016", "name": "Bull + Watch theme + Focus + A_READY",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL", "theme": "WATCH", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "theme_score": 70.0, "watchlist_score": 90.0, "abc_score": 90.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-017", "name": "Bull + Leader + Focus + B_READY + caution behavior",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "B_READY",
        "risk_level": "SAFE", "behavior": "CAUTION", "behavior_score": 65.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-018", "name": "Neutral + Leader + Focus + A_READY",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-019", "name": "Bull + Strong + Watch + A_READY + journal 75",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL", "theme": "STRONG", "watchlist": "WATCH", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "journal_quality_score": 75.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-020", "name": "Bull_soft + Strong + Focus + C_READY",
        "expected_action": "PAPER_PLAN_READY", "has_stop_loss": True,
        "regime": "BULL_SOFT", "theme": "STRONG", "watchlist": "FOCUS", "abc": "C_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    # ── BLOCKED scenarios (15) ───────────────────────────────────────────────
    {
        "id": "SC178-021", "name": "No stop loss → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": False,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-022", "name": "Real order requested → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "real_order_requested": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-023", "name": "Broker requested → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "broker_requested": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-024", "name": "Margin requested → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "margin_requested": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-025", "name": "RISK_OFF regime no override → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "regime": "RISK_OFF", "regime_safety_override": False,
        "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-026", "name": "Behavior BLOCKED → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "BLOCKED",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-027", "name": "Risk level BLOCKED → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "BLOCKED", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-028", "name": "Watchlist EXCLUDED → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "EXCLUDED", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-029", "name": "Theme EXCLUDED → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "regime": "BULL", "theme": "EXCLUDED", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-030", "name": "ABC BLOCKED → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "BLOCKED",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-031", "name": "Production DB write attempted → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "production_db_write_attempted": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-032", "name": "Multiple blocks: no stop + broker → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": False, "broker_requested": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-033", "name": "Bear regime no override → BLOCKED via NO_TRADE (MARKET_RISK_OFF)",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "regime": "BEAR", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-034", "name": "RISK_OFF with override allowed → not BLOCKED",
        "expected_action": "OBSERVE", "has_stop_loss": True,
        "regime": "RISK_OFF", "regime_safety_override": True,
        "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-035", "name": "All good but missing symbol → BLOCKED",
        "expected_action": "BLOCKED", "has_stop_loss": True,
        "symbol": "",
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    # ── NO_TRADE scenarios (10) ──────────────────────────────────────────────
    {
        "id": "SC178-036", "name": "RISK_OFF regime → NO_TRADE (after BLOCKED check with override)",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "regime": "RISK_OFF", "regime_safety_override": True,
        "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-037", "name": "Theme WEAK → NO_TRADE",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "regime": "BULL", "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN", "theme_score": 15.0,
        "watchlist_score": 30.0, "abc_score": 20.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-038", "name": "Missing date → NO_TRADE (data incomplete)",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "date": "",
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-039", "name": "Journal required but score 20 → NO_TRADE",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "journal_required": True, "journal_quality_score": 20.0,
        "regime": "BULL", "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-040", "name": "Mistake repeat blocked → NO_TRADE",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "mistake_repeat_detected": True,
        "regime": "BULL", "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-041", "name": "Low overall score with weak theme → NO_TRADE",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "theme_score": 20.0, "watchlist_score": 30.0, "abc_score": 20.0,
        "regime_score": 50.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-042", "name": "Bear regime + weak signals → NO_TRADE",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "regime": "BEAR", "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "HIGH", "behavior": "WARNING",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-043", "name": "Bull + Unknown theme + Watch + NOT_READY → NO_TRADE",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "regime": "BULL", "theme": "UNKNOWN", "watchlist": "UNKNOWN", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-044", "name": "Behavior WARNING + low score → NO_TRADE",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "WARNING",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-045", "name": "Risk HIGH + weak theme → NO_TRADE",
        "expected_action": "NO_TRADE", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "HIGH", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    # ── WAIT scenarios (5) ───────────────────────────────────────────────────
    {
        "id": "SC178-046", "name": "Bull + Watch theme + Watch watchlist + NOT_READY",
        "expected_action": "WAIT", "has_stop_loss": True,
        "regime": "BULL", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-047", "name": "Bull_soft + Watch + Watch + NOT_READY",
        "expected_action": "WAIT", "has_stop_loss": True,
        "regime": "BULL_SOFT", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-048", "name": "Neutral + Strong + Focus + NOT_READY",
        "expected_action": "WAIT", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "STRONG", "watchlist": "FOCUS", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-049", "name": "Bull + Watch + Focus + NOT_READY + moderate risk",
        "expected_action": "WAIT", "has_stop_loss": True,
        "regime": "BULL", "theme": "WATCH", "watchlist": "FOCUS", "abc": "NOT_READY",
        "risk_level": "MODERATE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-050", "name": "Neutral + Leader + Watch + NOT_READY",
        "expected_action": "WAIT", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "LEADER", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CAUTION",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    # ── OBSERVE scenarios (5) ────────────────────────────────────────────────
    {
        "id": "SC178-051", "name": "Neutral + Weak theme + Watch + NOT_READY",
        "expected_action": "OBSERVE", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "WEAK", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-052", "name": "Unknown regime + Watch + NOT_READY",
        "expected_action": "OBSERVE", "has_stop_loss": True,
        "regime": "UNKNOWN", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-053", "name": "Neutral + Watch + Unknown watchlist + NOT_READY",
        "expected_action": "OBSERVE", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "WATCH", "watchlist": "UNKNOWN", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-054", "name": "RISK_OFF + override + weak theme → OBSERVE",
        "expected_action": "OBSERVE", "has_stop_loss": True,
        "regime": "RISK_OFF", "regime_safety_override": True,
        "theme": "WEAK", "watchlist": "UNKNOWN", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-055", "name": "All unknown → OBSERVE",
        "expected_action": "OBSERVE", "has_stop_loss": True,
        "regime": "UNKNOWN", "theme": "UNKNOWN", "watchlist": "UNKNOWN", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    # ── REDUCE_RISK scenarios (5) ────────────────────────────────────────────
    {
        "id": "SC178-056", "name": "Risk HIGH + good theme → REDUCE_RISK",
        "expected_action": "REDUCE_RISK", "has_stop_loss": True,
        "regime": "BULL", "theme": "STRONG", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "HIGH", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-057", "name": "Risk HIGH + leader theme + strong score → REDUCE_RISK",
        "expected_action": "REDUCE_RISK", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "B_READY",
        "risk_level": "HIGH", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-058", "name": "Risk HIGH + neutral regime → REDUCE_RISK",
        "expected_action": "REDUCE_RISK", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "WATCH", "watchlist": "WATCH", "abc": "B_READY",
        "risk_level": "HIGH", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-059", "name": "Risk HIGH + bull soft → REDUCE_RISK",
        "expected_action": "REDUCE_RISK", "has_stop_loss": True,
        "regime": "BULL_SOFT", "theme": "STRONG", "watchlist": "WATCH", "abc": "C_READY",
        "risk_level": "HIGH", "behavior": "CAUTION",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-060", "name": "Risk HIGH + journal OK → REDUCE_RISK",
        "expected_action": "REDUCE_RISK", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "HIGH", "behavior": "CLEAN", "journal_quality_score": 80.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    # ── REVIEW_REQUIRED scenarios (5) ────────────────────────────────────────
    {
        "id": "SC178-061", "name": "Behavior CAUTION + low score → REVIEW_REQUIRED",
        "expected_action": "REVIEW_REQUIRED", "has_stop_loss": True,
        "regime": "BULL", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CAUTION", "behavior_score": 45.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-062", "name": "Journal required + score 35 → REVIEW_REQUIRED",
        "expected_action": "REVIEW_REQUIRED", "has_stop_loss": True,
        "journal_required": True, "journal_quality_score": 35.0,
        "regime": "BULL", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-063", "name": "Caution behavior + neutral regime → REVIEW_REQUIRED",
        "expected_action": "REVIEW_REQUIRED", "has_stop_loss": True,
        "regime": "NEUTRAL", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CAUTION", "behavior_score": 40.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-064", "name": "Journal needed, low score, caution → REVIEW_REQUIRED",
        "expected_action": "REVIEW_REQUIRED", "has_stop_loss": True,
        "journal_required": True, "journal_quality_score": 30.0,
        "regime": "NEUTRAL", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CAUTION",
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-065", "name": "Caution + bull_soft + watch theme → REVIEW_REQUIRED",
        "expected_action": "REVIEW_REQUIRED", "has_stop_loss": True,
        "regime": "BULL_SOFT", "theme": "WATCH", "watchlist": "WATCH", "abc": "NOT_READY",
        "risk_level": "SAFE", "behavior": "CAUTION", "behavior_score": 50.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    # ── PAPER_ADD_ALLOWED scenarios (5) ──────────────────────────────────────
    {
        "id": "SC178-066", "name": "Bull + Leader + Focus + B_READY + add signal",
        "expected_action": "PAPER_ADD_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "B_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "theme_score": 92.0, "watchlist_score": 92.0, "abc_score": 88.0,
        "regime_score": 90.0, "risk_score": 90.0, "behavior_score": 90.0,
        "journal_quality_score": 85.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-067", "name": "Bull + Leader + Focus + C_READY + add signal",
        "expected_action": "PAPER_ADD_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "C_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "theme_score": 90.0, "watchlist_score": 90.0, "abc_score": 85.0,
        "regime_score": 90.0, "risk_score": 90.0, "behavior_score": 90.0,
        "journal_quality_score": 80.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-068", "name": "Bull + Strong + Focus + A_READY + full score add",
        "expected_action": "PAPER_ADD_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "STRONG", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "theme_score": 85.0, "watchlist_score": 90.0, "abc_score": 92.0,
        "regime_score": 88.0, "risk_score": 92.0, "behavior_score": 92.0,
        "journal_quality_score": 90.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-069", "name": "Bull + Leader + Focus + A_READY + journal 90",
        "expected_action": "PAPER_ADD_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "theme_score": 94.0, "watchlist_score": 94.0, "abc_score": 92.0,
        "regime_score": 90.0, "risk_score": 94.0, "behavior_score": 92.0,
        "journal_quality_score": 90.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
    {
        "id": "SC178-070", "name": "Bull + Leader + Focus + A_READY + perfect scenario",
        "expected_action": "PAPER_ADD_ALLOWED", "has_stop_loss": True,
        "regime": "BULL", "theme": "LEADER", "watchlist": "FOCUS", "abc": "A_READY",
        "risk_level": "SAFE", "behavior": "CLEAN",
        "theme_score": 98.0, "watchlist_score": 98.0, "abc_score": 96.0,
        "regime_score": 95.0, "risk_score": 98.0, "behavior_score": 96.0,
        "journal_quality_score": 95.0,
        "paper_only": True, "research_only": True, "no_real_orders": True,
        "no_broker": True, "not_investment_advice": True, "demo_only": True,
        "not_for_production": True,
    },
]


def get_scenarios() -> List[Dict[str, Any]]:
    """Return all integrated strategy scenarios."""
    return list(_SCENARIOS)


def count_scenarios() -> int:
    """Return number of scenarios."""
    return len(_SCENARIOS)


def get_scenario_by_id(scenario_id: str) -> Dict[str, Any]:
    """Return a single scenario by ID, or None."""
    for s in _SCENARIOS:
        if s["id"] == scenario_id:
            return s
    return None


def get_scenarios_by_action(action: str) -> List[Dict[str, Any]]:
    """Return scenarios with the given expected_action."""
    return [s for s in _SCENARIOS if s.get("expected_action") == action]
