"""
paper_trading/small_capital_strategy/paper_cockpit_fixtures_v203.py
v2.0.3 Paper Strategy Simulation Batch & Scenario Replay — Fixtures
[!] Paper Only. Research Only. Simulate Only. No Real Orders. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List

_F = {
    "schema_version": "203", "paper_only": True, "no_real_orders": True,
    "simulate_only": True, "research_only": True,
}

FIXTURES: List[Dict[str, Any]] = [
    {**_F, "id": "PC203-F001", "fixture_id": "PC203-F001", "name": "default_simulation_input",
     "description": "Default SimulationInput fixture", "model": "SimulationInput",
     "data": {"simulation_version": "2.0.3", "market_condition": "bull_trend", "entry_style": "balanced"}},
    {**_F, "id": "PC203-F002", "fixture_id": "PC203-F002", "name": "bull_trend_scenario_replay",
     "description": "Bull trend ScenarioReplaySchema", "model": "ScenarioReplaySchema",
     "data": {"market_condition": "bull_trend", "trend_condition": "uptrend"}},
    {**_F, "id": "PC203-F003", "fixture_id": "PC203-F003", "name": "pullback_scenario_replay",
     "description": "Pullback ScenarioReplaySchema", "model": "ScenarioReplaySchema",
     "data": {"market_condition": "pullback", "trend_condition": "pullback_from_high"}},
    {**_F, "id": "PC203-F004", "fixture_id": "PC203-F004", "name": "breakdown_scenario_replay",
     "description": "Breakdown ScenarioReplaySchema", "model": "ScenarioReplaySchema",
     "data": {"market_condition": "breakdown", "expected_final_actions": ["NO_ENTRY"]}},
    {**_F, "id": "PC203-F005", "fixture_id": "PC203-F005", "name": "panic_selloff_scenario",
     "description": "Panic selloff ScenarioReplaySchema", "model": "ScenarioReplaySchema",
     "data": {"market_condition": "panic_selloff", "expected_final_actions": ["NO_ENTRY"]}},
    {**_F, "id": "PC203-F006", "fixture_id": "PC203-F006", "name": "rebound_scenario",
     "description": "Rebound ScenarioReplaySchema", "model": "ScenarioReplaySchema",
     "data": {"market_condition": "rebound", "trend_condition": "recovering"}},
    {**_F, "id": "PC203-F007", "fixture_id": "PC203-F007", "name": "high_volatility_scenario",
     "description": "High volatility ScenarioReplaySchema", "model": "ScenarioReplaySchema",
     "data": {"market_condition": "high_volatility", "volatility_condition": "high"}},
    {**_F, "id": "PC203-F008", "fixture_id": "PC203-F008", "name": "low_liquidity_scenario",
     "description": "Low liquidity ScenarioReplaySchema", "model": "ScenarioReplaySchema",
     "data": {"market_condition": "low_liquidity", "liquidity_condition": "thin"}},
    {**_F, "id": "PC203-F009", "fixture_id": "PC203-F009", "name": "balanced_strategy_profile",
     "description": "Balanced StrategyProfile", "model": "StrategyProfile",
     "data": {"entry_style": "balanced", "risk_budget_pct": 20.0, "max_position_count": 5}},
    {**_F, "id": "PC203-F010", "fixture_id": "PC203-F010", "name": "conservative_strategy_profile",
     "description": "Conservative StrategyProfile", "model": "StrategyProfile",
     "data": {"entry_style": "conservative", "risk_budget_pct": 10.0, "max_position_count": 3}},
    {**_F, "id": "PC203-F011", "fixture_id": "PC203-F011", "name": "aggressive_strategy_profile",
     "description": "Aggressive StrategyProfile", "model": "StrategyProfile",
     "data": {"entry_style": "aggressive", "risk_budget_pct": 30.0, "max_position_count": 8}},
    {**_F, "id": "PC203-F012", "fixture_id": "PC203-F012", "name": "risk_first_strategy_profile",
     "description": "Risk-first StrategyProfile", "model": "StrategyProfile",
     "data": {"entry_style": "risk_first", "risk_budget_pct": 8.0, "max_position_count": 2}},
    {**_F, "id": "PC203-F013", "fixture_id": "PC203-F013", "name": "abc_pullback_profile",
     "description": "ABC pullback StrategyProfile", "model": "StrategyProfile",
     "data": {"entry_style": "abc_pullback", "risk_budget_pct": 15.0}},
    {**_F, "id": "PC203-F014", "fixture_id": "PC203-F014", "name": "breakout_only_profile",
     "description": "Breakout-only StrategyProfile", "model": "StrategyProfile",
     "data": {"entry_style": "breakout_only", "risk_budget_pct": 20.0}},
    {**_F, "id": "PC203-F015", "fixture_id": "PC203-F015", "name": "second_wave_profile",
     "description": "Second wave StrategyProfile", "model": "StrategyProfile",
     "data": {"entry_style": "second_wave", "risk_budget_pct": 18.0}},
    {**_F, "id": "PC203-F016", "fixture_id": "PC203-F016", "name": "simulation_result_paper_only",
     "description": "SimulationResult with paper_only=True", "model": "SimulationResult",
     "data": {"paper_only": True, "no_real_orders": True, "simulation_version": "2.0.3"}},
    {**_F, "id": "PC203-F017", "fixture_id": "PC203-F017", "name": "batch_result_paper_only",
     "description": "BatchSimulationResult with paper_only=True", "model": "BatchSimulationResult",
     "data": {"paper_only": True, "no_real_orders": True}},
    {**_F, "id": "PC203-F018", "fixture_id": "PC203-F018", "name": "batch_comparison_all_fields",
     "description": "BatchComparison with all 15 fields", "model": "BatchComparison",
     "data": {"total_candidates": 5, "allowed_count": 3, "blocked_count": 2}},
    {**_F, "id": "PC203-F019", "fixture_id": "PC203-F019", "name": "simulation_ranking_grade_a",
     "description": "SimulationRanking with grade A", "model": "SimulationRanking",
     "data": {"rank": 1, "quality_score": 85.0, "final_grade": "A"}},
    {**_F, "id": "PC203-F020", "fixture_id": "PC203-F020", "name": "simulation_ranking_grade_b",
     "description": "SimulationRanking with grade B", "model": "SimulationRanking",
     "data": {"rank": 2, "quality_score": 70.0, "final_grade": "B"}},
    {**_F, "id": "PC203-F021", "fixture_id": "PC203-F021", "name": "simulation_ranking_grade_c",
     "description": "SimulationRanking with grade C", "model": "SimulationRanking",
     "data": {"rank": 3, "quality_score": 55.0, "final_grade": "C"}},
    {**_F, "id": "PC203-F022", "fixture_id": "PC203-F022", "name": "json_export_valid",
     "description": "SimulationExportResult JSON", "model": "SimulationExportResult",
     "data": {"export_format": "json", "is_valid": True, "export_status": "complete"}},
    {**_F, "id": "PC203-F023", "fixture_id": "PC203-F023", "name": "markdown_export_valid",
     "description": "SimulationExportResult Markdown", "model": "SimulationExportResult",
     "data": {"export_format": "markdown", "is_valid": True, "export_status": "complete"}},
    {**_F, "id": "PC203-F024", "fixture_id": "PC203-F024", "name": "csv_export_valid",
     "description": "SimulationExportResult CSV", "model": "SimulationExportResult",
     "data": {"export_format": "csv", "is_valid": True, "export_status": "complete"}},
    {**_F, "id": "PC203-F025", "fixture_id": "PC203-F025", "name": "audit_snapshot_with_hash",
     "description": "SimulationAuditSnapshot with reproducibility_hash", "model": "SimulationAuditSnapshot",
     "data": {"reproducibility_hash": "abc123", "export_format": "audit_snapshot"}},
    {**_F, "id": "PC203-F026", "fixture_id": "PC203-F026", "name": "candidate_result_no_entry",
     "description": "SimulationCandidateResult with NO_ENTRY", "model": "SimulationCandidateResult",
     "data": {"final_action": "NO_ENTRY", "abc_type": "NO_ENTRY"}},
    {**_F, "id": "PC203-F027", "fixture_id": "PC203-F027", "name": "candidate_result_buy_plan",
     "description": "SimulationCandidateResult with PAPER_BUY_PLAN", "model": "SimulationCandidateResult",
     "data": {"final_action": "PAPER_BUY_PLAN", "abc_type": "A_PULLBACK_10MA", "signal_score": 85.0}},
    {**_F, "id": "PC203-F028", "fixture_id": "PC203-F028", "name": "candidate_result_add_plan",
     "description": "SimulationCandidateResult with PAPER_ADD_PLAN", "model": "SimulationCandidateResult",
     "data": {"final_action": "PAPER_ADD_PLAN", "signal_score": 72.0}},
    {**_F, "id": "PC203-F029", "fixture_id": "PC203-F029", "name": "candidate_result_watch",
     "description": "SimulationCandidateResult with WATCH", "model": "SimulationCandidateResult",
     "data": {"final_action": "WATCH", "signal_score": 62.0}},
    {**_F, "id": "PC203-F030", "fixture_id": "PC203-F030", "name": "candidate_result_wait",
     "description": "SimulationCandidateResult with WAIT", "model": "SimulationCandidateResult",
     "data": {"final_action": "WAIT", "signal_score": 52.0}},
    {**_F, "id": "PC203-F031", "fixture_id": "PC203-F031", "name": "v203_health_summary",
     "description": "V203HealthSummary fixture", "model": "V203HealthSummary",
     "data": {"all_passed": True, "version": "2.0.3"}},
    {**_F, "id": "PC203-F032", "fixture_id": "PC203-F032", "name": "v203_release_summary",
     "description": "V203ReleaseSummary fixture", "model": "V203ReleaseSummary",
     "data": {"version": "2.0.3", "models_count": 12, "cli_count": 10, "gui_tabs_count": 3}},
    {**_F, "id": "PC203-F033", "fixture_id": "PC203-F033", "name": "simulate_one_watchlist",
     "description": "simulate_one with watchlist input", "model": "SimulationInput",
     "data": {"watchlist": ["2330", "2317"], "market_condition": "bull_trend"}},
    {**_F, "id": "PC203-F034", "fixture_id": "PC203-F034", "name": "simulate_one_candidates",
     "description": "simulate_one with candidates input", "model": "SimulationInput",
     "data": {"candidates": ["2454", "2382"], "market_condition": "pullback"}},
    {**_F, "id": "PC203-F035", "fixture_id": "PC203-F035", "name": "zero_risk_budget_input",
     "description": "SimulationInput with risk_budget_pct=0", "model": "SimulationInput",
     "data": {"risk_budget_pct": 0.0, "expected_result": "NO_ENTRY"}},
    {**_F, "id": "PC203-F036", "fixture_id": "PC203-F036", "name": "batch_simulation_two_profiles",
     "description": "Batch simulation with two profiles", "model": "BatchSimulationResult",
     "data": {"simulations_count": 2, "comparisons_count": 2}},
    {**_F, "id": "PC203-F037", "fixture_id": "PC203-F037", "name": "batch_simulation_three_scenarios",
     "description": "Batch simulation with three scenarios", "model": "BatchSimulationResult",
     "data": {"simulations_count": 3}},
    {**_F, "id": "PC203-F038", "fixture_id": "PC203-F038", "name": "ranking_sorted_by_quality",
     "description": "Rankings sorted descending by quality_score", "model": "SimulationRanking",
     "data": {"rank": 1, "expected": "highest_quality_first"}},
    {**_F, "id": "PC203-F039", "fixture_id": "PC203-F039", "name": "strategy_profile_conservative",
     "description": "Conservative profile stop loss policy", "model": "StrategyProfile",
     "data": {"entry_style": "conservative", "stop_loss_policy": "fixed_8pct"}},
    {**_F, "id": "PC203-F040", "fixture_id": "PC203-F040", "name": "strategy_profile_human_review",
     "description": "Profile human_review_policy always required", "model": "StrategyProfile",
     "data": {"human_review_policy": "always_required"}},
    {**_F, "id": "PC203-F041", "fixture_id": "PC203-F041", "name": "scenario_replay_expected_blocks",
     "description": "Scenario with expected_block_reasons", "model": "ScenarioReplaySchema",
     "data": {"expected_block_reasons": ["trend_broken", "below_20ma"]}},
    {**_F, "id": "PC203-F042", "fixture_id": "PC203-F042", "name": "scenario_replay_expected_actions",
     "description": "Scenario with expected_final_actions", "model": "ScenarioReplaySchema",
     "data": {"expected_final_actions": ["PAPER_BUY_PLAN", "WATCH"]}},
    {**_F, "id": "PC203-F043", "fixture_id": "PC203-F043", "name": "scenario_with_notes",
     "description": "Scenario with replay_notes", "model": "ScenarioReplaySchema",
     "data": {"replay_notes": "paper-only simulation note"}},
    {**_F, "id": "PC203-F044", "fixture_id": "PC203-F044", "name": "chip_condition_normal",
     "description": "Scenario with chip_condition=neutral", "model": "ScenarioReplaySchema",
     "data": {"chip_condition": "neutral"}},
    {**_F, "id": "PC203-F045", "fixture_id": "PC203-F045", "name": "margin_condition_normal",
     "description": "Scenario with margin_condition=normal", "model": "ScenarioReplaySchema",
     "data": {"margin_condition": "normal"}},
    {**_F, "id": "PC203-F046", "fixture_id": "PC203-F046", "name": "simulation_export_formats",
     "description": "SIMULATION_EXPORT_FORMATS has 4 entries", "model": "constants",
     "data": {"count": 4}},
    {**_F, "id": "PC203-F047", "fixture_id": "PC203-F047", "name": "safety_flags_20",
     "description": "SAFETY_FLAGS_V203 has 20 entries", "model": "constants",
     "data": {"count": 20}},
    {**_F, "id": "PC203-F048", "fixture_id": "PC203-F048", "name": "market_conditions_list",
     "description": "MARKET_CONDITIONS has 8 items", "model": "constants",
     "data": {"count": 8, "items": ["bull_trend", "pullback", "range_bound", "breakdown"]}},
    {**_F, "id": "PC203-F049", "fixture_id": "PC203-F049", "name": "entry_styles_list",
     "description": "ENTRY_STYLES has 7 items", "model": "constants",
     "data": {"count": 7, "items": ["conservative", "balanced", "aggressive"]}},
    {**_F, "id": "PC203-F050", "fixture_id": "PC203-F050", "name": "simulation_candidate_schema",
     "description": "SimulationCandidateResult schema", "model": "SimulationCandidateResult",
     "data": {"schema_version": "203", "paper_only": True, "human_review_required": True}},
    {**_F, "id": "PC203-F051", "fixture_id": "PC203-F051", "name": "batch_comparison_top_candidates",
     "description": "BatchComparison top_candidates list", "model": "BatchComparison",
     "data": {"top_candidates": ["2330", "2317", "2454"]}},
    {**_F, "id": "PC203-F052", "fixture_id": "PC203-F052", "name": "batch_comparison_blocked_reasons",
     "description": "BatchComparison worst_blocked_reasons list", "model": "BatchComparison",
     "data": {"worst_blocked_reasons": ["below_20ma", "trend_broken"]}},
    {**_F, "id": "PC203-F053", "fixture_id": "PC203-F053", "name": "simulation_result_final_action_summary",
     "description": "SimulationResult final_action_summary dict", "model": "SimulationResult",
     "data": {"final_action_summary": {"PAPER_BUY_PLAN": 2, "NO_ENTRY": 3}}},
    {**_F, "id": "PC203-F054", "fixture_id": "PC203-F054", "name": "simulation_rule_snapshot",
     "description": "SimulationResult rule_snapshot", "model": "SimulationResult",
     "data": {"rule_snapshot": "paper_abc_rules_v203"}},
    {**_F, "id": "PC203-F055", "fixture_id": "PC203-F055", "name": "simulation_risk_policy_snapshot",
     "description": "SimulationResult risk_policy_snapshot", "model": "SimulationResult",
     "data": {"risk_policy_snapshot": "paper_risk_policy_v203"}},
    {**_F, "id": "PC203-F056", "fixture_id": "PC203-F056", "name": "audit_run_metadata",
     "description": "SimulationAuditSnapshot run_metadata", "model": "SimulationAuditSnapshot",
     "data": {"run_metadata": "v2.0.3|scenario=test"}},
    {**_F, "id": "PC203-F057", "fixture_id": "PC203-F057", "name": "audit_safety_snapshot",
     "description": "SimulationAuditSnapshot safety_snapshot", "model": "SimulationAuditSnapshot",
     "data": {"safety_snapshot": "NO_REAL_ORDERS=True|BROKER_EXECUTION_ENABLED=False"}},
    {**_F, "id": "PC203-F058", "fixture_id": "PC203-F058", "name": "gui_render_simulation_batch",
     "description": "render_simulation_batch_v203_tab result", "model": "GUI",
     "data": {"tab": "simulation_batch_v203", "paper_only": True}},
    {**_F, "id": "PC203-F059", "fixture_id": "PC203-F059", "name": "gui_render_scenario_replay",
     "description": "render_scenario_replay_v203_tab result", "model": "GUI",
     "data": {"tab": "scenario_replay_v203", "paper_only": True}},
    {**_F, "id": "PC203-F060", "fixture_id": "PC203-F060", "name": "gui_render_strategy_comparison",
     "description": "render_strategy_comparison_v203_tab result", "model": "GUI",
     "data": {"tab": "strategy_comparison_v203", "paper_only": True}},
    {**_F, "id": "PC203-F061", "fixture_id": "PC203-F061", "name": "cli_command_simulate_one",
     "description": "paper-cockpit-v203-simulate-one CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-simulate-one"}},
    {**_F, "id": "PC203-F062", "fixture_id": "PC203-F062", "name": "cli_command_simulate_batch",
     "description": "paper-cockpit-v203-simulate-batch CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-simulate-batch"}},
    {**_F, "id": "PC203-F063", "fixture_id": "PC203-F063", "name": "cli_command_replay",
     "description": "paper-cockpit-v203-replay-scenario CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-replay-scenario"}},
    {**_F, "id": "PC203-F064", "fixture_id": "PC203-F064", "name": "cli_command_compare",
     "description": "paper-cockpit-v203-compare-profiles CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-compare-profiles"}},
    {**_F, "id": "PC203-F065", "fixture_id": "PC203-F065", "name": "cli_command_rank",
     "description": "paper-cockpit-v203-rank-results CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-rank-results"}},
    {**_F, "id": "PC203-F066", "fixture_id": "PC203-F066", "name": "cli_command_export_json",
     "description": "paper-cockpit-v203-export-json CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-export-json"}},
    {**_F, "id": "PC203-F067", "fixture_id": "PC203-F067", "name": "cli_command_export_md",
     "description": "paper-cockpit-v203-export-md CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-export-md"}},
    {**_F, "id": "PC203-F068", "fixture_id": "PC203-F068", "name": "cli_command_export_csv",
     "description": "paper-cockpit-v203-export-csv CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-export-csv"}},
    {**_F, "id": "PC203-F069", "fixture_id": "PC203-F069", "name": "cli_command_health",
     "description": "paper-cockpit-v203-health CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-health"}},
    {**_F, "id": "PC203-F070", "fixture_id": "PC203-F070", "name": "cli_command_gate",
     "description": "paper-cockpit-v203-gate CLI command", "model": "CLI",
     "data": {"command": "paper-cockpit-v203-gate"}},
    {**_F, "id": "PC203-F071", "fixture_id": "PC203-F071", "name": "backward_compat_v202_import",
     "description": "v2.0.2 paper_cockpit_v202 importable", "model": "backward_compat",
     "data": {"module": "paper_cockpit_v202", "version": "2.0.2"}},
    {**_F, "id": "PC203-F072", "fixture_id": "PC203-F072", "name": "backward_compat_v201_import",
     "description": "v2.0.1 paper_cockpit_v201 importable", "model": "backward_compat",
     "data": {"module": "paper_cockpit_v201", "version": "2.0.1"}},
    {**_F, "id": "PC203-F073", "fixture_id": "PC203-F073", "name": "backward_compat_v200_import",
     "description": "v2.0.0 paper_cockpit_v200 importable", "model": "backward_compat",
     "data": {"module": "paper_cockpit_v200", "version": "2.0.0"}},
    {**_F, "id": "PC203-F074", "fixture_id": "PC203-F074", "name": "render_all_tabs_clean",
     "description": "render_all_tabs() returns no error tabs", "model": "GUI",
     "data": {"error_tabs": []}},
    {**_F, "id": "PC203-F075", "fixture_id": "PC203-F075", "name": "panel_version_v203_constant",
     "description": "PANEL_VERSION_V203 == 2.0.3", "model": "GUI",
     "data": {"PANEL_VERSION_V203": "2.0.3"}},
    {**_F, "id": "PC203-F076", "fixture_id": "PC203-F076", "name": "panel_version_unchanged",
     "description": "PANEL_VERSION remains 2.0.0", "model": "GUI",
     "data": {"PANEL_VERSION": "2.0.0"}},
    {**_F, "id": "PC203-F077", "fixture_id": "PC203-F077", "name": "get_v203_tab_names",
     "description": "get_v203_tab_names() returns 3 tabs", "model": "GUI",
     "data": {"count": 3}},
    {**_F, "id": "PC203-F078", "fixture_id": "PC203-F078", "name": "health_check_all_passed",
     "description": "v2.0.3 health check all_passed=True", "model": "health",
     "data": {"all_passed": True}},
    {**_F, "id": "PC203-F079", "fixture_id": "PC203-F079", "name": "gate_check_passed",
     "description": "v2.0.3 gate gate_passed=True", "model": "gate",
     "data": {"gate_passed": True}},
    {**_F, "id": "PC203-F080", "fixture_id": "PC203-F080", "name": "safety_paper_only_snapshot",
     "description": "paper_only_safety_snapshot=True in SimulationResult", "model": "SimulationResult",
     "data": {"paper_only_safety_snapshot": True}},
]

assert len(FIXTURES) == 80, f"Expected 80 fixtures, got {len(FIXTURES)}"
assert all(f["schema_version"] == "203" for f in FIXTURES)
assert all(f["paper_only"] is True for f in FIXTURES)
assert all("fixture_id" in f for f in FIXTURES)
assert len({f["id"] for f in FIXTURES}) == 80
