"""
paper_trading/small_capital_strategy/paper_cockpit_scenarios_v208.py
v2.0.8 Paper Portfolio Exposure & Theme Concentration Risk Control — Scenarios
[!] Paper Only. Research Only. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List

SCHEMA_VERSION = "208"

SCENARIOS: List[Dict[str, Any]] = [
    # --- 1-10: theme concentration scenarios ---
    {"scenario_id": "SC208-001", "schema_version": "208", "paper_only": True, "name": "AI主題過度集中-高警告", "description": "AI主題候選股佔比超過上限，觸發high警告，建議reduce_priority", "theme_id": "THEME-AI", "candidate_count": 5, "total_candidates": 8, "cap_limit": 0.40, "expected_warning_level": "high", "expected_action": "human_review_required", "should_auto_apply": False},
    {"scenario_id": "SC208-002", "schema_version": "208", "paper_only": True, "name": "半導體主題臨界集中", "description": "半導體佔比剛好在邊界，medium警告，monitor", "theme_id": "THEME-SEMI", "candidate_count": 4, "total_candidates": 8, "cap_limit": 0.40, "expected_warning_level": "medium", "should_auto_apply": False},
    {"scenario_id": "SC208-003", "schema_version": "208", "paper_only": True, "name": "電動車主題低集中度-安全", "description": "電動車佔比低，無需警告", "theme_id": "THEME-EV", "candidate_count": 2, "total_candidates": 10, "cap_limit": 0.40, "expected_warning_level": "none", "should_auto_apply": False},
    {"scenario_id": "SC208-004", "schema_version": "208", "paper_only": True, "name": "雲端運算嚴重集中-critical", "description": "雲端運算佔比達80%，critical警告，human_review_required", "theme_id": "THEME-CLOUD", "candidate_count": 8, "total_candidates": 10, "cap_limit": 0.40, "expected_warning_level": "critical", "expected_action": "human_review_required", "should_auto_apply": False},
    {"scenario_id": "SC208-005", "schema_version": "208", "paper_only": True, "name": "多主題均衡分散-最佳狀態", "description": "5個主題各佔20%，無任何警告", "theme_distribution": {"THEME-AI": 2, "THEME-SEMI": 2, "THEME-EV": 2, "THEME-CLOUD": 2, "THEME-ROBOT": 2}, "total_candidates": 10, "expected_max_warning": "none", "should_auto_apply": False},
    {"scenario_id": "SC208-006", "schema_version": "208", "paper_only": True, "name": "生技主題低警告觀察", "description": "生技佔比37.5%，low警告，監控", "theme_id": "THEME-BIOTECH", "candidate_count": 3, "total_candidates": 8, "cap_limit": 0.40, "expected_warning_level": "low", "expected_action": "monitor", "should_auto_apply": False},
    {"scenario_id": "SC208-007", "schema_version": "208", "paper_only": True, "name": "鋼鐵主題超限-阻擋促銷", "description": "鋼鐵佔比60%，over_limit，block_promotion", "theme_id": "THEME-STEEL", "candidate_count": 6, "total_candidates": 10, "cap_limit": 0.40, "expected_over_limit": True, "should_auto_apply": False},
    {"scenario_id": "SC208-008", "schema_version": "208", "paper_only": True, "name": "金融主題edge case", "description": "金融主題剛好在cap邊界", "theme_id": "THEME-FIN", "candidate_count": 4, "total_candidates": 10, "cap_limit": 0.40, "expected_over_limit": False, "should_auto_apply": False},
    {"scenario_id": "SC208-009", "schema_version": "208", "paper_only": True, "name": "空候選池-零集中度", "description": "候選池為空，無集中度風險", "theme_id": "THEME-ROBOT", "candidate_count": 0, "total_candidates": 10, "expected_concentration_score": 0.0, "should_auto_apply": False},
    {"scenario_id": "SC208-010", "schema_version": "208", "paper_only": True, "name": "主題輪動後重新評估", "description": "v2.0.7主題輪動後，v2.0.8評估新的exposure", "theme_from_v207": "THEME-AI", "theme_state": "overheating", "expected_action": "freeze_new_candidates", "should_auto_apply": False},
    # --- 11-20: sector concentration scenarios ---
    {"scenario_id": "SC208-011", "schema_version": "208", "paper_only": True, "name": "科技業嚴重集中", "description": "科技業佔75%，critical警告", "sector_id": "SECTOR-TECH", "candidate_count": 6, "total_candidates": 8, "cap_limit": 0.45, "expected_over_limit": True, "expected_warning_level": "critical", "should_auto_apply": False},
    {"scenario_id": "SC208-012", "schema_version": "208", "paper_only": True, "name": "金融業安全集中度", "description": "金融業20%，無警告", "sector_id": "SECTOR-FIN", "candidate_count": 2, "total_candidates": 10, "cap_limit": 0.45, "expected_warning_level": "none", "should_auto_apply": False},
    {"scenario_id": "SC208-013", "schema_version": "208", "paper_only": True, "name": "電子零組件中等集中", "description": "電子零組件30%，low警告", "sector_id": "SECTOR-ELEC", "candidate_count": 3, "total_candidates": 10, "cap_limit": 0.45, "expected_warning_level": "low", "should_auto_apply": False},
    {"scenario_id": "SC208-014", "schema_version": "208", "paper_only": True, "name": "製造業邊界集中", "description": "製造業40%，low警告", "sector_id": "SECTOR-MFGR", "candidate_count": 4, "total_candidates": 10, "cap_limit": 0.45, "expected_warning_level": "low", "should_auto_apply": False},
    {"scenario_id": "SC208-015", "schema_version": "208", "paper_only": True, "name": "化工業中等集中-需rescores", "description": "化工業50%，medium警告，需重新評分", "sector_id": "SECTOR-CHEM", "candidate_count": 5, "total_candidates": 10, "cap_limit": 0.45, "expected_over_limit": True, "should_auto_apply": False},
    # --- 16-20: style concentration scenarios ---
    {"scenario_id": "SC208-016", "schema_version": "208", "paper_only": True, "name": "成長型嚴重集中", "description": "成長型佔70%，high警告", "style_id": "STYLE-GROWTH", "candidate_count": 7, "total_candidates": 10, "cap_limit": 0.50, "expected_over_limit": True, "expected_warning_level": "high", "should_auto_apply": False},
    {"scenario_id": "SC208-017", "schema_version": "208", "paper_only": True, "name": "價值型安全集中", "description": "價值型20%，無警告", "style_id": "STYLE-VALUE", "candidate_count": 2, "total_candidates": 10, "cap_limit": 0.50, "expected_warning_level": "none", "should_auto_apply": False},
    {"scenario_id": "SC208-018", "schema_version": "208", "paper_only": True, "name": "動能型中等集中", "description": "動能型50%，medium警告", "style_id": "STYLE-MOMENTUM", "candidate_count": 5, "total_candidates": 10, "cap_limit": 0.50, "expected_warning_level": "medium", "should_auto_apply": False},
    {"scenario_id": "SC208-019", "schema_version": "208", "paper_only": True, "name": "收益型中等集中", "description": "收益型60%，high警告", "style_id": "STYLE-INCOME", "candidate_count": 6, "total_candidates": 10, "cap_limit": 0.50, "expected_over_limit": True, "should_auto_apply": False},
    {"scenario_id": "SC208-020", "schema_version": "208", "paper_only": True, "name": "成長型完全集中-最差", "description": "成長型100%，critical警告", "style_id": "STYLE-GROWTH", "candidate_count": 10, "total_candidates": 10, "cap_limit": 0.50, "expected_over_limit": True, "expected_warning_level": "critical", "should_auto_apply": False},
    # --- 21-30: volatility and liquidity scenarios ---
    {"scenario_id": "SC208-021", "schema_version": "208", "paper_only": True, "name": "高波動安全範圍", "description": "高波動佔20%，在30%上限內", "high_volatility_count": 2, "total_candidates": 10, "cap_limit": 0.30, "expected_over_limit": False, "should_auto_apply": False},
    {"scenario_id": "SC208-022", "schema_version": "208", "paper_only": True, "name": "高波動超限", "description": "高波動佔50%，超過30%上限", "high_volatility_count": 5, "total_candidates": 10, "cap_limit": 0.30, "expected_over_limit": True, "should_auto_apply": False},
    {"scenario_id": "SC208-023", "schema_version": "208", "paper_only": True, "name": "低流動性超限", "description": "低流動性佔30%，超過20%上限", "low_liquidity_count": 3, "total_candidates": 10, "cap_limit": 0.20, "expected_over_limit": True, "should_auto_apply": False},
    {"scenario_id": "SC208-024", "schema_version": "208", "paper_only": True, "name": "低流動性安全", "description": "低流動性佔10%，在20%上限內", "low_liquidity_count": 1, "total_candidates": 10, "cap_limit": 0.20, "expected_over_limit": False, "should_auto_apply": False},
    {"scenario_id": "SC208-025", "schema_version": "208", "paper_only": True, "name": "市場regime風險集中", "description": "Risk-off主題佔15%，超過10%上限", "risk_off_count": 1, "total_candidates": 10, "cap_limit": 0.10, "expected_over_limit": True, "should_auto_apply": False},
    {"scenario_id": "SC208-026", "schema_version": "208", "paper_only": True, "name": "市場regime安全", "description": "Risk-off主題佔0%，安全", "risk_off_count": 0, "total_candidates": 10, "cap_limit": 0.10, "expected_over_limit": False, "should_auto_apply": False},
    {"scenario_id": "SC208-027", "schema_version": "208", "paper_only": True, "name": "候選池主題過度集中", "description": "主題AI佔候選池60%", "dominant_count": 6, "total_candidates": 10, "cap_limit": 0.40, "expected_over_limit": True, "should_auto_apply": False},
    {"scenario_id": "SC208-028", "schema_version": "208", "paper_only": True, "name": "晉升佇列主題集中-超限", "description": "晉升佇列中AI佔40%，超過35%上限", "dominant_in_queue": 4, "total_in_queue": 10, "cap_limit": 0.35, "expected_over_limit": True, "should_auto_apply": False},
    {"scenario_id": "SC208-029", "schema_version": "208", "paper_only": True, "name": "晉升佇列安全", "description": "晉升佇列分散，無過度集中", "dominant_in_queue": 3, "total_in_queue": 10, "cap_limit": 0.35, "expected_over_limit": False, "should_auto_apply": False},
    {"scenario_id": "SC208-030", "schema_version": "208", "paper_only": True, "name": "零候選池邊界測試", "description": "候選池和晉升佇列均為空", "dominant_in_queue": 0, "total_in_queue": 1, "expected_over_limit": False, "should_auto_apply": False},
    # --- 31-40: warning level and action scenarios ---
    {"scenario_id": "SC208-031", "schema_version": "208", "paper_only": True, "name": "warning=none -> action=allow", "concentration_score": 20.0, "cap_limit": 0.40, "current_usage": 0.20, "expected_warning_level": "none", "expected_action": "allow", "should_auto_apply": False},
    {"scenario_id": "SC208-032", "schema_version": "208", "paper_only": True, "name": "warning=low -> action=monitor", "concentration_score": 48.0, "cap_limit": 0.40, "current_usage": 0.28, "expected_warning_level": "low", "expected_action": "monitor", "should_auto_apply": False},
    {"scenario_id": "SC208-033", "schema_version": "208", "paper_only": True, "name": "warning=medium (theme) -> reduce_priority", "exposure_type": "theme", "concentration_score": 62.0, "cap_limit": 0.40, "current_usage": 0.36, "expected_warning_level": "medium", "expected_action": "reduce_priority", "should_auto_apply": False},
    {"scenario_id": "SC208-034", "schema_version": "208", "paper_only": True, "name": "warning=high -> human_review", "concentration_score": 78.0, "cap_limit": 0.40, "current_usage": 0.44, "expected_warning_level": "high", "expected_action": "human_review_required", "should_auto_apply": False},
    {"scenario_id": "SC208-035", "schema_version": "208", "paper_only": True, "name": "warning=critical -> human_review", "concentration_score": 92.0, "cap_limit": 0.40, "current_usage": 0.55, "expected_warning_level": "critical", "expected_action": "human_review_required", "should_auto_apply": False},
    {"scenario_id": "SC208-036", "schema_version": "208", "paper_only": True, "name": "exposure_action recommendation only", "description": "exposure_action 只是建議，不會自動執行", "should_auto_apply": False, "auto_apply_enabled": False},
    {"scenario_id": "SC208-037", "schema_version": "208", "paper_only": True, "name": "freeze_new_candidates (非theme type)", "exposure_type": "volatility", "concentration_score": 62.0, "cap_limit": 0.30, "current_usage": 0.27, "expected_action": "freeze_new_candidates", "should_auto_apply": False},
    {"scenario_id": "SC208-038", "schema_version": "208", "paper_only": True, "name": "require_rescore scenario", "description": "某exposure item觸發require_rescore", "expected_action": "require_rescore", "should_auto_apply": False},
    {"scenario_id": "SC208-039", "schema_version": "208", "paper_only": True, "name": "block_promotion scenario", "description": "exposure超限導致block_promotion", "expected_action": "block_promotion", "should_auto_apply": False},
    {"scenario_id": "SC208-040", "schema_version": "208", "paper_only": True, "name": "所有exposure_action都是建議", "description": "7種exposure_action均只產生建議，不自動執行", "exposure_actions": ["allow","monitor","reduce_priority","freeze_new_candidates","require_rescore","block_promotion","human_review_required"], "should_auto_apply": False},
    # --- 41-50: candidate exposure adjustment scenarios ---
    {"scenario_id": "SC208-041", "schema_version": "208", "paper_only": True, "name": "台積電-主題集中懲罰", "symbol": "2330", "theme_concentration_score": 78.0, "expected_penalty_range": [8.0, 15.0], "should_auto_apply": False},
    {"scenario_id": "SC208-042", "schema_version": "208", "paper_only": True, "name": "聯發科-多重懲罰", "symbol": "2454", "theme_concentration_score": 92.0, "sector_concentration_score": 90.0, "market_state": "downtrend", "expected_total_penalty_min": 30.0, "should_auto_apply": False},
    {"scenario_id": "SC208-043", "schema_version": "208", "paper_only": True, "name": "鴻海-無懲罰安全", "symbol": "2317", "theme_concentration_score": 15.0, "sector_concentration_score": 20.0, "market_state": "range_bound", "is_high_volatility": False, "is_low_liquidity": False, "expected_total_penalty": 0.0, "should_auto_apply": False},
    {"scenario_id": "SC208-044", "schema_version": "208", "paper_only": True, "name": "台達電-高波動懲罰", "symbol": "2308", "is_high_volatility": True, "expected_volatility_penalty": 8.0, "should_auto_apply": False},
    {"scenario_id": "SC208-045", "schema_version": "208", "paper_only": True, "name": "聯電-低流動性懲罰", "symbol": "2303", "is_low_liquidity": True, "expected_liquidity_penalty": 10.0, "should_auto_apply": False},
    {"scenario_id": "SC208-046", "schema_version": "208", "paper_only": True, "name": "友達-exposure_cap阻擋", "symbol": "2409", "blocked_by_exposure_cap": True, "expected_requires_human_review": True, "should_auto_apply": False},
    {"scenario_id": "SC208-047", "schema_version": "208", "paper_only": True, "name": "廣達-risk_off人工審核", "symbol": "2382", "market_state": "risk_off", "expected_requires_human_review": True, "should_auto_apply": False},
    {"scenario_id": "SC208-048", "schema_version": "208", "paper_only": True, "name": "日月光-sector超限+主題集中", "symbol": "3711", "theme_concentration_score": 78.0, "sector_concentration_score": 92.0, "should_auto_apply": False},
    {"scenario_id": "SC208-049", "schema_version": "208", "paper_only": True, "name": "緯穎-高波動+高主題集中", "symbol": "6669", "is_high_volatility": True, "theme_concentration_score": 92.0, "should_auto_apply": False},
    {"scenario_id": "SC208-050", "schema_version": "208", "paper_only": True, "name": "should_auto_apply恆為False", "should_auto_apply": False, "auto_apply_enabled": False, "description": "CandidateExposureAdjustment.should_auto_apply恆為False，即使強制設True也不生效"},
    # --- 51-60: integration with v2.0.7 scenarios ---
    {"scenario_id": "SC208-051", "schema_version": "208", "paper_only": True, "name": "v207主題輪動整合-leading主題低懲罰", "description": "v2.0.7 leading主題整合到v2.0.8，集中度正常則低懲罰", "v207_theme_state": "leading", "expected_theme_penalty_low": True, "should_auto_apply": False},
    {"scenario_id": "SC208-052", "schema_version": "208", "paper_only": True, "name": "v207主題輪動整合-overheating主題高懲罰", "description": "v2.0.7 overheating主題集中度高，v2.0.8 產生高懲罰", "v207_theme_state": "overheating", "expected_exposure_action": "freeze_new_candidates", "should_auto_apply": False},
    {"scenario_id": "SC208-053", "schema_version": "208", "paper_only": True, "name": "v206候選lifecycle整合", "description": "v2.0.6候選池老化資訊整合到v2.0.8 exposure分析", "v206_lifecycle_version": "2.0.6", "should_auto_apply": False},
    {"scenario_id": "SC208-054", "schema_version": "208", "paper_only": True, "name": "v205watchlist輪動整合", "description": "v2.0.5watchlist輪動後的候選股進入v2.0.8 exposure分析", "v205_watchlist_version": "2.0.5", "should_auto_apply": False},
    {"scenario_id": "SC208-055", "schema_version": "208", "paper_only": True, "name": "v207 market regime整合-strong_uptrend低懲罰", "description": "v2.0.7 strong_uptrend市場state，v2.0.8 market_regime_penalty=0", "market_state": "strong_uptrend", "expected_market_regime_penalty": 0.0, "should_auto_apply": False},
    {"scenario_id": "SC208-056", "schema_version": "208", "paper_only": True, "name": "v207 market regime整合-risk_off高懲罰", "description": "v2.0.7 risk_off market state，v2.0.8 market_regime_penalty=20", "market_state": "risk_off", "expected_market_regime_penalty": 20.0, "should_auto_apply": False},
    {"scenario_id": "SC208-057", "schema_version": "208", "paper_only": True, "name": "report export v202整合", "description": "v2.0.2報告匯出整合，確保exposure report可嵌入", "v202_export_version": "2.0.2", "should_auto_apply": False},
    {"scenario_id": "SC208-058", "schema_version": "208", "paper_only": True, "name": "simulation ranking v203整合", "description": "v2.0.3 simulation ranking整合exposure風險", "v203_simulation_version": "2.0.3", "should_auto_apply": False},
    {"scenario_id": "SC208-059", "schema_version": "208", "paper_only": True, "name": "weekly improvement v204整合", "description": "v2.0.4 weekly improvement pack整合exposure snapshot", "v204_review_version": "2.0.4", "should_auto_apply": False},
    {"scenario_id": "SC208-060", "schema_version": "208", "paper_only": True, "name": "全版本backward compat", "description": "v2.0.0~v2.0.7所有版本backward compat保持", "backward_compat_versions": ["2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7"], "should_auto_apply": False},
    # --- 61-70: safety and paper-only scenarios ---
    {"scenario_id": "SC208-061", "schema_version": "208", "paper_only": True, "name": "paper_only恆為True", "paper_only": True, "should_auto_apply": False},
    {"scenario_id": "SC208-062", "schema_version": "208", "paper_only": True, "name": "no_real_orders恆為True", "no_real_orders": True, "should_auto_apply": False},
    {"scenario_id": "SC208-063", "schema_version": "208", "paper_only": True, "name": "NO_REAL_ORDERS=True全域", "should_auto_apply": False},
    {"scenario_id": "SC208-064", "schema_version": "208", "paper_only": True, "name": "BROKER_EXECUTION_ENABLED=False", "should_auto_apply": False},
    {"scenario_id": "SC208-065", "schema_version": "208", "paper_only": True, "name": "PRODUCTION_TRADING_BLOCKED=True", "should_auto_apply": False},
    {"scenario_id": "SC208-066", "schema_version": "208", "paper_only": True, "name": "no_automatic_rebalance=True", "should_auto_apply": False},
    {"scenario_id": "SC208-067", "schema_version": "208", "paper_only": True, "name": "no_real_account_sync=True", "should_auto_apply": False},
    {"scenario_id": "SC208-068", "schema_version": "208", "paper_only": True, "name": "auto_apply_enabled恆為False", "auto_apply_enabled": False, "should_auto_apply": False},
    {"scenario_id": "SC208-069", "schema_version": "208", "paper_only": True, "name": "exposure_actions_recommendation_only", "description": "所有exposure action均為建議，不自動執行", "should_auto_apply": False},
    {"scenario_id": "SC208-070", "schema_version": "208", "paper_only": True, "name": "human_review_required=True", "human_review_required": True, "should_auto_apply": False},
    # --- 71-80: export, CLI, GUI, health, gate scenarios ---
    {"scenario_id": "SC208-071", "schema_version": "208", "paper_only": True, "name": "JSON匯出schema完整性", "export_format": "json", "expected_fields": ["exposure_review_id","exposure_version","paper_only","should_auto_apply","auto_apply_enabled"], "should_auto_apply": False},
    {"scenario_id": "SC208-072", "schema_version": "208", "paper_only": True, "name": "Markdown匯出包含安全聲明", "export_format": "markdown", "expected_contains": "[!] Paper Only", "should_auto_apply": False},
    {"scenario_id": "SC208-073", "schema_version": "208", "paper_only": True, "name": "exposure item CSV header完整", "export_format": "csv", "expected_header_fields": ["exposure_id","exposure_type","warning_level","exposure_action","should_auto_apply"], "should_auto_apply": False},
    {"scenario_id": "SC208-074", "schema_version": "208", "paper_only": True, "name": "risk cap CSV header完整", "export_format": "risk_cap_csv", "expected_header_fields": ["exposure_id","current_usage","cap_limit","auto_apply_enabled"], "should_auto_apply": False},
    {"scenario_id": "SC208-075", "schema_version": "208", "paper_only": True, "name": "candidate exposure CSV header完整", "export_format": "candidate_csv", "expected_header_fields": ["symbol","original_score","theme_penalty","final_score","should_auto_apply"], "should_auto_apply": False},
    {"scenario_id": "SC208-076", "schema_version": "208", "paper_only": True, "name": "audit snapshot schema完整", "export_format": "audit_snapshot", "expected_fields": ["exposure_review_id","safety_snapshot","reproducibility_hash"], "should_auto_apply": False},
    {"scenario_id": "SC208-077", "schema_version": "208", "paper_only": True, "name": "CLI handler 10個全部可呼叫", "cli_commands": ["paper-cockpit-v208-review-exposure","paper-cockpit-v208-evaluate-concentration","paper-cockpit-v208-build-warning-queue","paper-cockpit-v208-build-risk-cap-queue","paper-cockpit-v208-adjust-candidate-exposure","paper-cockpit-v208-export-json","paper-cockpit-v208-export-md","paper-cockpit-v208-export-csv","paper-cockpit-v208-health","paper-cockpit-v208-gate"], "should_auto_apply": False},
    {"scenario_id": "SC208-078", "schema_version": "208", "paper_only": True, "name": "GUI 3個tab正常渲染", "gui_tabs": ["portfolio_exposure_v208","theme_concentration_v208","exposure_warning_queue_v208"], "should_auto_apply": False},
    {"scenario_id": "SC208-079", "schema_version": "208", "paper_only": True, "name": "health check全項通過", "health_checks_min": 50, "should_auto_apply": False},
    {"scenario_id": "SC208-080", "schema_version": "208", "paper_only": True, "name": "release gate全項通過", "gate_checks_min": 50, "should_auto_apply": False},
]

assert len(SCENARIOS) == 80, f"Expected 80 SCENARIOS, got {len(SCENARIOS)}"
assert all(s["schema_version"] == "208" for s in SCENARIOS)
assert all(s["paper_only"] is True for s in SCENARIOS)
assert all("scenario_id" in s for s in SCENARIOS)
