"""
paper_trading/small_capital_strategy/paper_cockpit_fixtures_v212.py
v2.0.12 Paper Profit Taking & ETF Rebalancing Control — Fixtures
[!] Paper Only. Research Only. Profit Taking Recommendation Only. Validation Only.
[!] No Real Orders. No Broker. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List

SCHEMA_VERSION = "212"

FIXTURES: List[Dict[str, Any]] = [
    # --- 1-10: profit taking policy fixtures ---
    {"fixture_id": "FX212-001", "schema_version": "212", "paper_only": True, "name": "標準停利政策", "policy_id": "default-policy-v212", "first_take_profit_pct": 0.20, "second_take_profit_pct": 0.40, "require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-002", "schema_version": "212", "paper_only": True, "name": "嚴格停利政策", "policy_id": "strict-profit-v212", "first_take_profit_pct": 0.15, "second_take_profit_pct": 0.30, "require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-003", "schema_version": "212", "paper_only": True, "name": "寬鬆停利政策", "policy_id": "loose-profit-v212", "first_take_profit_pct": 0.25, "second_take_profit_pct": 0.50, "require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-004", "schema_version": "212", "paper_only": True, "name": "緊縮移動停利", "policy_id": "tight-trailing-v212", "trailing_stop_from_high_pct": 0.08, "require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-005", "schema_version": "212", "paper_only": True, "name": "寬鬆移動停利", "policy_id": "loose-trailing-v212", "trailing_stop_from_high_pct": 0.18, "require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-006", "schema_version": "212", "paper_only": True, "name": "低回吐門檻政策", "policy_id": "low-giveback-v212", "max_profit_giveback_pct": 0.10, "require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-007", "schema_version": "212", "paper_only": True, "name": "require_profit_plan強制True", "policy_id": "forced-profit-plan-v212", "input_require_profit_plan": False, "expected_require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-008", "schema_version": "212", "paper_only": True, "name": "auto_apply強制False", "policy_id": "forced-no-apply-v212", "input_auto_apply_enabled": True, "expected_auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-009", "schema_version": "212", "paper_only": True, "name": "停利計畫必要進場", "policy_id": "plan-before-entry-v212", "require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"fixture_id": "FX212-010", "schema_version": "212", "paper_only": True, "name": "壓力區退出啟用", "policy_id": "pressure-exit-v212", "weak_rebound_pressure_exit_enabled": True, "auto_apply_enabled": False, "should_auto_apply": False},
    # --- 11-20: stock profit plan fixtures (first take-profit) ---
    {"fixture_id": "FX212-011", "schema_version": "212", "paper_only": True, "name": "台積電-未達第一停利", "plan_id": "PP-2330-FX-011", "symbol": "2330", "name_": "台積電", "asset_type": "stock", "entry_price": 700.0, "current_price": 790.0, "high_watermark_price": 790.0, "first_take_profit_triggered": False, "has_profit_plan": True, "expected_profit_action": "hold_with_plan", "should_auto_apply": False},
    {"fixture_id": "FX212-012", "schema_version": "212", "paper_only": True, "name": "台積電-觸發第一停利", "plan_id": "PP-2330-FX-012", "symbol": "2330", "name_": "台積電", "asset_type": "stock", "entry_price": 700.0, "current_price": 855.0, "high_watermark_price": 860.0, "first_take_profit_triggered": False, "has_profit_plan": True, "expected_profit_action": "take_first_third", "should_auto_apply": False},
    {"fixture_id": "FX212-013", "schema_version": "212", "paper_only": True, "name": "聯發科-觸發第二停利", "plan_id": "PP-2454-FX-013", "symbol": "2454", "name_": "聯發科", "asset_type": "stock", "entry_price": 800.0, "current_price": 1130.0, "high_watermark_price": 1200.0, "first_take_profit_triggered": True, "second_take_profit_triggered": False, "has_profit_plan": True, "expected_profit_action": "take_second_third", "should_auto_apply": False},
    {"fixture_id": "FX212-014", "schema_version": "212", "paper_only": True, "name": "緯穎-runner保護", "plan_id": "PP-6669-FX-014", "symbol": "6669", "name_": "緯穎", "asset_type": "stock", "entry_price": 1500.0, "current_price": 1750.0, "high_watermark_price": 1800.0, "first_take_profit_triggered": True, "second_take_profit_triggered": True, "has_profit_plan": True, "expected_profit_action": "protect_runner", "should_auto_apply": False},
    {"fixture_id": "FX212-015", "schema_version": "212", "paper_only": True, "name": "廣達-壓力區減碼", "plan_id": "PP-2382-FX-015", "symbol": "2382", "name_": "廣達", "asset_type": "stock", "entry_price": 200.0, "current_price": 245.0, "high_watermark_price": 260.0, "first_take_profit_triggered": False, "has_profit_plan": True, "has_pressure_signal": True, "expected_profit_action": "reduce_on_pressure", "should_auto_apply": False},
    {"fixture_id": "FX212-016", "schema_version": "212", "paper_only": True, "name": "鴻海-無停利計畫阻止", "plan_id": "PP-2317-FX-016", "symbol": "2317", "name_": "鴻海", "asset_type": "stock", "entry_price": 100.0, "current_price": 115.0, "has_profit_plan": False, "expected_profit_action": "block_new_add", "expected_blocked": True, "should_auto_apply": False},
    {"fixture_id": "FX212-017", "schema_version": "212", "paper_only": True, "name": "聯電-虧損倉位持有", "plan_id": "PP-2303-FX-017", "symbol": "2303", "name_": "聯電", "asset_type": "stock", "entry_price": 50.0, "current_price": 43.0, "high_watermark_price": 55.0, "first_take_profit_triggered": False, "has_profit_plan": True, "expected_profit_action": "hold_with_plan", "should_auto_apply": False},
    {"fixture_id": "FX212-018", "schema_version": "212", "paper_only": True, "name": "日月光-到達第一停利", "plan_id": "PP-3711-FX-018", "symbol": "3711", "name_": "日月光", "asset_type": "stock", "entry_price": 130.0, "current_price": 157.0, "high_watermark_price": 160.0, "first_take_profit_triggered": False, "has_profit_plan": True, "expected_profit_action": "take_first_third", "should_auto_apply": False},
    {"fixture_id": "FX212-019", "schema_version": "212", "paper_only": True, "name": "飆股爆量上影線減碼", "plan_id": "PP-BLOWOFF-FX-019", "symbol": "TEST01", "name_": "測試飆股", "asset_type": "stock", "entry_price": 100.0, "current_price": 185.0, "high_watermark_price": 195.0, "first_take_profit_triggered": True, "second_take_profit_triggered": True, "has_profit_plan": True, "has_blowoff_signal": True, "expected_profit_action": "reduce_on_pressure", "should_auto_apply": False},
    {"fixture_id": "FX212-020", "schema_version": "212", "paper_only": True, "name": "runner跌破移動停利", "plan_id": "PP-TRAIL-FX-020", "symbol": "TEST02", "name_": "測試移動停利", "asset_type": "stock", "entry_price": 100.0, "current_price": 148.0, "high_watermark_price": 180.0, "first_take_profit_triggered": True, "second_take_profit_triggered": True, "has_profit_plan": True, "expected_profit_action": "tighten_trailing_stop", "should_auto_apply": False},
    # --- 21-30: stock profit plan (giveback) fixtures ---
    {"fixture_id": "FX212-021", "schema_version": "212", "paper_only": True, "name": "回吐5%進入審核佇列", "plan_id": "PP-GB-FX-021", "symbol": "TEST03", "name_": "測試回吐5%", "asset_type": "stock", "entry_price": 100.0, "current_price": 142.5, "high_watermark_price": 150.0, "first_take_profit_triggered": False, "has_profit_plan": True, "expected_in_giveback_queue": True, "should_auto_apply": False},
    {"fixture_id": "FX212-022", "schema_version": "212", "paper_only": True, "name": "回吐20%觸發人工審核", "plan_id": "PP-GB-FX-022", "symbol": "TEST04", "name_": "測試回吐20%", "asset_type": "stock", "entry_price": 100.0, "current_price": 120.0, "high_watermark_price": 150.0, "first_take_profit_triggered": False, "has_profit_plan": True, "expected_profit_action": "human_review_required", "should_auto_apply": False},
    {"fixture_id": "FX212-023", "schema_version": "212", "paper_only": True, "name": "高點大幅回落最高點警告", "plan_id": "PP-GB-FX-023", "symbol": "TEST05", "name_": "測試高點大幅回落", "asset_type": "stock", "entry_price": 100.0, "current_price": 125.0, "high_watermark_price": 170.0, "first_take_profit_triggered": True, "has_profit_plan": True, "expected_profit_action": "human_review_required", "should_auto_apply": False},
    {"fixture_id": "FX212-024", "schema_version": "212", "paper_only": True, "name": "高點接近無回吐", "plan_id": "PP-GB-FX-024", "symbol": "TEST06", "name_": "測試無回吐", "asset_type": "stock", "entry_price": 100.0, "current_price": 148.0, "high_watermark_price": 150.0, "first_take_profit_triggered": False, "has_profit_plan": True, "expected_in_giveback_queue": True, "should_auto_apply": False},
    {"fixture_id": "FX212-025", "schema_version": "212", "paper_only": True, "name": "回吐計算精確值", "plan_id": "PP-GB-FX-025", "symbol": "TEST07", "name_": "測試回吐計算", "current_price": 85.0, "high_watermark_price": 100.0, "expected_giveback_from_high_pct": 0.15, "should_auto_apply": False},
    {"fixture_id": "FX212-026", "schema_version": "212", "paper_only": True, "name": "未達到獲利高點前無回吐", "plan_id": "PP-GB-FX-026", "symbol": "TEST08", "name_": "測試未達高點", "entry_price": 100.0, "current_price": 110.0, "high_watermark_price": 110.0, "expected_giveback_from_high_pct": 0.0, "should_auto_apply": False},
    {"fixture_id": "FX212-027", "schema_version": "212", "paper_only": True, "name": "回吐風險評估可調用", "plan_id": "PP-RISK-FX-027", "symbol": "TEST09", "name_": "測試風險評估", "expected_callable": True, "should_auto_apply": False},
    {"fixture_id": "FX212-028", "schema_version": "212", "paper_only": True, "name": "回吐風險回傳dict", "plan_id": "PP-RISK-FX-028", "expected_return_type": "dict", "should_auto_apply": False},
    {"fixture_id": "FX212-029", "schema_version": "212", "paper_only": True, "name": "警示佇列含人工審核", "plan_id": "PP-WARN-FX-029", "expected_human_review_in_warning": True, "should_auto_apply": False},
    {"fixture_id": "FX212-030", "schema_version": "212", "paper_only": True, "name": "回吐佇列最低門檻5%", "plan_id": "PP-GB-FX-030", "min_giveback_for_queue": 0.05, "should_auto_apply": False},
    # --- 31-40: ETF rebalancing fixtures ---
    {"fixture_id": "FX212-031", "schema_version": "212", "paper_only": True, "name": "元大台灣50-帶內持有", "etf_symbol": "0050", "etf_name": "元大台灣50", "target_allocation_pct": 0.40, "current_allocation_pct": 0.43, "upper_rebalance_band_pct": 0.50, "lower_rebalance_band_pct": 0.35, "is_leveraged_etf": False, "expected_rebalance_action": "within_band_hold", "should_auto_apply": False},
    {"fixture_id": "FX212-032", "schema_version": "212", "paper_only": True, "name": "元大台灣50-超重修剪", "etf_symbol": "0050", "etf_name": "元大台灣50", "target_allocation_pct": 0.40, "current_allocation_pct": 0.55, "upper_rebalance_band_pct": 0.50, "lower_rebalance_band_pct": 0.35, "is_leveraged_etf": False, "expected_rebalance_action": "trim_to_target_band", "should_auto_apply": False},
    {"fixture_id": "FX212-033", "schema_version": "212", "paper_only": True, "name": "元大高股息-低於下限補回", "etf_symbol": "0056", "etf_name": "元大高股息", "target_allocation_pct": 0.20, "current_allocation_pct": 0.13, "upper_rebalance_band_pct": 0.25, "lower_rebalance_band_pct": 0.15, "is_leveraged_etf": False, "expected_rebalance_action": "add_back_to_target_band", "should_auto_apply": False},
    {"fixture_id": "FX212-034", "schema_version": "212", "paper_only": True, "name": "元大正2-槓桿ETF超重減碼", "etf_symbol": "00631L", "etf_name": "元大台灣50正2", "target_allocation_pct": 0.05, "current_allocation_pct": 0.12, "upper_rebalance_band_pct": 0.08, "lower_rebalance_band_pct": 0.02, "is_leveraged_etf": True, "expected_rebalance_action": "reduce_leveraged_exposure", "should_auto_apply": False},
    {"fixture_id": "FX212-035", "schema_version": "212", "paper_only": True, "name": "槓桿ETF警示非空", "etf_symbol": "00631L", "etf_name": "元大台灣50正2", "is_leveraged_etf": True, "expected_has_warning": True, "should_auto_apply": False},
    {"fixture_id": "FX212-036", "schema_version": "212", "paper_only": True, "name": "ETF帶寬自動計算", "etf_symbol": "TEST_ETF", "etf_name": "測試ETF", "target_allocation_pct": 0.40, "current_allocation_pct": 0.40, "upper_rebalance_band_pct": 0.0, "lower_rebalance_band_pct": 0.0, "expected_auto_band": True, "should_auto_apply": False},
    {"fixture_id": "FX212-037", "schema_version": "212", "paper_only": True, "name": "ETF修剪百分比計算", "etf_symbol": "0050", "target_allocation_pct": 0.40, "current_allocation_pct": 0.55, "expected_trim_pct_positive": True, "should_auto_apply": False},
    {"fixture_id": "FX212-038", "schema_version": "212", "paper_only": True, "name": "ETF補回百分比計算", "etf_symbol": "0056", "target_allocation_pct": 0.20, "current_allocation_pct": 0.13, "expected_add_pct_positive": True, "should_auto_apply": False},
    {"fixture_id": "FX212-039", "schema_version": "212", "paper_only": True, "name": "ETF超重量計算", "current_allocation_pct": 0.58, "upper_rebalance_band_pct": 0.50, "expected_overweight_positive": True, "should_auto_apply": False},
    {"fixture_id": "FX212-040", "schema_version": "212", "paper_only": True, "name": "ETF不足量計算", "current_allocation_pct": 0.28, "lower_rebalance_band_pct": 0.35, "expected_underweight_positive": True, "should_auto_apply": False},
    # --- 41-50: profit taking summary fixtures ---
    {"fixture_id": "FX212-041", "schema_version": "212", "paper_only": True, "name": "停利摘要總部位數", "expected_total_position_count_gt": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-042", "schema_version": "212", "paper_only": True, "name": "停利摘要個股數", "expected_stock_profit_plan_count_gte": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-043", "schema_version": "212", "paper_only": True, "name": "停利摘要ETF數", "expected_etf_rebalance_plan_count_gte": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-044", "schema_version": "212", "paper_only": True, "name": "停利摘要第一停利計數", "expected_first_take_profit_count_gte": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-045", "schema_version": "212", "paper_only": True, "name": "停利摘要第二停利計數", "expected_second_take_profit_count_gte": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-046", "schema_version": "212", "paper_only": True, "name": "停利摘要runner保護計數", "expected_runner_protection_count_gte": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-047", "schema_version": "212", "paper_only": True, "name": "停利摘要回吐警示計數", "expected_giveback_warning_count_gte": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-048", "schema_version": "212", "paper_only": True, "name": "停利摘要壓力區計數", "expected_pressure_zone_reduce_count_gte": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-049", "schema_version": "212", "paper_only": True, "name": "停利摘要槓桿ETF警示計數", "expected_leveraged_etf_warning_count_gte": 0, "should_auto_apply": False},
    {"fixture_id": "FX212-050", "schema_version": "212", "paper_only": True, "name": "停利摘要人工審核計數", "expected_human_review_count_gte": 0, "should_auto_apply": False},
    # --- 51-60: export fixtures ---
    {"fixture_id": "FX212-051", "schema_version": "212", "paper_only": True, "name": "JSON匯出is_valid=True", "expected_is_valid": True, "export_format": "json", "should_auto_apply": False},
    {"fixture_id": "FX212-052", "schema_version": "212", "paper_only": True, "name": "JSON匯出export_status=complete", "expected_export_status": "complete", "export_format": "json", "should_auto_apply": False},
    {"fixture_id": "FX212-053", "schema_version": "212", "paper_only": True, "name": "JSON匯出paper_only_confirmed=True", "expected_paper_only_confirmed": True, "should_auto_apply": False},
    {"fixture_id": "FX212-054", "schema_version": "212", "paper_only": True, "name": "Markdown匯出is_valid=True", "expected_is_valid": True, "export_format": "markdown", "should_auto_apply": False},
    {"fixture_id": "FX212-055", "schema_version": "212", "paper_only": True, "name": "候選停利計畫CSV is_valid=True", "expected_is_valid": True, "export_format": "csv_profit_plan", "should_auto_apply": False},
    {"fixture_id": "FX212-056", "schema_version": "212", "paper_only": True, "name": "ETF再平衡CSV is_valid=True", "expected_is_valid": True, "export_format": "csv_etf", "should_auto_apply": False},
    {"fixture_id": "FX212-057", "schema_version": "212", "paper_only": True, "name": "停利警示佇列CSV is_valid=True", "expected_is_valid": True, "export_format": "csv_warning", "should_auto_apply": False},
    {"fixture_id": "FX212-058", "schema_version": "212", "paper_only": True, "name": "回吐審核佇列CSV is_valid=True", "expected_is_valid": True, "export_format": "csv_giveback", "should_auto_apply": False},
    {"fixture_id": "FX212-059", "schema_version": "212", "paper_only": True, "name": "稽核快照export_status=complete", "expected_export_status": "complete", "export_format": "audit_snapshot", "should_auto_apply": False},
    {"fixture_id": "FX212-060", "schema_version": "212", "paper_only": True, "name": "稽核快照reproducibility_hash非空", "expected_hash_nonempty": True, "should_auto_apply": False},
    # --- 61-70: CLI and GUI fixtures ---
    {"fixture_id": "FX212-061", "schema_version": "212", "paper_only": True, "name": "CLI停利審查指令已註冊", "cli_command": "paper-cockpit-v212-review-profit-taking", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-062", "schema_version": "212", "paper_only": True, "name": "CLI回吐風險評估已註冊", "cli_command": "paper-cockpit-v212-evaluate-giveback-risk", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-063", "schema_version": "212", "paper_only": True, "name": "CLI停利警示佇列已註冊", "cli_command": "paper-cockpit-v212-build-profit-warning-queue", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-064", "schema_version": "212", "paper_only": True, "name": "CLI回吐審核佇列已註冊", "cli_command": "paper-cockpit-v212-build-giveback-review-queue", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-065", "schema_version": "212", "paper_only": True, "name": "CLI ETF再平衡審查已註冊", "cli_command": "paper-cockpit-v212-review-etf-rebalancing", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-066", "schema_version": "212", "paper_only": True, "name": "CLI export-json已註冊", "cli_command": "paper-cockpit-v212-export-json", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-067", "schema_version": "212", "paper_only": True, "name": "CLI export-md已註冊", "cli_command": "paper-cockpit-v212-export-md", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-068", "schema_version": "212", "paper_only": True, "name": "CLI export-csv已註冊", "cli_command": "paper-cockpit-v212-export-csv", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-069", "schema_version": "212", "paper_only": True, "name": "CLI health已註冊", "cli_command": "paper-cockpit-v212-health", "expected_registered": True, "should_auto_apply": False},
    {"fixture_id": "FX212-070", "schema_version": "212", "paper_only": True, "name": "CLI gate已註冊", "cli_command": "paper-cockpit-v212-gate", "expected_registered": True, "should_auto_apply": False},
    # --- 71-80: safety, backward compat, model fixtures ---
    {"fixture_id": "FX212-071", "schema_version": "212", "paper_only": True, "name": "GUI profit_taking_v212 tab存在", "gui_tab": "profit_taking_v212", "expected_in_tabs": True, "should_auto_apply": False},
    {"fixture_id": "FX212-072", "schema_version": "212", "paper_only": True, "name": "GUI etf_rebalancing_v212 tab存在", "gui_tab": "etf_rebalancing_v212", "expected_in_tabs": True, "should_auto_apply": False},
    {"fixture_id": "FX212-073", "schema_version": "212", "paper_only": True, "name": "GUI giveback_review_queue_v212 tab存在", "gui_tab": "giveback_review_queue_v212", "expected_in_tabs": True, "should_auto_apply": False},
    {"fixture_id": "FX212-074", "schema_version": "212", "paper_only": True, "name": "v2.0.11向後相容-run_journal_review", "backward_compat": "v211", "expected_callable": True, "should_auto_apply": False},
    {"fixture_id": "FX212-075", "schema_version": "212", "paper_only": True, "name": "v2.0.10向後相容-run_exit_plan_review", "backward_compat": "v210", "expected_callable": True, "should_auto_apply": False},
    {"fixture_id": "FX212-076", "schema_version": "212", "paper_only": True, "name": "ProfitSafetyGuard所有旗標True", "model": "ProfitSafetyGuard", "expected_all_safety_true": True, "should_auto_apply": False},
    {"fixture_id": "FX212-077", "schema_version": "212", "paper_only": True, "name": "v212摘要paper_only=True", "expected_summary_paper_only": True, "should_auto_apply": False},
    {"fixture_id": "FX212-078", "schema_version": "212", "paper_only": True, "name": "16個模型全部可實例化", "expected_model_count": 16, "should_auto_apply": False},
    {"fixture_id": "FX212-079", "schema_version": "212", "paper_only": True, "name": "v201 health相對路徑相容", "expected_v201_path_exists": True, "should_auto_apply": False},
    {"fixture_id": "FX212-080", "schema_version": "212", "paper_only": True, "name": "run_profit_taking_review完整回傳", "expected_all_passed": True, "expected_paper_only": True, "should_auto_apply": False},
]

assert len(FIXTURES) == 80, f"Expected 80 fixtures, got {len(FIXTURES)}"
assert all(f["schema_version"] == "212" for f in FIXTURES), "Some fixtures have wrong schema_version"
assert all("fixture_id" in f for f in FIXTURES), "Some fixtures missing fixture_id"
assert all(f["paper_only"] is True for f in FIXTURES), "Some fixtures missing paper_only=True"
assert all(f["should_auto_apply"] is False for f in FIXTURES), "Some fixtures have should_auto_apply=True"
