"""
paper_trading/small_capital_strategy/paper_cockpit_fixtures_v200.py
v2.0.0 Paper Cockpit Unified Entry & Strategy Decision Console — Fixtures
[!] Paper Only. Research Only. Simulate Only. Validation Only.
[!] No Real Orders. No Broker. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List

_SAFETY = {
    "paper_only": True,
    "research_only": True,
    "simulate_only": True,
    "validation_only": True,
    "unified_paper_cockpit_only": True,
    "decision_console_only": True,
    "dashboard_only": True,
    "report_only": True,
    "audit_only": True,
    "no_real_orders": True,
    "no_broker": True,
    "no_margin": True,
    "no_leverage": True,
    "no_production_strategy_mutation": True,
    "no_automatic_rollback": True,
    "no_live_strategy_activation": True,
    "no_real_portfolio_rebalancing": True,
    "not_investment_advice": True,
    "human_review_required": True,
    "demo_only": True,
    "not_for_production": True,
    "production_trading_blocked": True,
}

FIXTURES: List[Dict[str, Any]] = [
    {"id": "PCFIX200-001", "fixture_id": "PCFIX200-001", "schema_version": "200",
     "name": "default_cockpit_input", "capital_twd": 300000.0,
     "market_regime": "BULL", "watchlist": ["2330", "2454"],
     "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-002", "fixture_id": "PCFIX200-002", "schema_version": "200",
     "name": "empty_watchlist_input", "capital_twd": 300000.0,
     "market_regime": "BULL", "watchlist": [],
     "expected_valid": False, **_SAFETY},
    {"id": "PCFIX200-003", "fixture_id": "PCFIX200-003", "schema_version": "200",
     "name": "a_pullback_10ma_conditions",
     "ma10_support": True, "volume_contraction": True, "continuous_institutional_selling": False,
     "expected_abc_type": "A_PULLBACK_10MA", **_SAFETY},
    {"id": "PCFIX200-004", "fixture_id": "PCFIX200-004", "schema_version": "200",
     "name": "b_breakout_base_conditions",
     "base_breakout": True, "volume_expansion_ratio": 2.0, "margin_financing_exploding": False,
     "expected_abc_type": "B_BREAKOUT_BASE", **_SAFETY},
    {"id": "PCFIX200-005", "fixture_id": "PCFIX200-005", "schema_version": "200",
     "name": "c_reclaim_20ma_conditions",
     "ma20_reclaim": True, "momentum_repair": True, "ma20_failed_again": False,
     "expected_abc_type": "C_RECLAIM_20MA", **_SAFETY},
    {"id": "PCFIX200-006", "fixture_id": "PCFIX200-006", "schema_version": "200",
     "name": "no_entry_conditions",
     "ma10_support": False, "base_breakout": False, "ma20_reclaim": False,
     "expected_abc_type": "NO_ENTRY", **_SAFETY},
    {"id": "PCFIX200-007", "fixture_id": "PCFIX200-007", "schema_version": "200",
     "name": "portfolio_risk_all_ok",
     "portfolio_risk_pct": 40.0, "theme_exposure_pct": 20.0,
     "cash_buffer_pct": 30.0, "risk_budget_remaining_pct": 50.0,
     "expected_overall_ok": True, **_SAFETY},
    {"id": "PCFIX200-008", "fixture_id": "PCFIX200-008", "schema_version": "200",
     "name": "portfolio_risk_exceeded",
     "portfolio_risk_pct": 70.0, "theme_exposure_pct": 20.0,
     "cash_buffer_pct": 30.0, "risk_budget_remaining_pct": 50.0,
     "expected_overall_ok": False, "expected_recommendation": "PAPER_BLOCK_NEW_ENTRY", **_SAFETY},
    {"id": "PCFIX200-009", "fixture_id": "PCFIX200-009", "schema_version": "200",
     "name": "theme_exposure_exceeded",
     "portfolio_risk_pct": 40.0, "theme_exposure_pct": 40.0,
     "cash_buffer_pct": 30.0, "risk_budget_remaining_pct": 50.0,
     "expected_overall_ok": False, **_SAFETY},
    {"id": "PCFIX200-010", "fixture_id": "PCFIX200-010", "schema_version": "200",
     "name": "cash_buffer_low",
     "portfolio_risk_pct": 40.0, "theme_exposure_pct": 20.0,
     "cash_buffer_pct": 10.0, "risk_budget_remaining_pct": 50.0,
     "expected_overall_ok": False, "expected_recommendation": "PAPER_KEEP_CASH", **_SAFETY},
    {"id": "PCFIX200-011", "fixture_id": "PCFIX200-011", "schema_version": "200",
     "name": "sizing_8pct_stop",
     "capital_twd": 300000.0, "stop_distance_pct": 0.08,
     "expected_sizing_ok": True, "expected_max_loss": 4500.0, **_SAFETY},
    {"id": "PCFIX200-012", "fixture_id": "PCFIX200-012", "schema_version": "200",
     "name": "sizing_stop_too_wide",
     "capital_twd": 300000.0, "stop_distance_pct": 0.20,
     "expected_sizing_ok": False, **_SAFETY},
    {"id": "PCFIX200-013", "fixture_id": "PCFIX200-013", "schema_version": "200",
     "name": "sizing_zero_stop",
     "capital_twd": 300000.0, "stop_distance_pct": 0.0,
     "expected_sizing_ok": False, **_SAFETY},
    {"id": "PCFIX200-014", "fixture_id": "PCFIX200-014", "schema_version": "200",
     "name": "signal_score_all_100",
     "theme_score": 100.0, "fundamental_score": 100.0, "technical_score": 100.0,
     "institutional_score": 100.0, "margin_score": 100.0,
     "expected_total": 100.0, "expected_grade": "A", "expected_tradable": True, **_SAFETY},
    {"id": "PCFIX200-015", "fixture_id": "PCFIX200-015", "schema_version": "200",
     "name": "signal_score_all_zero",
     "theme_score": 0.0, "fundamental_score": 0.0, "technical_score": 0.0,
     "institutional_score": 0.0, "margin_score": 0.0,
     "expected_total": 0.0, "expected_grade": "F", "expected_tradable": False, **_SAFETY},
    {"id": "PCFIX200-016", "fixture_id": "PCFIX200-016", "schema_version": "200",
     "name": "signal_score_grade_b",
     "theme_score": 75.0, "fundamental_score": 72.0, "technical_score": 70.0,
     "institutional_score": 71.0, "margin_score": 73.0,
     "expected_grade": "B", **_SAFETY},
    {"id": "PCFIX200-017", "fixture_id": "PCFIX200-017", "schema_version": "200",
     "name": "signal_score_grade_c",
     "theme_score": 60.0, "fundamental_score": 56.0, "technical_score": 55.0,
     "institutional_score": 57.0, "margin_score": 58.0,
     "expected_grade": "C", **_SAFETY},
    {"id": "PCFIX200-018", "fixture_id": "PCFIX200-018", "schema_version": "200",
     "name": "watchlist_30_symbols",
     "watchlist": [f"{2300 + i}" for i in range(30)],
     "expected_valid": True, "expected_count": 30, **_SAFETY},
    {"id": "PCFIX200-019", "fixture_id": "PCFIX200-019", "schema_version": "200",
     "name": "watchlist_31_symbols_oversized",
     "watchlist": [f"{2300 + i}" for i in range(31)],
     "expected_valid": False, **_SAFETY},
    {"id": "PCFIX200-020", "fixture_id": "PCFIX200-020", "schema_version": "200",
     "name": "decision_ticket_paper_only",
     "symbol": "2330", "abc_type": "A_PULLBACK_10MA",
     "expected_paper_only": True, "expected_no_broker": True,
     "expected_ticket_triggers_broker": False,
     "expected_ticket_executes_order": False, **_SAFETY},
    {"id": "PCFIX200-021", "fixture_id": "PCFIX200-021", "schema_version": "200",
     "name": "decision_ticket_blocked",
     "symbol": "2454", "abc_type": "NO_ENTRY",
     "expected_is_blocked": True, **_SAFETY},
    {"id": "PCFIX200-022", "fixture_id": "PCFIX200-022", "schema_version": "200",
     "name": "human_review_high_urgency_a_type",
     "abc_type": "A_PULLBACK_10MA",
     "expected_urgency": "HIGH", "expected_auto_approval_blocked": True, **_SAFETY},
    {"id": "PCFIX200-023", "fixture_id": "PCFIX200-023", "schema_version": "200",
     "name": "human_review_normal_urgency_b_type",
     "abc_type": "B_BREAKOUT_BASE",
     "expected_urgency": "NORMAL", **_SAFETY},
    {"id": "PCFIX200-024", "fixture_id": "PCFIX200-024", "schema_version": "200",
     "name": "dashboard_bull_regime",
     "market_regime": "BULL", "candidates_scored": 5,
     "expected_paper_only": True, "expected_no_production_writes": True, **_SAFETY},
    {"id": "PCFIX200-025", "fixture_id": "PCFIX200-025", "schema_version": "200",
     "name": "dashboard_risk_off_mode",
     "risk_off_mode": True, "expected_dashboard_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-026", "fixture_id": "PCFIX200-026", "schema_version": "200",
     "name": "report_triggers_no_real_order",
     "expected_report_triggers_real_order": False,
     "expected_report_activates_live_strategy": False, **_SAFETY},
    {"id": "PCFIX200-027", "fixture_id": "PCFIX200-027", "schema_version": "200",
     "name": "audit_trail_no_activation",
     "run_id": "test-run-001",
     "expected_audit_triggers_order": False,
     "expected_audit_activates_live_strategy": False, **_SAFETY},
    {"id": "PCFIX200-028", "fixture_id": "PCFIX200-028", "schema_version": "200",
     "name": "validation_default_input_valid",
     "schema_version_input": "200", "paper_only": True, "no_real_orders": True,
     "expected_is_valid": True, **_SAFETY},
    {"id": "PCFIX200-029", "fixture_id": "PCFIX200-029", "schema_version": "200",
     "name": "validation_wrong_schema_version_invalid",
     "schema_version_input": "100",
     "expected_is_valid": False, **_SAFETY},
    {"id": "PCFIX200-030", "fixture_id": "PCFIX200-030", "schema_version": "200",
     "name": "version_info_correct",
     "expected_version": "2.0.0", "expected_schema_version": "200", **_SAFETY},
    {"id": "PCFIX200-031", "fixture_id": "PCFIX200-031", "schema_version": "200",
     "name": "cockpit_summary_all_fields",
     "expected_models": 23, "expected_cli": 17, "expected_gui_tabs": 3, **_SAFETY},
    {"id": "PCFIX200-032", "fixture_id": "PCFIX200-032", "schema_version": "200",
     "name": "safety_flags_count_30",
     "expected_safety_flags_count": 30, **_SAFETY},
    {"id": "PCFIX200-033", "fixture_id": "PCFIX200-033", "schema_version": "200",
     "name": "forbidden_actions_count_10",
     "expected_forbidden_count": 10, **_SAFETY},
    {"id": "PCFIX200-034", "fixture_id": "PCFIX200-034", "schema_version": "200",
     "name": "allowed_actions_count_9",
     "expected_allowed_count": 9, **_SAFETY},
    {"id": "PCFIX200-035", "fixture_id": "PCFIX200-035", "schema_version": "200",
     "name": "hard_block_conditions_count_22",
     "expected_hard_block_count": 22, **_SAFETY},
    {"id": "PCFIX200-036", "fixture_id": "PCFIX200-036", "schema_version": "200",
     "name": "no_entry_conditions_count_8",
     "expected_no_entry_count": 8, **_SAFETY},
    {"id": "PCFIX200-037", "fixture_id": "PCFIX200-037", "schema_version": "200",
     "name": "abc_types_count_4",
     "expected_abc_count": 4, **_SAFETY},
    {"id": "PCFIX200-038", "fixture_id": "PCFIX200-038", "schema_version": "200",
     "name": "covered_versions_count_29",
     "expected_covered_count": 29, **_SAFETY},
    {"id": "PCFIX200-039", "fixture_id": "PCFIX200-039", "schema_version": "200",
     "name": "cli_commands_count_17",
     "expected_cli_count": 17, **_SAFETY},
    {"id": "PCFIX200-040", "fixture_id": "PCFIX200-040", "schema_version": "200",
     "name": "gui_tabs_count_3",
     "expected_gui_tab_count": 3, **_SAFETY},
    {"id": "PCFIX200-041", "fixture_id": "PCFIX200-041", "schema_version": "200",
     "name": "release_summary_model_count",
     "expected_models_count": 23, **_SAFETY},
    {"id": "PCFIX200-042", "fixture_id": "PCFIX200-042", "schema_version": "200",
     "name": "release_summary_baseline_tests",
     "expected_baseline": 31925, **_SAFETY},
    {"id": "PCFIX200-043", "fixture_id": "PCFIX200-043", "schema_version": "200",
     "name": "release_summary_min_new_tests",
     "expected_min_new": 500, **_SAFETY},
    {"id": "PCFIX200-044", "fixture_id": "PCFIX200-044", "schema_version": "200",
     "name": "a_pullback_ma10_support_required",
     "ma10_support": False, "volume_contraction": True,
     "expected_abc_type": "NO_ENTRY", **_SAFETY},
    {"id": "PCFIX200-045", "fixture_id": "PCFIX200-045", "schema_version": "200",
     "name": "a_pullback_volume_contraction_required",
     "ma10_support": True, "volume_contraction": False,
     "expected_abc_type": "NO_ENTRY", **_SAFETY},
    {"id": "PCFIX200-046", "fixture_id": "PCFIX200-046", "schema_version": "200",
     "name": "a_pullback_institutional_selling_blocks",
     "ma10_support": True, "volume_contraction": True, "continuous_institutional_selling": True,
     "expected_abc_type": "NO_ENTRY", **_SAFETY},
    {"id": "PCFIX200-047", "fixture_id": "PCFIX200-047", "schema_version": "200",
     "name": "b_breakout_volume_expansion_15x_minimum",
     "base_breakout": True, "volume_expansion_ratio": 1.4,
     "expected_abc_type": "NO_ENTRY", **_SAFETY},
    {"id": "PCFIX200-048", "fixture_id": "PCFIX200-048", "schema_version": "200",
     "name": "b_breakout_extended_reduced_size",
     "base_breakout": True, "volume_expansion_ratio": 3.5, "margin_financing_exploding": False,
     "expected_abc_type": "B_BREAKOUT_BASE", "expected_size_pct": 0.6, **_SAFETY},
    {"id": "PCFIX200-049", "fixture_id": "PCFIX200-049", "schema_version": "200",
     "name": "b_breakout_margin_explosion_blocks",
     "base_breakout": True, "volume_expansion_ratio": 2.0, "margin_financing_exploding": True,
     "expected_abc_type": "NO_ENTRY", **_SAFETY},
    {"id": "PCFIX200-050", "fixture_id": "PCFIX200-050", "schema_version": "200",
     "name": "c_reclaim_ma20_failed_blocks",
     "ma20_reclaim": True, "momentum_repair": True, "ma20_failed_again": True,
     "expected_abc_type": "NO_ENTRY", **_SAFETY},
    {"id": "PCFIX200-051", "fixture_id": "PCFIX200-051", "schema_version": "200",
     "name": "c_reclaim_no_momentum_repair_blocks",
     "ma20_reclaim": True, "momentum_repair": False, "ma20_failed_again": False,
     "expected_abc_type": "NO_ENTRY", **_SAFETY},
    {"id": "PCFIX200-052", "fixture_id": "PCFIX200-052", "schema_version": "200",
     "name": "cockpit_run_with_candidates",
     "watchlist": ["2330", "2454", "3008"],
     "candidates": ["2330", "2454"],
     "expected_all_passed": True, **_SAFETY},
    {"id": "PCFIX200-053", "fixture_id": "PCFIX200-053", "schema_version": "200",
     "name": "cockpit_run_no_candidates",
     "watchlist": ["2330"],
     "candidates": [],
     "expected_all_passed": True, **_SAFETY},
    {"id": "PCFIX200-054", "fixture_id": "PCFIX200-054", "schema_version": "200",
     "name": "cockpit_run_is_deterministic",
     "watchlist": ["2330"], "candidates": ["2330"],
     "expected_deterministic": True, **_SAFETY},
    {"id": "PCFIX200-055", "fixture_id": "PCFIX200-055", "schema_version": "200",
     "name": "model_paper_cockpit_input_schema",
     "expected_schema_version": "200", "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-056", "fixture_id": "PCFIX200-056", "schema_version": "200",
     "name": "model_paper_cockpit_watchlist_schema",
     "expected_schema_version": "200", "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-057", "fixture_id": "PCFIX200-057", "schema_version": "200",
     "name": "model_paper_cockpit_signal_score_schema",
     "expected_schema_version": "200", "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-058", "fixture_id": "PCFIX200-058", "schema_version": "200",
     "name": "model_paper_cockpit_theme_score_schema",
     "expected_schema_version": "200", "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-059", "fixture_id": "PCFIX200-059", "schema_version": "200",
     "name": "model_paper_cockpit_fundamental_score_schema",
     "expected_schema_version": "200", "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-060", "fixture_id": "PCFIX200-060", "schema_version": "200",
     "name": "model_paper_cockpit_technical_score_schema",
     "expected_schema_version": "200", "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-061", "fixture_id": "PCFIX200-061", "schema_version": "200",
     "name": "model_paper_cockpit_institutional_score_schema",
     "expected_schema_version": "200", "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-062", "fixture_id": "PCFIX200-062", "schema_version": "200",
     "name": "model_paper_cockpit_margin_score_schema",
     "expected_schema_version": "200", "expected_paper_only": True,
     "expected_no_margin": True, **_SAFETY},
    {"id": "PCFIX200-063", "fixture_id": "PCFIX200-063", "schema_version": "200",
     "name": "model_paper_cockpit_entry_check_schema",
     "expected_schema_version": "200", "expected_paper_only": True,
     "expected_no_real_orders": True, **_SAFETY},
    {"id": "PCFIX200-064", "fixture_id": "PCFIX200-064", "schema_version": "200",
     "name": "model_paper_cockpit_abc_decision_schema",
     "expected_schema_version": "200",
     "expected_cockpit_executes_order": False,
     "expected_cockpit_mutates_strategy": False, **_SAFETY},
    {"id": "PCFIX200-065", "fixture_id": "PCFIX200-065", "schema_version": "200",
     "name": "model_paper_cockpit_portfolio_risk_check_schema",
     "expected_schema_version": "200",
     "expected_no_real_portfolio_rebalancing": True, **_SAFETY},
    {"id": "PCFIX200-066", "fixture_id": "PCFIX200-066", "schema_version": "200",
     "name": "model_paper_cockpit_position_sizing_check_schema",
     "expected_schema_version": "200",
     "expected_sizing_executes_order": False,
     "expected_sizing_mutates_strategy": False, **_SAFETY},
    {"id": "PCFIX200-067", "fixture_id": "PCFIX200-067", "schema_version": "200",
     "name": "model_paper_cockpit_no_entry_condition_schema",
     "expected_schema_version": "200",
     "expected_cockpit_executes_order": False, **_SAFETY},
    {"id": "PCFIX200-068", "fixture_id": "PCFIX200-068", "schema_version": "200",
     "name": "model_paper_cockpit_decision_ticket_schema",
     "expected_schema_version": "200",
     "expected_ticket_triggers_broker": False,
     "expected_ticket_executes_order": False, **_SAFETY},
    {"id": "PCFIX200-069", "fixture_id": "PCFIX200-069", "schema_version": "200",
     "name": "model_paper_cockpit_human_review_schema",
     "expected_schema_version": "200",
     "expected_auto_approval_blocked": True,
     "expected_cockpit_auto_approves": False, **_SAFETY},
    {"id": "PCFIX200-070", "fixture_id": "PCFIX200-070", "schema_version": "200",
     "name": "model_paper_cockpit_dashboard_schema",
     "expected_schema_version": "200",
     "expected_dashboard_writes_production_db": False,
     "expected_dashboard_places_real_order": False, **_SAFETY},
    {"id": "PCFIX200-071", "fixture_id": "PCFIX200-071", "schema_version": "200",
     "name": "model_paper_cockpit_report_schema",
     "expected_schema_version": "200",
     "expected_report_triggers_real_order": False, **_SAFETY},
    {"id": "PCFIX200-072", "fixture_id": "PCFIX200-072", "schema_version": "200",
     "name": "model_paper_cockpit_audit_trail_schema",
     "expected_schema_version": "200",
     "expected_audit_triggers_order": False, **_SAFETY},
    {"id": "PCFIX200-073", "fixture_id": "PCFIX200-073", "schema_version": "200",
     "name": "model_paper_cockpit_validation_result_schema",
     "expected_schema_version": "200",
     "expected_paper_only": True, **_SAFETY},
    {"id": "PCFIX200-074", "fixture_id": "PCFIX200-074", "schema_version": "200",
     "name": "model_paper_cockpit_health_summary_schema",
     "expected_schema_version": "200",
     "expected_version": "2.0.0", **_SAFETY},
    {"id": "PCFIX200-075", "fixture_id": "PCFIX200-075", "schema_version": "200",
     "name": "model_paper_cockpit_release_summary_schema",
     "expected_schema_version": "200",
     "expected_version": "2.0.0",
     "expected_scenarios_count": 80, "expected_fixtures_count": 80, **_SAFETY},
    {"id": "PCFIX200-076", "fixture_id": "PCFIX200-076", "schema_version": "200",
     "name": "model_paper_cockpit_candidate_schema",
     "expected_schema_version": "200",
     "expected_paper_only": True,
     "expected_requires_human_review": True, **_SAFETY},
    {"id": "PCFIX200-077", "fixture_id": "PCFIX200-077", "schema_version": "200",
     "name": "model_paper_cockpit_result_schema",
     "expected_schema_version": "200",
     "expected_paper_only": True,
     "expected_cockpit_executes_order": False,
     "expected_cockpit_mutates_strategy": False, **_SAFETY},
    {"id": "PCFIX200-078", "fixture_id": "PCFIX200-078", "schema_version": "200",
     "name": "no_entry_evaluate_from_abc_no_entry",
     "abc_type": "NO_ENTRY", "portfolio_overall_ok": True, "sizing_ok": True,
     "expected_condition_triggered": True, **_SAFETY},
    {"id": "PCFIX200-079", "fixture_id": "PCFIX200-079", "schema_version": "200",
     "name": "no_entry_not_triggered_when_all_pass",
     "abc_type": "A_PULLBACK_10MA", "portfolio_overall_ok": True, "sizing_ok": True,
     "expected_condition_triggered": False, **_SAFETY},
    {"id": "PCFIX200-080", "fixture_id": "PCFIX200-080", "schema_version": "200",
     "name": "all_model_names_count_23",
     "expected_model_count": 23, **_SAFETY},
]

assert len(FIXTURES) == 80, f"Expected 80 fixtures, got {len(FIXTURES)}"
