"""
paper_trading/small_capital_strategy/paper_cockpit_scenarios_v212.py
v2.0.12 Paper Profit Taking & ETF Rebalancing Control — Scenarios
[!] Paper Only. Research Only. Profit Taking Recommendation Only. Validation Only.
[!] No Real Orders. No Broker. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List

SCHEMA_VERSION = "212"

SCENARIOS: List[Dict[str, Any]] = [
    # --- 1-10: profit taking policy scenarios ---
    {"scenario_id": "SC212-001", "schema_version": "212", "paper_only": True, "name": "標準停利政策", "description": "require_profit_plan_before_entry=True，auto_apply_enabled=False", "require_profit_plan_before_entry": True, "auto_apply_enabled": False, "should_auto_apply": False},
    {"scenario_id": "SC212-002", "schema_version": "212", "paper_only": True, "name": "auto_apply_enabled強制False", "description": "__post_init__強制auto_apply_enabled=False", "input_auto_apply_enabled": True, "expected_auto_apply_enabled": False, "should_auto_apply": False},
    {"scenario_id": "SC212-003", "schema_version": "212", "paper_only": True, "name": "require_profit_plan強制True", "description": "__post_init__強制require_profit_plan_before_entry=True", "input_require_profit_plan": False, "expected_require_profit_plan": True, "should_auto_apply": False},
    {"scenario_id": "SC212-004", "schema_version": "212", "paper_only": True, "name": "第一停利+20%", "description": "first_take_profit_pct=0.20", "first_take_profit_pct": 0.20, "should_auto_apply": False},
    {"scenario_id": "SC212-005", "schema_version": "212", "paper_only": True, "name": "第二停利+40%", "description": "second_take_profit_pct=0.40", "second_take_profit_pct": 0.40, "should_auto_apply": False},
    {"scenario_id": "SC212-006", "schema_version": "212", "paper_only": True, "name": "三分之一停利比例", "description": "first_take_profit_fraction=1/3, second_take_profit_fraction=1/3, runner_fraction=1/3", "first_take_profit_fraction": 0.333, "second_take_profit_fraction": 0.333, "runner_fraction": 0.334, "should_auto_apply": False},
    {"scenario_id": "SC212-007", "schema_version": "212", "paper_only": True, "name": "移動停利高點12%", "description": "trailing_stop_from_high_pct=0.12", "trailing_stop_from_high_pct": 0.12, "should_auto_apply": False},
    {"scenario_id": "SC212-008", "schema_version": "212", "paper_only": True, "name": "最大回吐15%警示", "description": "max_profit_giveback_pct=0.15", "max_profit_giveback_pct": 0.15, "should_auto_apply": False},
    {"scenario_id": "SC212-009", "schema_version": "212", "paper_only": True, "name": "壓力區退出啟用", "description": "weak_rebound_pressure_exit_enabled=True", "weak_rebound_pressure_exit_enabled": True, "should_auto_apply": False},
    {"scenario_id": "SC212-010", "schema_version": "212", "paper_only": True, "name": "所有profit_action均為建議", "description": "9種profit_action均為紙上建議，不自動執行", "profit_actions": ["hold_with_plan","take_first_third","take_second_third","protect_runner","tighten_trailing_stop","reduce_on_pressure","observation_only","block_new_add","human_review_required"], "should_auto_apply": False, "auto_apply_enabled": False},
    # --- 11-20: first take-profit trigger scenarios ---
    {"scenario_id": "SC212-011", "schema_version": "212", "paper_only": True, "name": "未達20%持有計畫", "description": "unrealized_return_pct<0.20，action=hold_with_plan", "entry_price": 100.0, "current_price": 115.0, "first_take_profit_triggered": False, "expected_profit_action": "hold_with_plan", "should_auto_apply": False},
    {"scenario_id": "SC212-012", "schema_version": "212", "paper_only": True, "name": "達到+20%觸發第一停利", "description": "unrealized_return_pct>=0.20，action=take_first_third", "entry_price": 100.0, "current_price": 121.0, "first_take_profit_triggered": False, "expected_profit_action": "take_first_third", "should_auto_apply": False},
    {"scenario_id": "SC212-013", "schema_version": "212", "paper_only": True, "name": "精確+20%觸發第一停利", "description": "unrealized_return_pct=0.20，action=take_first_third", "entry_price": 100.0, "current_price": 120.0, "first_take_profit_triggered": False, "expected_profit_action": "take_first_third", "should_auto_apply": False},
    {"scenario_id": "SC212-014", "schema_version": "212", "paper_only": True, "name": "第一停利已執行不重複", "description": "first_take_profit_triggered=True，<40%時不觸發第二停利", "entry_price": 100.0, "current_price": 130.0, "first_take_profit_triggered": True, "second_take_profit_triggered": False, "expected_profit_action": "hold_with_plan", "should_auto_apply": False},
    {"scenario_id": "SC212-015", "schema_version": "212", "paper_only": True, "name": "第一停利價格計算正確", "description": "first_take_profit_price=entry_price*1.20", "entry_price": 500.0, "expected_first_tp_price": 600.0, "should_auto_apply": False},
    {"scenario_id": "SC212-016", "schema_version": "212", "paper_only": True, "name": "高股息ETF不用個股停利", "description": "asset_type=etf，action=observation_only", "entry_price": 35.0, "current_price": 42.0, "asset_type": "etf", "expected_profit_action": "observation_only", "should_auto_apply": False},
    {"scenario_id": "SC212-017", "schema_version": "212", "paper_only": True, "name": "個股+19%不觸發", "description": "unrealized_return_pct=0.19，action=hold_with_plan", "entry_price": 100.0, "current_price": 119.0, "first_take_profit_triggered": False, "expected_profit_action": "hold_with_plan", "should_auto_apply": False},
    {"scenario_id": "SC212-018", "schema_version": "212", "paper_only": True, "name": "飆股+50%觸發第一停利", "description": "first_take_profit_triggered=False，unrealized_return_pct=0.50，action=take_first_third", "entry_price": 100.0, "current_price": 150.0, "first_take_profit_triggered": False, "expected_profit_action": "take_first_third", "should_auto_apply": False},
    {"scenario_id": "SC212-019", "schema_version": "212", "paper_only": True, "name": "無停利計畫阻止加碼", "description": "has_profit_plan=False，blocked_by_missing_profit_plan=True，action=block_new_add", "has_profit_plan": False, "expected_profit_action": "block_new_add", "should_auto_apply": False},
    {"scenario_id": "SC212-020", "schema_version": "212", "paper_only": True, "name": "停利計畫存在正常進行", "description": "has_profit_plan=True，允許正常評估", "has_profit_plan": True, "expected_blocked": False, "should_auto_apply": False},
    # --- 21-30: second take-profit and runner scenarios ---
    {"scenario_id": "SC212-021", "schema_version": "212", "paper_only": True, "name": "達到+40%觸發第二停利", "description": "first_triggered=True，unrealized_return_pct>=0.40，action=take_second_third", "entry_price": 100.0, "current_price": 141.0, "first_take_profit_triggered": True, "second_take_profit_triggered": False, "expected_profit_action": "take_second_third", "should_auto_apply": False},
    {"scenario_id": "SC212-022", "schema_version": "212", "paper_only": True, "name": "第二停利已執行移至runner", "description": "both_triggered=True，action=protect_runner", "entry_price": 100.0, "current_price": 155.0, "first_take_profit_triggered": True, "second_take_profit_triggered": True, "expected_profit_action": "protect_runner", "high_watermark_price": 160.0, "should_auto_apply": False},
    {"scenario_id": "SC212-023", "schema_version": "212", "paper_only": True, "name": "第二停利價格計算正確", "description": "second_take_profit_price=entry_price*1.40", "entry_price": 500.0, "expected_second_tp_price": 700.0, "should_auto_apply": False},
    {"scenario_id": "SC212-024", "schema_version": "212", "paper_only": True, "name": "runner_active=True當雙觸發", "description": "first_triggered=True and second_triggered=True，runner_active=True", "first_take_profit_triggered": True, "second_take_profit_triggered": True, "expected_runner_active": True, "should_auto_apply": False},
    {"scenario_id": "SC212-025", "schema_version": "212", "paper_only": True, "name": "runner跌破移動停利緊縮停利", "description": "current_price<=trailing_stop_price，action=tighten_trailing_stop", "entry_price": 100.0, "current_price": 148.0, "high_watermark_price": 170.0, "first_take_profit_triggered": True, "second_take_profit_triggered": True, "expected_profit_action": "tighten_trailing_stop", "should_auto_apply": False},
    {"scenario_id": "SC212-026", "schema_version": "212", "paper_only": True, "name": "移動停利價格計算", "description": "trailing_stop_price=high_watermark*0.88", "high_watermark_price": 200.0, "expected_trailing_stop": 176.0, "should_auto_apply": False},
    {"scenario_id": "SC212-027", "schema_version": "212", "paper_only": True, "name": "runner有blowoff訊號減碼", "description": "second_triggered=True，has_blowoff_signal=True，action=reduce_on_pressure", "first_take_profit_triggered": True, "second_take_profit_triggered": True, "has_blowoff_signal": True, "expected_profit_action": "reduce_on_pressure", "should_auto_apply": False},
    {"scenario_id": "SC212-028", "schema_version": "212", "paper_only": True, "name": "runner有壓力區訊號減碼", "description": "second_triggered=True，has_pressure_signal=True，action=reduce_on_pressure", "first_take_profit_triggered": True, "second_take_profit_triggered": True, "has_pressure_signal": True, "expected_profit_action": "reduce_on_pressure", "should_auto_apply": False},
    {"scenario_id": "SC212-029", "schema_version": "212", "paper_only": True, "name": "watchlist_candidate適用個股停利", "description": "asset_type=watchlist_candidate，走個股三分之一停利", "asset_type": "watchlist_candidate", "entry_price": 100.0, "current_price": 125.0, "first_take_profit_triggered": False, "expected_profit_action": "take_first_third", "should_auto_apply": False},
    {"scenario_id": "SC212-030", "schema_version": "212", "paper_only": True, "name": "theme_basket適用個股停利", "description": "asset_type=theme_basket，走個股三分之一停利", "asset_type": "theme_basket", "entry_price": 100.0, "current_price": 125.0, "first_take_profit_triggered": False, "expected_profit_action": "take_first_third", "should_auto_apply": False},
    # --- 31-40: giveback detection scenarios ---
    {"scenario_id": "SC212-031", "schema_version": "212", "paper_only": True, "name": "無回吐不警示", "description": "current_price=high_watermark_price，giveback=0", "current_price": 150.0, "high_watermark_price": 150.0, "expected_giveback": 0.0, "should_auto_apply": False},
    {"scenario_id": "SC212-032", "schema_version": "212", "paper_only": True, "name": "回吐10%不超標", "description": "giveback_from_high=0.10<0.15，不觸發human_review", "current_price": 135.0, "high_watermark_price": 150.0, "expected_giveback": 0.10, "should_auto_apply": False},
    {"scenario_id": "SC212-033", "schema_version": "212", "paper_only": True, "name": "回吐15%觸發警示", "description": "giveback_from_high=0.15=max，觸發human_review", "current_price": 127.5, "high_watermark_price": 150.0, "expected_human_review": True, "should_auto_apply": False},
    {"scenario_id": "SC212-034", "schema_version": "212", "paper_only": True, "name": "回吐20%超標", "description": "giveback_from_high=0.20>0.15，action=human_review_required", "current_price": 120.0, "high_watermark_price": 150.0, "expected_profit_action": "human_review_required", "should_auto_apply": False},
    {"scenario_id": "SC212-035", "schema_version": "212", "paper_only": True, "name": "回吐計算公式", "description": "giveback=(high-current)/high", "current_price": 80.0, "high_watermark_price": 100.0, "expected_giveback": 0.20, "should_auto_apply": False},
    {"scenario_id": "SC212-036", "schema_version": "212", "paper_only": True, "name": "高點等於進場價無回吐", "description": "high_watermark=entry_price，current=entry，giveback=0", "entry_price": 100.0, "current_price": 100.0, "high_watermark_price": 100.0, "expected_giveback": 0.0, "should_auto_apply": False},
    {"scenario_id": "SC212-037", "schema_version": "212", "paper_only": True, "name": "回吐佇列最低5%門檻", "description": "giveback>5%進入giveback_review_queue", "current_price": 142.0, "high_watermark_price": 150.0, "expected_in_giveback_queue": True, "should_auto_apply": False},
    {"scenario_id": "SC212-038", "schema_version": "212", "paper_only": True, "name": "無回吐不進佇列", "description": "giveback=0不進giveback_review_queue", "current_price": 150.0, "high_watermark_price": 150.0, "expected_in_giveback_queue": False, "should_auto_apply": False},
    {"scenario_id": "SC212-039", "schema_version": "212", "paper_only": True, "name": "虧損倉位不計回吐", "description": "current_price<entry_price，giveback=0（依定義）", "entry_price": 100.0, "current_price": 90.0, "high_watermark_price": 100.0, "expected_giveback": 0.0, "should_auto_apply": False},
    {"scenario_id": "SC212-040", "schema_version": "212", "paper_only": True, "name": "高點為0時回吐為0", "description": "high_watermark_price<=0，giveback=0", "current_price": 100.0, "high_watermark_price": 0.0, "expected_giveback": 0.0, "should_auto_apply": False},
    # --- 41-50: ETF rebalancing scenarios ---
    {"scenario_id": "SC212-041", "schema_version": "212", "paper_only": True, "name": "ETF在帶內持有", "description": "current_allocation在upper/lower之間，action=within_band_hold", "target_allocation_pct": 0.40, "current_allocation_pct": 0.43, "upper_rebalance_band_pct": 0.50, "lower_rebalance_band_pct": 0.35, "expected_rebalance_action": "within_band_hold", "should_auto_apply": False},
    {"scenario_id": "SC212-042", "schema_version": "212", "paper_only": True, "name": "ETF超過上限修剪", "description": "current_allocation>upper_band，action=trim_to_target_band", "target_allocation_pct": 0.40, "current_allocation_pct": 0.55, "upper_rebalance_band_pct": 0.50, "lower_rebalance_band_pct": 0.35, "expected_rebalance_action": "trim_to_target_band", "should_auto_apply": False},
    {"scenario_id": "SC212-043", "schema_version": "212", "paper_only": True, "name": "ETF低於下限補回", "description": "current_allocation<lower_band，action=add_back_to_target_band", "target_allocation_pct": 0.40, "current_allocation_pct": 0.30, "upper_rebalance_band_pct": 0.50, "lower_rebalance_band_pct": 0.35, "expected_rebalance_action": "add_back_to_target_band", "should_auto_apply": False},
    {"scenario_id": "SC212-044", "schema_version": "212", "paper_only": True, "name": "槓桿ETF超重減碼", "description": "is_leveraged_etf=True，current>target，action=reduce_leveraged_exposure", "target_allocation_pct": 0.05, "current_allocation_pct": 0.10, "is_leveraged_etf": True, "expected_rebalance_action": "reduce_leveraged_exposure", "should_auto_apply": False},
    {"scenario_id": "SC212-045", "schema_version": "212", "paper_only": True, "name": "槓桿ETF警示訊息", "description": "is_leveraged_etf=True，leveraged_etf_warning非空", "is_leveraged_etf": True, "expected_has_warning": True, "should_auto_apply": False},
    {"scenario_id": "SC212-046", "schema_version": "212", "paper_only": True, "name": "個股不走ETF再平衡", "description": "asset_type=stock不走ETF rebalancing路徑", "asset_type": "stock", "expected_uses_profit_plan": True, "should_auto_apply": False},
    {"scenario_id": "SC212-047", "schema_version": "212", "paper_only": True, "name": "ETF修剪建議百分比", "description": "recommended_trim_pct=current-target", "target_allocation_pct": 0.40, "current_allocation_pct": 0.55, "expected_trim_pct": 0.15, "should_auto_apply": False},
    {"scenario_id": "SC212-048", "schema_version": "212", "paper_only": True, "name": "ETF補回建議百分比", "description": "recommended_add_pct=target-current", "target_allocation_pct": 0.40, "current_allocation_pct": 0.30, "expected_add_pct": 0.10, "should_auto_apply": False},
    {"scenario_id": "SC212-049", "schema_version": "212", "paper_only": True, "name": "ETF超重量計算", "description": "overweight_pct=current-upper_band when current>upper", "current_allocation_pct": 0.56, "upper_rebalance_band_pct": 0.50, "expected_overweight_pct": 0.06, "should_auto_apply": False},
    {"scenario_id": "SC212-050", "schema_version": "212", "paper_only": True, "name": "ETF低於下限不足量計算", "description": "underweight_pct=lower_band-current when current<lower", "current_allocation_pct": 0.30, "lower_rebalance_band_pct": 0.35, "expected_underweight_pct": 0.05, "should_auto_apply": False},
    # --- 51-60: safety invariants ---
    {"scenario_id": "SC212-051", "schema_version": "212", "paper_only": True, "name": "should_auto_apply永遠False", "description": "CandidateProfitPlan.should_auto_apply強制False", "input_should_auto_apply": True, "expected_should_auto_apply": False, "should_auto_apply": False},
    {"scenario_id": "SC212-052", "schema_version": "212", "paper_only": True, "name": "ETFItem.should_auto_apply永遠False", "description": "ETFRebalancingItem.should_auto_apply強制False", "input_should_auto_apply": True, "expected_should_auto_apply": False, "should_auto_apply": False},
    {"scenario_id": "SC212-053", "schema_version": "212", "paper_only": True, "name": "ProfitReviewResult.should_auto_apply永遠False", "description": "ProfitReviewResult.should_auto_apply強制False", "input_should_auto_apply": True, "expected_should_auto_apply": False, "should_auto_apply": False},
    {"scenario_id": "SC212-054", "schema_version": "212", "paper_only": True, "name": "ProfitReviewResult.auto_apply_enabled永遠False", "description": "ProfitReviewResult.auto_apply_enabled強制False", "input_auto_apply_enabled": True, "expected_auto_apply_enabled": False, "should_auto_apply": False},
    {"scenario_id": "SC212-055", "schema_version": "212", "paper_only": True, "name": "停利行動只做紙上建議", "description": "profit_action不自動執行", "profit_action": "take_first_third", "is_recommendation_only": True, "should_auto_apply": False},
    {"scenario_id": "SC212-056", "schema_version": "212", "paper_only": True, "name": "ETF再平衡只做紙上建議", "description": "rebalance_action不自動執行", "rebalance_action": "trim_to_target_band", "is_recommendation_only": True, "should_auto_apply": False},
    {"scenario_id": "SC212-057", "schema_version": "212", "paper_only": True, "name": "NO_REAL_ORDERS=True", "description": "全版本NO_REAL_ORDERS永遠True", "expected_no_real_orders": True, "should_auto_apply": False},
    {"scenario_id": "SC212-058", "schema_version": "212", "paper_only": True, "name": "BROKER_EXECUTION_ENABLED=False", "description": "全版本BROKER_EXECUTION_ENABLED永遠False", "expected_broker_enabled": False, "should_auto_apply": False},
    {"scenario_id": "SC212-059", "schema_version": "212", "paper_only": True, "name": "PRODUCTION_TRADING_BLOCKED=True", "description": "全版本PRODUCTION_TRADING_BLOCKED永遠True", "expected_blocked": True, "should_auto_apply": False},
    {"scenario_id": "SC212-060", "schema_version": "212", "paper_only": True, "name": "所有25個安全旗標啟用", "description": "SAFETY_FLAGS_V212共25個旗標全True", "expected_safety_flag_count": 25, "should_auto_apply": False},
    # --- 61-70: integration scenarios ---
    {"scenario_id": "SC212-061", "schema_version": "212", "paper_only": True, "name": "整合v2.0.11日誌紀律", "description": "停利計畫與v2.0.11 trade journal整合", "v211_integration": True, "should_auto_apply": False},
    {"scenario_id": "SC212-062", "schema_version": "212", "paper_only": True, "name": "整合v2.0.10出場計畫", "description": "停利計畫與v2.0.10 exit plan整合", "v210_integration": True, "should_auto_apply": False},
    {"scenario_id": "SC212-063", "schema_version": "212", "paper_only": True, "name": "整合v2.0.9部位大小", "description": "停利計畫考量v2.0.9 position sizing", "v209_integration": True, "should_auto_apply": False},
    {"scenario_id": "SC212-064", "schema_version": "212", "paper_only": True, "name": "整合v2.0.8曝險控制", "description": "ETF再平衡考量v2.0.8 exposure control", "v208_integration": True, "should_auto_apply": False},
    {"scenario_id": "SC212-065", "schema_version": "212", "paper_only": True, "name": "整合v2.0.7主題輪動", "description": "停利計畫考量v2.0.7 market regime", "v207_integration": True, "should_auto_apply": False},
    {"scenario_id": "SC212-066", "schema_version": "212", "paper_only": True, "name": "JSON匯出格式完整", "description": "export_profit_taking_json包含所有必要欄位", "export_format": "json", "expected_is_valid": True, "should_auto_apply": False},
    {"scenario_id": "SC212-067", "schema_version": "212", "paper_only": True, "name": "Markdown報告格式完整", "description": "export_profit_taking_markdown有效且is_valid=True", "export_format": "markdown", "expected_is_valid": True, "should_auto_apply": False},
    {"scenario_id": "SC212-068", "schema_version": "212", "paper_only": True, "name": "候選停利計畫CSV匯出", "description": "export_candidate_profit_plan_csv有效", "export_format": "csv", "expected_is_valid": True, "should_auto_apply": False},
    {"scenario_id": "SC212-069", "schema_version": "212", "paper_only": True, "name": "ETF再平衡CSV匯出", "description": "export_etf_rebalancing_csv有效", "export_format": "csv", "expected_is_valid": True, "should_auto_apply": False},
    {"scenario_id": "SC212-070", "schema_version": "212", "paper_only": True, "name": "稽核快照匯出完整", "description": "export_profit_taking_audit_snapshot export_status=complete", "expected_export_status": "complete", "should_auto_apply": False},
    # --- 71-80: export, CLI, GUI, health scenarios ---
    {"scenario_id": "SC212-071", "schema_version": "212", "paper_only": True, "name": "停利警示佇列CSV", "description": "export_profit_warning_queue_csv有效", "export_format": "csv", "expected_is_valid": True, "should_auto_apply": False},
    {"scenario_id": "SC212-072", "schema_version": "212", "paper_only": True, "name": "回吐審核佇列CSV", "description": "export_giveback_review_queue_csv有效", "export_format": "csv", "expected_is_valid": True, "should_auto_apply": False},
    {"scenario_id": "SC212-073", "schema_version": "212", "paper_only": True, "name": "CLI停利審查指令", "description": "paper-cockpit-v212-review-profit-taking可調用", "cli_command": "paper-cockpit-v212-review-profit-taking", "should_auto_apply": False},
    {"scenario_id": "SC212-074", "schema_version": "212", "paper_only": True, "name": "CLI回吐風險評估指令", "description": "paper-cockpit-v212-evaluate-giveback-risk可調用", "cli_command": "paper-cockpit-v212-evaluate-giveback-risk", "should_auto_apply": False},
    {"scenario_id": "SC212-075", "schema_version": "212", "paper_only": True, "name": "CLI ETF再平衡指令", "description": "paper-cockpit-v212-review-etf-rebalancing可調用", "cli_command": "paper-cockpit-v212-review-etf-rebalancing", "should_auto_apply": False},
    {"scenario_id": "SC212-076", "schema_version": "212", "paper_only": True, "name": "GUI停利tab渲染正常", "description": "profit_taking_v212 tab render無錯誤", "gui_tab": "profit_taking_v212", "expected_no_error": True, "should_auto_apply": False},
    {"scenario_id": "SC212-077", "schema_version": "212", "paper_only": True, "name": "GUI ETF再平衡tab渲染正常", "description": "etf_rebalancing_v212 tab render無錯誤", "gui_tab": "etf_rebalancing_v212", "expected_no_error": True, "should_auto_apply": False},
    {"scenario_id": "SC212-078", "schema_version": "212", "paper_only": True, "name": "GUI回吐審核tab渲染正常", "description": "giveback_review_queue_v212 tab render無錯誤", "gui_tab": "giveback_review_queue_v212", "expected_no_error": True, "should_auto_apply": False},
    {"scenario_id": "SC212-079", "schema_version": "212", "paper_only": True, "name": "v2.0.11向後相容性", "description": "v2.0.11 run_journal_review仍可調用", "backward_compat_v211": True, "should_auto_apply": False},
    {"scenario_id": "SC212-080", "schema_version": "212", "paper_only": True, "name": "v201 health相對路徑相容", "description": "test_paper_cockpit_v201.py可透過相對路徑找到", "v201_relative_path": True, "should_auto_apply": False},
]

assert len(SCENARIOS) == 80, f"Expected 80 scenarios, got {len(SCENARIOS)}"
assert all(s["schema_version"] == "212" for s in SCENARIOS), "Some scenarios have wrong schema_version"
assert all(s["paper_only"] is True for s in SCENARIOS), "Some scenarios missing paper_only=True"
assert all(s["should_auto_apply"] is False for s in SCENARIOS), "Some scenarios have should_auto_apply=True"
