"""
paper_trading/small_capital_strategy/paper_cockpit_fixtures_v207.py
v2.0.7 Paper Theme Rotation & Market Regime Control — Fixtures
[!] Paper Only. Research Only. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List

SCHEMA_VERSION = "207"

FIXTURES: List[Dict[str, Any]] = [
    # --- 1-10: theme strength item fixtures ---
    {"fixture_id": "FX207-001", "schema_version": "207", "paper_only": True, "theme_id": "THEME-AI", "theme_name": "人工智慧", "theme_group": "technology", "theme_score": 88.0, "momentum_score": 82.0, "breadth_score": 76.0, "leadership_score": 85.0, "earnings_support_score": 72.0, "volume_confirmation_score": 80.0, "institutional_support_score": 84.0, "overheating_score": 28.0, "weakening_score": 8.0, "concentration_risk_score": 42.0, "candidate_count": 9, "promoted_candidate_count": 4, "stale_candidate_count": 1, "expired_candidate_count": 0, "active_candidate_count": 8, "expected_state": "leading"},
    {"fixture_id": "FX207-002", "schema_version": "207", "paper_only": True, "theme_id": "THEME-SEMI", "theme_name": "半導體", "theme_group": "technology", "theme_score": 91.0, "momentum_score": 87.0, "breadth_score": 82.0, "leadership_score": 90.0, "earnings_support_score": 85.0, "volume_confirmation_score": 88.0, "institutional_support_score": 92.0, "overheating_score": 58.0, "weakening_score": 4.0, "concentration_risk_score": 72.0, "candidate_count": 11, "promoted_candidate_count": 6, "stale_candidate_count": 0, "expired_candidate_count": 0, "active_candidate_count": 11, "expected_state": "crowded"},
    {"fixture_id": "FX207-003", "schema_version": "207", "paper_only": True, "theme_id": "THEME-EV", "theme_name": "電動車", "theme_group": "green_energy", "theme_score": 56.0, "momentum_score": 52.0, "breadth_score": 48.0, "leadership_score": 50.0, "earnings_support_score": 45.0, "volume_confirmation_score": 50.0, "institutional_support_score": 48.0, "overheating_score": 18.0, "weakening_score": 32.0, "concentration_risk_score": 28.0, "candidate_count": 5, "promoted_candidate_count": 2, "stale_candidate_count": 2, "expired_candidate_count": 0, "active_candidate_count": 5, "expected_state": "strengthening"},
    {"fixture_id": "FX207-004", "schema_version": "207", "paper_only": True, "theme_id": "THEME-BIOTECH", "theme_name": "生技", "theme_group": "healthcare", "theme_score": 42.0, "momentum_score": 38.0, "breadth_score": 35.0, "leadership_score": 40.0, "earnings_support_score": 35.0, "volume_confirmation_score": 38.0, "institutional_support_score": 35.0, "overheating_score": 10.0, "weakening_score": 20.0, "concentration_risk_score": 20.0, "candidate_count": 3, "promoted_candidate_count": 1, "stale_candidate_count": 1, "expired_candidate_count": 0, "active_candidate_count": 3, "expected_state": "emerging"},
    {"fixture_id": "FX207-005", "schema_version": "207", "paper_only": True, "theme_id": "THEME-SOLAR", "theme_name": "太陽能", "theme_group": "green_energy", "theme_score": 30.0, "momentum_score": 25.0, "breadth_score": 28.0, "leadership_score": 28.0, "earnings_support_score": 25.0, "volume_confirmation_score": 26.0, "institutional_support_score": 22.0, "overheating_score": 8.0, "weakening_score": 58.0, "concentration_risk_score": 18.0, "candidate_count": 2, "promoted_candidate_count": 0, "stale_candidate_count": 2, "expired_candidate_count": 1, "active_candidate_count": 1, "expected_state": "weakening"},
    {"fixture_id": "FX207-006", "schema_version": "207", "paper_only": True, "theme_id": "THEME-CLOUD", "theme_name": "雲端運算", "theme_group": "technology", "theme_score": 78.0, "momentum_score": 72.0, "breadth_score": 68.0, "leadership_score": 75.0, "earnings_support_score": 68.0, "volume_confirmation_score": 72.0, "institutional_support_score": 75.0, "overheating_score": 82.0, "weakening_score": 6.0, "concentration_risk_score": 60.0, "candidate_count": 7, "promoted_candidate_count": 4, "stale_candidate_count": 0, "expired_candidate_count": 0, "active_candidate_count": 7, "expected_state": "overheating"},
    {"fixture_id": "FX207-007", "schema_version": "207", "paper_only": True, "theme_id": "THEME-REIT", "theme_name": "不動產", "theme_group": "real_estate", "theme_score": 22.0, "momentum_score": 18.0, "breadth_score": 20.0, "leadership_score": 20.0, "earnings_support_score": 18.0, "volume_confirmation_score": 16.0, "institutional_support_score": 15.0, "overheating_score": 5.0, "weakening_score": 56.0, "concentration_risk_score": 12.0, "candidate_count": 1, "promoted_candidate_count": 0, "stale_candidate_count": 1, "expired_candidate_count": 1, "active_candidate_count": 0, "expected_state": "stale"},
    {"fixture_id": "FX207-008", "schema_version": "207", "paper_only": True, "theme_id": "THEME-FIN", "theme_name": "金融", "theme_group": "finance", "theme_score": 50.0, "momentum_score": 48.0, "breadth_score": 50.0, "leadership_score": 48.0, "earnings_support_score": 50.0, "volume_confirmation_score": 46.0, "institutional_support_score": 50.0, "overheating_score": 25.0, "weakening_score": 22.0, "concentration_risk_score": 30.0, "candidate_count": 4, "promoted_candidate_count": 2, "stale_candidate_count": 1, "expired_candidate_count": 0, "active_candidate_count": 4, "expected_state": "neutral"},
    {"fixture_id": "FX207-009", "schema_version": "207", "paper_only": True, "theme_id": "THEME-STEEL", "theme_name": "鋼鐵", "theme_group": "materials", "theme_score": 18.0, "momentum_score": 14.0, "breadth_score": 16.0, "leadership_score": 16.0, "earnings_support_score": 12.0, "volume_confirmation_score": 14.0, "institutional_support_score": 10.0, "overheating_score": 3.0, "weakening_score": 28.0, "concentration_risk_score": 10.0, "candidate_count": 1, "promoted_candidate_count": 0, "stale_candidate_count": 1, "expired_candidate_count": 1, "active_candidate_count": 0, "expected_state": "risk_off"},
    {"fixture_id": "FX207-010", "schema_version": "207", "paper_only": True, "theme_id": "THEME-ROBOT", "theme_name": "機器人", "theme_group": "automation", "theme_score": 65.0, "momentum_score": 60.0, "breadth_score": 58.0, "leadership_score": 62.0, "earnings_support_score": 55.0, "volume_confirmation_score": 62.0, "institutional_support_score": 60.0, "overheating_score": 22.0, "weakening_score": 15.0, "concentration_risk_score": 35.0, "candidate_count": 5, "promoted_candidate_count": 3, "stale_candidate_count": 0, "expired_candidate_count": 0, "active_candidate_count": 5, "expected_state": "strengthening"},
    # --- 11-20: market regime fixtures ---
    {"fixture_id": "FX207-011", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-UPTREND", "regime_name": "Strong Uptrend", "index_trend_score": 82.0, "breadth_score": 78.0, "volume_score": 75.0, "volatility_score": 30.0, "risk_appetite_score": 80.0, "institutional_flow_score": 78.0, "margin_risk_score": 30.0, "expected_market_state": "strong_uptrend", "expected_risk_mode": "aggressive_paper"},
    {"fixture_id": "FX207-012", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-PULLBACK", "regime_name": "Healthy Pullback", "index_trend_score": 62.0, "breadth_score": 60.0, "volume_score": 55.0, "volatility_score": 38.0, "risk_appetite_score": 62.0, "institutional_flow_score": 60.0, "margin_risk_score": 35.0, "expected_market_state": "healthy_pullback", "expected_risk_mode": "normal_paper"},
    {"fixture_id": "FX207-013", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-RANGE", "regime_name": "Range Bound", "index_trend_score": 50.0, "breadth_score": 50.0, "volume_score": 48.0, "volatility_score": 40.0, "risk_appetite_score": 52.0, "institutional_flow_score": 48.0, "margin_risk_score": 40.0, "expected_market_state": "range_bound", "expected_risk_mode": "normal_paper"},
    {"fixture_id": "FX207-014", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-WEAK", "regime_name": "Weak Rebound", "index_trend_score": 44.0, "breadth_score": 40.0, "volume_score": 36.0, "volatility_score": 48.0, "risk_appetite_score": 44.0, "institutional_flow_score": 42.0, "margin_risk_score": 48.0, "expected_market_state": "weak_rebound", "expected_risk_mode": "defensive_paper"},
    {"fixture_id": "FX207-015", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-DOWN", "regime_name": "Downtrend", "index_trend_score": 22.0, "breadth_score": 25.0, "volume_score": 35.0, "volatility_score": 62.0, "risk_appetite_score": 30.0, "institutional_flow_score": 25.0, "margin_risk_score": 65.0, "expected_market_state": "downtrend", "expected_risk_mode": "observation_only"},
    {"fixture_id": "FX207-016", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-VOLAT", "regime_name": "High Volatility", "index_trend_score": 50.0, "breadth_score": 45.0, "volume_score": 60.0, "volatility_score": 88.0, "risk_appetite_score": 38.0, "institutional_flow_score": 40.0, "margin_risk_score": 72.0, "expected_market_state": "high_volatility", "expected_risk_mode": "defensive_paper"},
    {"fixture_id": "FX207-017", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-RISKOFF", "regime_name": "Risk Off", "index_trend_score": 18.0, "breadth_score": 20.0, "volume_score": 28.0, "volatility_score": 72.0, "risk_appetite_score": 12.0, "institutional_flow_score": 15.0, "margin_risk_score": 80.0, "expected_market_state": "risk_off", "expected_risk_mode": "freeze_promotion"},
    {"fixture_id": "FX207-018", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-UPTREND-PROMO", "regime_name": "Uptrend Promotion", "index_trend_score": 75.0, "breadth_score": 70.0, "volume_score": 68.0, "volatility_score": 25.0, "risk_appetite_score": 72.0, "expected_candidate_promotion_allowed": True, "expected_aggressive_entry": True},
    {"fixture_id": "FX207-019", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-FREEZE", "regime_name": "Freeze Promotion", "index_trend_score": 20.0, "breadth_score": 18.0, "volume_score": 25.0, "volatility_score": 75.0, "risk_appetite_score": 10.0, "expected_candidate_promotion_allowed": False, "expected_aggressive_entry": False},
    {"fixture_id": "FX207-020", "schema_version": "207", "paper_only": True, "regime_id": "REGIME-SHOULD-AUTO-APPLY", "regime_name": "Auto Apply Test", "index_trend_score": 60.0, "breadth_score": 55.0, "volume_score": 55.0, "volatility_score": 40.0, "risk_appetite_score": 60.0, "should_auto_apply": False},
    # --- 21-30: candidate priority adjustment fixtures ---
    {"fixture_id": "FX207-021", "schema_version": "207", "paper_only": True, "symbol": "2330", "name": "台積電", "candidate_id": "CAND-2330-001", "theme_id": "THEME-SEMI", "theme_state": "leading", "market_state": "strong_uptrend", "original_score": 75.0, "expected_priority_change": "promote_priority", "should_auto_apply": False},
    {"fixture_id": "FX207-022", "schema_version": "207", "paper_only": True, "symbol": "2317", "name": "鴻海", "candidate_id": "CAND-2317-001", "theme_id": "THEME-EV", "theme_state": "strengthening", "market_state": "range_bound", "original_score": 60.0, "expected_priority_change": "keep_priority", "should_auto_apply": False},
    {"fixture_id": "FX207-023", "schema_version": "207", "paper_only": True, "symbol": "2454", "name": "聯發科", "candidate_id": "CAND-2454-001", "theme_id": "THEME-AI", "theme_state": "leading", "market_state": "healthy_pullback", "original_score": 65.0, "expected_blocked_by_market": False, "should_auto_apply": False},
    {"fixture_id": "FX207-024", "schema_version": "207", "paper_only": True, "symbol": "2412", "name": "中華電", "candidate_id": "CAND-2412-001", "theme_id": "THEME-REIT", "theme_state": "stale", "market_state": "range_bound", "original_score": 55.0, "expected_blocked_by_theme": True, "should_auto_apply": False},
    {"fixture_id": "FX207-025", "schema_version": "207", "paper_only": True, "symbol": "2303", "name": "聯電", "candidate_id": "CAND-2303-001", "theme_id": "THEME-SEMI", "theme_state": "overheating", "market_state": "range_bound", "original_score": 70.0, "expected_blocked_by_theme": True, "should_auto_apply": False},
    {"fixture_id": "FX207-026", "schema_version": "207", "paper_only": True, "symbol": "2308", "name": "台達電", "candidate_id": "CAND-2308-001", "theme_id": "THEME-EV", "theme_state": "weakening", "market_state": "healthy_pullback", "original_score": 60.0, "expected_priority_change": "reduce_priority", "should_auto_apply": False},
    {"fixture_id": "FX207-027", "schema_version": "207", "paper_only": True, "symbol": "2382", "name": "廣達", "candidate_id": "CAND-2382-001", "theme_id": "THEME-AI", "theme_state": "neutral", "market_state": "downtrend", "original_score": 65.0, "expected_blocked_by_market": True, "should_auto_apply": False},
    {"fixture_id": "FX207-028", "schema_version": "207", "paper_only": True, "symbol": "2409", "name": "友達", "candidate_id": "CAND-2409-001", "theme_id": "THEME-STEEL", "theme_state": "risk_off", "market_state": "range_bound", "original_score": 50.0, "expected_priority_change": "human_review_required", "should_auto_apply": False},
    {"fixture_id": "FX207-029", "schema_version": "207", "paper_only": True, "symbol": "3711", "name": "日月光", "candidate_id": "CAND-3711-001", "theme_id": "THEME-SEMI", "theme_state": "crowded", "market_state": "strong_uptrend", "original_score": 72.0, "should_auto_apply": False},
    {"fixture_id": "FX207-030", "schema_version": "207", "paper_only": True, "symbol": "2357", "name": "華碩", "candidate_id": "CAND-2357-001", "theme_id": "THEME-ROBOT", "theme_state": "strengthening", "market_state": "range_bound", "original_score": 62.0, "should_auto_apply": False},
    # --- 31-40: theme rotation summary fixtures ---
    {"fixture_id": "FX207-031", "schema_version": "207", "paper_only": True, "total_theme_count": 10, "leading_theme_count": 3, "strengthening_theme_count": 2, "overheating_theme_count": 1, "weakening_theme_count": 1, "stale_theme_count": 1, "risk_off_theme_count": 0, "expected_theme_grade": "B"},
    {"fixture_id": "FX207-032", "schema_version": "207", "paper_only": True, "total_theme_count": 10, "leading_theme_count": 5, "strengthening_theme_count": 3, "overheating_theme_count": 0, "weakening_theme_count": 0, "stale_theme_count": 0, "risk_off_theme_count": 0, "expected_theme_grade": "A"},
    {"fixture_id": "FX207-033", "schema_version": "207", "paper_only": True, "total_theme_count": 10, "leading_theme_count": 0, "strengthening_theme_count": 0, "overheating_theme_count": 5, "weakening_theme_count": 3, "stale_theme_count": 2, "risk_off_theme_count": 2, "expected_theme_grade": "D"},
    {"fixture_id": "FX207-034", "schema_version": "207", "paper_only": True, "top_leading_themes": ["人工智慧", "半導體", "雲端運算"], "top_strengthening_themes": ["電動車", "機器人"]},
    {"fixture_id": "FX207-035", "schema_version": "207", "paper_only": True, "candidate_count_by_theme": {"THEME-AI": 8, "THEME-SEMI": 10, "THEME-EV": 5}},
    {"fixture_id": "FX207-036", "schema_version": "207", "paper_only": True, "promotion_allowed_count": 8, "promotion_blocked_count": 2},
    {"fixture_id": "FX207-037", "schema_version": "207", "paper_only": True, "regime_score": 72.0, "expected_regime_grade": "A"},
    {"fixture_id": "FX207-038", "schema_version": "207", "paper_only": True, "regime_score": 58.0, "expected_regime_grade": "B"},
    {"fixture_id": "FX207-039", "schema_version": "207", "paper_only": True, "regime_score": 42.0, "expected_regime_grade": "C"},
    {"fixture_id": "FX207-040", "schema_version": "207", "paper_only": True, "regime_score": 30.0, "expected_regime_grade": "D"},
    # --- 41-50: theme rotation review result fixtures ---
    {"fixture_id": "FX207-041", "schema_version": "207", "paper_only": True, "review_period": "2026-W29", "expected_review_id_len": 10},
    {"fixture_id": "FX207-042", "schema_version": "207", "paper_only": True, "theme_rotation_version": "2.0.7"},
    {"fixture_id": "FX207-043", "schema_version": "207", "paper_only": True, "paper_only": True, "should_auto_apply": False},
    {"fixture_id": "FX207-044", "schema_version": "207", "paper_only": True, "all_passed": True},
    {"fixture_id": "FX207-045", "schema_version": "207", "paper_only": True, "paper_only_safety_snapshot": True},
    {"fixture_id": "FX207-046", "schema_version": "207", "paper_only": True, "review_period": "2026-W01", "theme_count": 5},
    {"fixture_id": "FX207-047", "schema_version": "207", "paper_only": True, "review_period": "2026-W52", "theme_count": 10},
    {"fixture_id": "FX207-048", "schema_version": "207", "paper_only": True, "review_period": "2026-W15", "theme_count": 3},
    {"fixture_id": "FX207-049", "schema_version": "207", "paper_only": True, "human_review_required": True},
    {"fixture_id": "FX207-050", "schema_version": "207", "paper_only": True, "not_investment_advice": True, "no_broker": True},
    # --- 51-60: export format fixtures ---
    {"fixture_id": "FX207-051", "schema_version": "207", "paper_only": True, "export_format": "json", "expected_contains": "theme_rotation_review_id"},
    {"fixture_id": "FX207-052", "schema_version": "207", "paper_only": True, "export_format": "json", "expected_contains": "paper_only"},
    {"fixture_id": "FX207-053", "schema_version": "207", "paper_only": True, "export_format": "json", "expected_contains": "should_auto_apply"},
    {"fixture_id": "FX207-054", "schema_version": "207", "paper_only": True, "export_format": "markdown", "expected_contains": "Theme Rotation Report v2.0.7"},
    {"fixture_id": "FX207-055", "schema_version": "207", "paper_only": True, "export_format": "markdown", "expected_contains": "Paper Only"},
    {"fixture_id": "FX207-056", "schema_version": "207", "paper_only": True, "export_format": "csv", "expected_header": "theme_id,theme_name,theme_rank,theme_score,momentum_score,theme_state,theme_action,should_auto_apply"},
    {"fixture_id": "FX207-057", "schema_version": "207", "paper_only": True, "export_format": "csv", "expected_contains_false": "False"},
    {"fixture_id": "FX207-058", "schema_version": "207", "paper_only": True, "export_format": "audit_snapshot", "expected_has_hash": True},
    {"fixture_id": "FX207-059", "schema_version": "207", "paper_only": True, "export_format": "audit_snapshot", "expected_contains": "paper_only"},
    {"fixture_id": "FX207-060", "schema_version": "207", "paper_only": True, "export_format": "json", "is_valid": True, "export_status": "complete"},
    # --- 61-70: safety flag fixtures ---
    {"fixture_id": "FX207-061", "schema_version": "207", "paper_only": True, "flag": "paper_only", "expected": True},
    {"fixture_id": "FX207-062", "schema_version": "207", "paper_only": True, "flag": "research_only", "expected": True},
    {"fixture_id": "FX207-063", "schema_version": "207", "paper_only": True, "flag": "theme_rotation_only", "expected": True},
    {"fixture_id": "FX207-064", "schema_version": "207", "paper_only": True, "flag": "market_regime_only", "expected": True},
    {"fixture_id": "FX207-065", "schema_version": "207", "paper_only": True, "flag": "no_real_orders", "expected": True},
    {"fixture_id": "FX207-066", "schema_version": "207", "paper_only": True, "flag": "no_broker", "expected": True},
    {"fixture_id": "FX207-067", "schema_version": "207", "paper_only": True, "flag": "should_auto_apply_always_false", "expected": True},
    {"fixture_id": "FX207-068", "schema_version": "207", "paper_only": True, "flag": "broker_execution_disabled", "expected": True},
    {"fixture_id": "FX207-069", "schema_version": "207", "paper_only": True, "flag": "production_trading_blocked", "expected": True},
    {"fixture_id": "FX207-070", "schema_version": "207", "paper_only": True, "total_flag_count": 20},
    # --- 71-80: backward compatibility fixtures ---
    {"fixture_id": "FX207-071", "schema_version": "207", "paper_only": True, "description": "v2.0.6 run_lifecycle_review callable and returns LifecycleReviewResult"},
    {"fixture_id": "FX207-072", "schema_version": "207", "paper_only": True, "description": "v2.0.5 run_watchlist_rotation callable and returns WatchlistRotationResult"},
    {"fixture_id": "FX207-073", "schema_version": "207", "paper_only": True, "description": "v2.0.6 VERSION unchanged at 2.0.6"},
    {"fixture_id": "FX207-074", "schema_version": "207", "paper_only": True, "description": "v2.0.5 VERSION unchanged at 2.0.5"},
    {"fixture_id": "FX207-075", "schema_version": "207", "paper_only": True, "description": "v2.0.6 SAFETY_FLAGS_V206 still 20 flags"},
    {"fixture_id": "FX207-076", "schema_version": "207", "paper_only": True, "description": "v2.0.5 SAFETY_FLAGS_V205 still 20 flags"},
    {"fixture_id": "FX207-077", "schema_version": "207", "paper_only": True, "description": "GUI tab candidate_lifecycle_v206 still present"},
    {"fixture_id": "FX207-078", "schema_version": "207", "paper_only": True, "description": "GUI tab watchlist_rotation_v205 still present"},
    {"fixture_id": "FX207-079", "schema_version": "207", "paper_only": True, "description": "v201 health relative-path test file exists"},
    {"fixture_id": "FX207-080", "schema_version": "207", "paper_only": True, "description": "render_all_tabs has no error tabs for any version"},
]

assert len(FIXTURES) == 80, f"Expected 80 fixtures, got {len(FIXTURES)}"
assert all(f["schema_version"] == "207" for f in FIXTURES)
assert all(f["paper_only"] is True for f in FIXTURES)
assert all("fixture_id" in f for f in FIXTURES)
