"""
paper_trading/small_capital_strategy/paper_cockpit_fixtures_v204.py
v2.0.4 Paper Portfolio Review Loop & Weekly Improvement Pack — Fixtures
[!] Paper Only. Research Only. Review Only. No Real Orders. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List

_F = {
    "schema_version": "204", "paper_only": True, "no_real_orders": True,
    "review_only": True, "research_only": True,
}

FIXTURES: List[Dict[str, Any]] = [
    {**_F, "id": "PC204-F001", "fixture_id": "PC204-F001", "name": "default_portfolio_review_input",
     "description": "Default PortfolioReviewInput fixture", "model": "PortfolioReviewInput",
     "data": {"review_version": "2.0.4", "review_period": "2026-W29", "decision_snapshot": ["2330", "2317"]}},
    {**_F, "id": "PC204-F002", "fixture_id": "PC204-F002", "name": "empty_portfolio_review_input",
     "description": "Empty PortfolioReviewInput fixture", "model": "PortfolioReviewInput",
     "data": {"review_period": "2026-W29", "decision_snapshot": []}},
    {**_F, "id": "PC204-F003", "fixture_id": "PC204-F003", "name": "recommendation_entry_rule",
     "description": "ImprovementRecommendation with entry_rule category", "model": "ImprovementRecommendation",
     "data": {"category": "entry_rule", "severity": "low", "should_auto_apply": False}},
    {**_F, "id": "PC204-F004", "fixture_id": "PC204-F004", "name": "recommendation_risk_budget",
     "description": "ImprovementRecommendation with risk_budget category", "model": "ImprovementRecommendation",
     "data": {"category": "risk_budget", "severity": "medium", "should_auto_apply": False}},
    {**_F, "id": "PC204-F005", "fixture_id": "PC204-F005", "name": "recommendation_no_entry_rule",
     "description": "ImprovementRecommendation with no_entry_rule category", "model": "ImprovementRecommendation",
     "data": {"category": "no_entry_rule", "severity": "low", "should_auto_apply": False}},
    {**_F, "id": "PC204-F006", "fixture_id": "PC204-F006", "name": "recommendation_exit_rule",
     "description": "ImprovementRecommendation with exit_rule category", "model": "ImprovementRecommendation",
     "data": {"category": "exit_rule", "severity": "medium", "should_auto_apply": False}},
    {**_F, "id": "PC204-F007", "fixture_id": "PC204-F007", "name": "recommendation_position_sizing",
     "description": "ImprovementRecommendation with position_sizing category", "model": "ImprovementRecommendation",
     "data": {"category": "position_sizing", "severity": "low", "should_auto_apply": False}},
    {**_F, "id": "PC204-F008", "fixture_id": "PC204-F008", "name": "recommendation_human_review",
     "description": "ImprovementRecommendation with human_review category", "model": "ImprovementRecommendation",
     "data": {"category": "human_review", "severity": "high", "should_auto_apply": False}},
    {**_F, "id": "PC204-F009", "fixture_id": "PC204-F009", "name": "review_metrics_default",
     "description": "ReviewMetrics with default values", "model": "ReviewMetrics",
     "data": {"final_review_grade": "C"}},
    {**_F, "id": "PC204-F010", "fixture_id": "PC204-F010", "name": "review_metrics_grade_a",
     "description": "ReviewMetrics with grade A values", "model": "ReviewMetrics",
     "data": {"actionability_score": 90.0, "discipline_score": 85.0, "final_review_grade": "A"}},
    {**_F, "id": "PC204-F011", "fixture_id": "PC204-F011", "name": "review_metrics_grade_b",
     "description": "ReviewMetrics with grade B values", "model": "ReviewMetrics",
     "data": {"actionability_score": 70.0, "discipline_score": 68.0, "final_review_grade": "B"}},
    {**_F, "id": "PC204-F012", "fixture_id": "PC204-F012", "name": "review_metrics_grade_d",
     "description": "ReviewMetrics with grade D values", "model": "ReviewMetrics",
     "data": {"actionability_score": 30.0, "discipline_score": 40.0, "final_review_grade": "D"}},
    {**_F, "id": "PC204-F013", "fixture_id": "PC204-F013", "name": "weekly_pack_default",
     "description": "Default WeeklyImprovementPack", "model": "WeeklyImprovementPack",
     "data": {"week_id": "test-wk", "should_auto_apply": False}},
    {**_F, "id": "PC204-F014", "fixture_id": "PC204-F014", "name": "weekly_pack_with_decisions",
     "description": "WeeklyImprovementPack with multiple decisions", "model": "WeeklyImprovementPack",
     "data": {"reviewed_decision_count": 10, "reviewed_candidate_count": 20, "should_auto_apply": False}},
    {**_F, "id": "PC204-F015", "fixture_id": "PC204-F015", "name": "blocked_reason_review_default",
     "description": "Default BlockedReasonReview", "model": "BlockedReasonReview",
     "data": {"total_blocked": 0}},
    {**_F, "id": "PC204-F016", "fixture_id": "PC204-F016", "name": "blocked_reason_review_with_blocks",
     "description": "BlockedReasonReview with common blocks", "model": "BlockedReasonReview",
     "data": {"total_blocked": 5, "most_common_reasons": ["low_score", "high_risk"]}},
    {**_F, "id": "PC204-F017", "fixture_id": "PC204-F017", "name": "risk_usage_review_default",
     "description": "Default RiskUsageReview", "model": "RiskUsageReview",
     "data": {"total_risk_budget_pct": 20.0, "used_risk_pct": 0.0}},
    {**_F, "id": "PC204-F018", "fixture_id": "PC204-F018", "name": "risk_usage_review_high_usage",
     "description": "RiskUsageReview near budget limit", "model": "RiskUsageReview",
     "data": {"total_risk_budget_pct": 20.0, "used_risk_pct": 18.0}},
    {**_F, "id": "PC204-F019", "fixture_id": "PC204-F019", "name": "strategy_profile_review_balanced",
     "description": "StrategyProfileReview with balanced profile", "model": "StrategyProfileReview",
     "data": {"profile_id": "P001", "entry_style": "balanced", "total_decisions": 10}},
    {**_F, "id": "PC204-F020", "fixture_id": "PC204-F020", "name": "strategy_profile_review_conservative",
     "description": "StrategyProfileReview with conservative profile", "model": "StrategyProfileReview",
     "data": {"profile_id": "P002", "entry_style": "conservative", "total_decisions": 5}},
    {**_F, "id": "PC204-F021", "fixture_id": "PC204-F021", "name": "portfolio_review_result_default",
     "description": "Default PortfolioReviewResult", "model": "PortfolioReviewResult",
     "data": {"review_version": "2.0.4", "all_passed": True}},
    {**_F, "id": "PC204-F022", "fixture_id": "PC204-F022", "name": "review_export_json_valid",
     "description": "ReviewExportResult with json format", "model": "ReviewExportResult",
     "data": {"export_format": "json", "is_valid": True}},
    {**_F, "id": "PC204-F023", "fixture_id": "PC204-F023", "name": "review_export_markdown_valid",
     "description": "ReviewExportResult with markdown format", "model": "ReviewExportResult",
     "data": {"export_format": "markdown", "is_valid": True}},
    {**_F, "id": "PC204-F024", "fixture_id": "PC204-F024", "name": "review_export_csv_valid",
     "description": "ReviewExportResult with csv format", "model": "ReviewExportResult",
     "data": {"export_format": "csv", "is_valid": True}},
    {**_F, "id": "PC204-F025", "fixture_id": "PC204-F025", "name": "review_audit_snapshot_default",
     "description": "Default ReviewAuditSnapshot", "model": "ReviewAuditSnapshot",
     "data": {"export_format": "audit_snapshot", "export_status": "complete"}},
    {**_F, "id": "PC204-F026", "fixture_id": "PC204-F026", "name": "review_audit_snapshot_with_hash",
     "description": "ReviewAuditSnapshot with reproducibility_hash", "model": "ReviewAuditSnapshot",
     "data": {"reproducibility_hash": "abc123def456"}},
    {**_F, "id": "PC204-F027", "fixture_id": "PC204-F027", "name": "v204_health_summary_default",
     "description": "Default V204HealthSummary", "model": "V204HealthSummary",
     "data": {"version": "2.0.4", "all_passed": False}},
    {**_F, "id": "PC204-F028", "fixture_id": "PC204-F028", "name": "v204_health_summary_all_passed",
     "description": "V204HealthSummary with all_passed=True", "model": "V204HealthSummary",
     "data": {"version": "2.0.4", "all_passed": True, "passed": 50, "failed": 0}},
    {**_F, "id": "PC204-F029", "fixture_id": "PC204-F029", "name": "v204_release_summary_default",
     "description": "Default V204ReleaseSummary", "model": "V204ReleaseSummary",
     "data": {"version": "2.0.4", "all_sealed": False}},
    {**_F, "id": "PC204-F030", "fixture_id": "PC204-F030", "name": "safety_flags_all_true",
     "description": "All SAFETY_FLAGS_V204 positive flags are True", "model": "safety_flags",
     "data": {"paper_only": True, "no_real_orders": True, "broker_execution_disabled": True}},
    {**_F, "id": "PC204-F031", "fixture_id": "PC204-F031", "name": "portfolio_review_two_profiles",
     "description": "Portfolio review with two strategy profiles", "model": "PortfolioReviewInput",
     "data": {"strategy_profile_ids": ["P001", "P002"], "review_period": "2026-W30"}},
    {**_F, "id": "PC204-F032", "fixture_id": "PC204-F032", "name": "recommendation_add_rule",
     "description": "ImprovementRecommendation with add_rule category", "model": "ImprovementRecommendation",
     "data": {"category": "add_rule", "severity": "low", "should_auto_apply": False}},
    {**_F, "id": "PC204-F033", "fixture_id": "PC204-F033", "name": "recommendation_reduce_rule",
     "description": "ImprovementRecommendation with reduce_rule category", "model": "ImprovementRecommendation",
     "data": {"category": "reduce_rule", "severity": "medium", "should_auto_apply": False}},
    {**_F, "id": "PC204-F034", "fixture_id": "PC204-F034", "name": "recommendation_simulation",
     "description": "ImprovementRecommendation with simulation category", "model": "ImprovementRecommendation",
     "data": {"category": "simulation", "severity": "low", "should_auto_apply": False}},
    {**_F, "id": "PC204-F035", "fixture_id": "PC204-F035", "name": "recommendation_reporting",
     "description": "ImprovementRecommendation with reporting category", "model": "ImprovementRecommendation",
     "data": {"category": "reporting", "severity": "low", "should_auto_apply": False}},
    {**_F, "id": "PC204-F036", "fixture_id": "PC204-F036", "name": "portfolio_review_with_risk_usage",
     "description": "Portfolio review input with risk usage data", "model": "PortfolioReviewInput",
     "data": {"risk_usage_summary": {"total_risk_budget_pct": 20.0, "used_risk_pct": 10.0}}},
    {**_F, "id": "PC204-F037", "fixture_id": "PC204-F037", "name": "portfolio_review_with_blocks",
     "description": "Portfolio review with blocked reason summary", "model": "PortfolioReviewInput",
     "data": {"blocked_reason_summary": ["low_score", "high_risk", "market_regime"]}},
    {**_F, "id": "PC204-F038", "fixture_id": "PC204-F038", "name": "weekly_pack_with_top_setups",
     "description": "WeeklyImprovementPack with top working setups", "model": "WeeklyImprovementPack",
     "data": {"top_working_setups": ["abc_pullback", "breakout"], "should_auto_apply": False}},
    {**_F, "id": "PC204-F039", "fixture_id": "PC204-F039", "name": "weekly_pack_with_no_entry_reasons",
     "description": "WeeklyImprovementPack with no-entry reasons", "model": "WeeklyImprovementPack",
     "data": {"most_common_no_entry_reasons": ["low_score", "high_risk"], "should_auto_apply": False}},
    {**_F, "id": "PC204-F040", "fixture_id": "PC204-F040", "name": "weekly_pack_do_not_change_rules",
     "description": "WeeklyImprovementPack with do_not_change_rules", "model": "WeeklyImprovementPack",
     "data": {"do_not_change_rules": ["core_abc_rules", "risk_budget_hard_limit"], "should_auto_apply": False}},
    {**_F, "id": "PC204-F041", "fixture_id": "PC204-F041", "name": "weekly_pack_human_review_items",
     "description": "WeeklyImprovementPack with human review required items", "model": "WeeklyImprovementPack",
     "data": {"human_review_required_items": ["any_rule_change"], "should_auto_apply": False}},
    {**_F, "id": "PC204-F042", "fixture_id": "PC204-F042", "name": "risk_usage_review_zero_positions",
     "description": "RiskUsageReview with zero positions", "model": "RiskUsageReview",
     "data": {"position_count": 0, "used_risk_pct": 0.0}},
    {**_F, "id": "PC204-F043", "fixture_id": "PC204-F043", "name": "risk_usage_review_five_positions",
     "description": "RiskUsageReview with five positions", "model": "RiskUsageReview",
     "data": {"position_count": 5, "used_risk_pct": 15.0}},
    {**_F, "id": "PC204-F044", "fixture_id": "PC204-F044", "name": "blocked_reason_review_one_block",
     "description": "BlockedReasonReview with one unique block reason", "model": "BlockedReasonReview",
     "data": {"total_blocked": 1, "most_common_reasons": ["low_score"]}},
    {**_F, "id": "PC204-F045", "fixture_id": "PC204-F045", "name": "blocked_reason_review_five_blocks",
     "description": "BlockedReasonReview with five block reasons", "model": "BlockedReasonReview",
     "data": {"total_blocked": 5, "most_common_reasons": ["low_score", "high_risk", "market_regime", "volume", "chip"]}},
    {**_F, "id": "PC204-F046", "fixture_id": "PC204-F046", "name": "review_metrics_c_grade",
     "description": "ReviewMetrics with C grade", "model": "ReviewMetrics",
     "data": {"actionability_score": 55.0, "discipline_score": 55.0, "final_review_grade": "C"}},
    {**_F, "id": "PC204-F047", "fixture_id": "PC204-F047", "name": "strategy_profile_review_aggressive",
     "description": "StrategyProfileReview with aggressive profile", "model": "StrategyProfileReview",
     "data": {"profile_id": "P003", "entry_style": "aggressive", "total_decisions": 15}},
    {**_F, "id": "PC204-F048", "fixture_id": "PC204-F048", "name": "strategy_profile_review_no_blocks",
     "description": "StrategyProfileReview with no blocked decisions", "model": "StrategyProfileReview",
     "data": {"total_decisions": 5, "blocked_count": 0, "allowed_count": 5}},
    {**_F, "id": "PC204-F049", "fixture_id": "PC204-F049", "name": "strategy_profile_review_all_blocked",
     "description": "StrategyProfileReview with all decisions blocked", "model": "StrategyProfileReview",
     "data": {"total_decisions": 5, "blocked_count": 5, "allowed_count": 0}},
    {**_F, "id": "PC204-F050", "fixture_id": "PC204-F050", "name": "export_audit_snapshot_hash_present",
     "description": "ReviewAuditSnapshot with non-empty hash", "model": "ReviewAuditSnapshot",
     "data": {"reproducibility_hash": "deadbeef12345678"}},
    {**_F, "id": "PC204-F051", "fixture_id": "PC204-F051", "name": "portfolio_review_week_29",
     "description": "Portfolio review for week 29 of 2026", "model": "PortfolioReviewInput",
     "data": {"review_period": "2026-W29", "strategy_profile_ids": ["P001"]}},
    {**_F, "id": "PC204-F052", "fixture_id": "PC204-F052", "name": "portfolio_review_week_30",
     "description": "Portfolio review for week 30 of 2026", "model": "PortfolioReviewInput",
     "data": {"review_period": "2026-W30", "strategy_profile_ids": ["P001", "P002"]}},
    {**_F, "id": "PC204-F053", "fixture_id": "PC204-F053", "name": "weekly_pack_simulation_gap",
     "description": "WeeklyImprovementPack with simulation_vs_decision_gap", "model": "WeeklyImprovementPack",
     "data": {"simulation_vs_decision_gap": {"simulation_decision_count": 5, "actual_decision_count": 3}, "should_auto_apply": False}},
    {**_F, "id": "PC204-F054", "fixture_id": "PC204-F054", "name": "weekly_pack_risk_findings",
     "description": "WeeklyImprovementPack with risk budget findings", "model": "WeeklyImprovementPack",
     "data": {"risk_budget_findings": ["risk_budget_near_limit"], "should_auto_apply": False}},
    {**_F, "id": "PC204-F055", "fixture_id": "PC204-F055", "name": "weekly_pack_sizing_findings",
     "description": "WeeklyImprovementPack with position sizing findings", "model": "WeeklyImprovementPack",
     "data": {"position_sizing_findings": ["position_sizing_within_policy"], "should_auto_apply": False}},
    {**_F, "id": "PC204-F056", "fixture_id": "PC204-F056", "name": "portfolio_review_with_simulation",
     "description": "Portfolio review with simulation snapshot", "model": "PortfolioReviewInput",
     "data": {"simulation_snapshot": ["SIM-001", "SIM-002", "SIM-003"]}},
    {**_F, "id": "PC204-F057", "fixture_id": "PC204-F057", "name": "recommendation_critical_severity",
     "description": "ImprovementRecommendation with critical severity", "model": "ImprovementRecommendation",
     "data": {"category": "risk_budget", "severity": "critical", "should_auto_apply": False}},
    {**_F, "id": "PC204-F058", "fixture_id": "PC204-F058", "name": "recommendation_high_severity",
     "description": "ImprovementRecommendation with high severity", "model": "ImprovementRecommendation",
     "data": {"category": "exit_rule", "severity": "high", "should_auto_apply": False}},
    {**_F, "id": "PC204-F059", "fixture_id": "PC204-F059", "name": "portfolio_review_paper_only_true",
     "description": "PortfolioReviewResult has paper_only=True", "model": "PortfolioReviewResult",
     "data": {"paper_only": True, "no_real_orders": True}},
    {**_F, "id": "PC204-F060", "fixture_id": "PC204-F060", "name": "portfolio_review_no_broker_true",
     "description": "PortfolioReviewResult has no_broker=True", "model": "PortfolioReviewResult",
     "data": {"no_broker": True, "not_investment_advice": True}},
    {**_F, "id": "PC204-F061", "fixture_id": "PC204-F061", "name": "review_export_audit_valid",
     "description": "ReviewExportResult with audit_snapshot format", "model": "ReviewExportResult",
     "data": {"export_format": "audit_snapshot", "is_valid": True}},
    {**_F, "id": "PC204-F062", "fixture_id": "PC204-F062", "name": "risk_usage_over_budget",
     "description": "RiskUsageReview with risk usage over budget", "model": "RiskUsageReview",
     "data": {"total_risk_budget_pct": 20.0, "used_risk_pct": 22.0, "position_sizing_findings": ["position_sizing_over_budget"]}},
    {**_F, "id": "PC204-F063", "fixture_id": "PC204-F063", "name": "portfolio_review_all_passed_true",
     "description": "PortfolioReviewResult has all_passed=True", "model": "PortfolioReviewResult",
     "data": {"all_passed": True}},
    {**_F, "id": "PC204-F064", "fixture_id": "PC204-F064", "name": "review_metrics_all_fields",
     "description": "ReviewMetrics with all 10 required fields", "model": "ReviewMetrics",
     "data": {"actionability_score": 75.0, "discipline_score": 70.0, "selectivity_score": 80.0,
              "risk_control_score": 85.0, "review_burden_score": 60.0, "missed_opportunity_score": 30.0,
              "false_positive_risk_score": 25.0, "no_entry_quality_score": 88.0,
              "strategy_improvement_score": 72.0, "final_review_grade": "B"}},
    {**_F, "id": "PC204-F065", "fixture_id": "PC204-F065", "name": "weekly_pack_with_review_metrics",
     "description": "WeeklyImprovementPack with embedded ReviewMetrics", "model": "WeeklyImprovementPack",
     "data": {"reviewed_decision_count": 8, "should_auto_apply": False}},
    {**_F, "id": "PC204-F066", "fixture_id": "PC204-F066", "name": "strategy_profile_review_with_gap",
     "description": "StrategyProfileReview with simulation_vs_decision_gap", "model": "StrategyProfileReview",
     "data": {"simulation_vs_decision_gap": {"simulation_allowed": 5, "actual_decisions": 3, "gap_pct": 0.4}}},
    {**_F, "id": "PC204-F067", "fixture_id": "PC204-F067", "name": "review_audit_safety_snapshot",
     "description": "ReviewAuditSnapshot with safety snapshot", "model": "ReviewAuditSnapshot",
     "data": {"safety_snapshot": "NO_REAL_ORDERS=True|BROKER_EXECUTION_ENABLED=False|PRODUCTION_TRADING_BLOCKED=True"}},
    {**_F, "id": "PC204-F068", "fixture_id": "PC204-F068", "name": "portfolio_review_multiple_decisions",
     "description": "Portfolio review with 5 decisions", "model": "PortfolioReviewInput",
     "data": {"decision_snapshot": ["2330", "2317", "2454", "3008", "2603"]}},
    {**_F, "id": "PC204-F069", "fixture_id": "PC204-F069", "name": "recommendation_target_rule",
     "description": "ImprovementRecommendation with target_rule set", "model": "ImprovementRecommendation",
     "data": {"target_rule": "entry_score_threshold", "should_auto_apply": False}},
    {**_F, "id": "PC204-F070", "fixture_id": "PC204-F070", "name": "weekly_pack_three_profiles",
     "description": "WeeklyImprovementPack with 3 reviewed profiles", "model": "WeeklyImprovementPack",
     "data": {"reviewed_strategy_profile_count": 3, "should_auto_apply": False}},
    {**_F, "id": "PC204-F071", "fixture_id": "PC204-F071", "name": "portfolio_review_result_schema_204",
     "description": "PortfolioReviewResult has schema_version 204", "model": "PortfolioReviewResult",
     "data": {"schema_version": "204"}},
    {**_F, "id": "PC204-F072", "fixture_id": "PC204-F072", "name": "blocked_reason_review_actionable",
     "description": "BlockedReasonReview with actionable blocks", "model": "BlockedReasonReview",
     "data": {"actionable_blocks": ["score_threshold_adjustable"], "non_actionable_blocks": ["market_closed"]}},
    {**_F, "id": "PC204-F073", "fixture_id": "PC204-F073", "name": "blocked_reason_review_with_recs",
     "description": "BlockedReasonReview with improvement recommendations", "model": "BlockedReasonReview",
     "data": {"total_blocked": 3}},
    {**_F, "id": "PC204-F074", "fixture_id": "PC204-F074", "name": "strategy_profile_review_top_setups",
     "description": "StrategyProfileReview with top working setups", "model": "StrategyProfileReview",
     "data": {"top_working_setups": ["abc_pullback", "breakout"]}},
    {**_F, "id": "PC204-F075", "fixture_id": "PC204-F075", "name": "strategy_profile_review_weak_setups",
     "description": "StrategyProfileReview with weakest setups", "model": "StrategyProfileReview",
     "data": {"weakest_setups": ["low_volume_entry"]}},
    {**_F, "id": "PC204-F076", "fixture_id": "PC204-F076", "name": "review_export_json_no_auto_apply",
     "description": "ReviewExportResult JSON content contains should_auto_apply false", "model": "ReviewExportResult",
     "data": {"export_format": "json", "is_valid": True}},
    {**_F, "id": "PC204-F077", "fixture_id": "PC204-F077", "name": "portfolio_review_human_review_required",
     "description": "PortfolioReviewInput has human_review_required=True", "model": "PortfolioReviewInput",
     "data": {"human_review_required": True}},
    {**_F, "id": "PC204-F078", "fixture_id": "PC204-F078", "name": "v204_release_summary_cli_11",
     "description": "V204ReleaseSummary has cli_count=11", "model": "V204ReleaseSummary",
     "data": {"cli_count": 11, "gui_tabs_count": 3, "models_count": 12}},
    {**_F, "id": "PC204-F079", "fixture_id": "PC204-F079", "name": "weekly_pack_suggested_adjustments",
     "description": "WeeklyImprovementPack with suggested_rule_adjustments", "model": "WeeklyImprovementPack",
     "data": {"suggested_rule_adjustments": [], "should_auto_apply": False}},
    {**_F, "id": "PC204-F080", "fixture_id": "PC204-F080", "name": "recommendation_requires_human_approval_true",
     "description": "ImprovementRecommendation has requires_human_approval=True", "model": "ImprovementRecommendation",
     "data": {"requires_human_approval": True, "should_auto_apply": False}},
]

assert len(FIXTURES) == 80, f"Expected 80 fixtures, got {len(FIXTURES)}"
assert len({f["id"] for f in FIXTURES}) == 80, "Duplicate fixture IDs in FIXTURES"
assert all(f["schema_version"] == "204" for f in FIXTURES), "Bad schema_version in FIXTURES"
assert all(f["paper_only"] is True for f in FIXTURES), "Missing paper_only in FIXTURES"
assert all("fixture_id" in f for f in FIXTURES), "Missing fixture_id in FIXTURES"
