"""
paper_trading/small_capital_strategy/paper_cockpit_fixtures_v205.py
v2.0.5 Paper Watchlist Rotation & Candidate Promotion Queue — Fixtures
[!] Paper Only. Research Only. No Real Orders. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List

_SCHEMA = "205"
_PAPER_ONLY = True
_NO_REAL_ORDERS = True


def _f(n: int, name: str, model: str, data: Dict[str, Any]) -> Dict[str, Any]:
    fid = f"PC205-F{n:03d}"
    return {
        "id": fid,
        "fixture_id": fid,
        "schema_version": _SCHEMA,
        "paper_only": _PAPER_ONLY,
        "no_real_orders": _NO_REAL_ORDERS,
        "name": name,
        "model": model,
        "data": data,
    }


FIXTURES: List[Dict[str, Any]] = [
    # --- WatchlistRotationInput fixtures (1-10) ---
    _f(1,  "default_rotation_input",           "WatchlistRotationInput",
       {"rotation_period": "2026-W29", "paper_only": True, "no_real_orders": True}),
    _f(2,  "rotation_input_with_items",        "WatchlistRotationInput",
       {"rotation_period": "2026-W30", "watchlist_items": ["2330", "2317"], "paper_only": True}),
    _f(3,  "rotation_input_empty_watchlist",   "WatchlistRotationInput",
       {"rotation_period": "2026-W29", "watchlist_items": [], "paper_only": True}),
    _f(4,  "rotation_input_with_review_pack",  "WatchlistRotationInput",
       {"rotation_period": "2026-W29", "review_pack_ids": ["R001", "R002"], "paper_only": True}),
    _f(5,  "rotation_input_with_sim_ranking",  "WatchlistRotationInput",
       {"rotation_period": "2026-W29", "simulation_ranking_ids": ["SIM001"], "paper_only": True}),
    _f(6,  "rotation_input_low_risk_budget",   "WatchlistRotationInput",
       {"rotation_period": "2026-W29", "risk_budget_pct": 5.0, "paper_only": True}),
    _f(7,  "rotation_input_high_risk_budget",  "WatchlistRotationInput",
       {"rotation_period": "2026-W29", "risk_budget_pct": 30.0, "paper_only": True}),
    _f(8,  "rotation_input_with_profile",      "WatchlistRotationInput",
       {"rotation_period": "2026-W29", "strategy_profile_id": "P001", "paper_only": True}),
    _f(9,  "rotation_input_human_review",      "WatchlistRotationInput",
       {"rotation_period": "2026-W29", "human_review_required": True, "paper_only": True}),
    _f(10, "rotation_input_multi_period",      "WatchlistRotationInput",
       {"rotation_period": "2026-W31", "paper_only": True, "no_real_orders": True}),
    # --- WatchlistItem fixtures (11-25) ---
    _f(11, "watchlist_item_default",           "WatchlistItem",
       {"symbol": "", "current_status": "active_watchlist", "paper_only": True}),
    _f(12, "watchlist_item_2330_high_score",   "WatchlistItem",
       {"symbol": "2330", "score": 85.0, "trend_quality": 88.0, "paper_only": True}),
    _f(13, "watchlist_item_2317_mid_score",    "WatchlistItem",
       {"symbol": "2317", "score": 55.0, "trend_quality": 55.0, "paper_only": True}),
    _f(14, "watchlist_item_with_themes",       "WatchlistItem",
       {"symbol": "2454", "theme_tags": ["ai", "semiconductor"], "paper_only": True}),
    _f(15, "watchlist_item_with_no_entry",     "WatchlistItem",
       {"symbol": "2308", "no_entry_reasons": ["trend_broken", "below_20ma", "volume_dry_up_failed"], "paper_only": True}),
    _f(16, "watchlist_item_with_promo_reasons","WatchlistItem",
       {"symbol": "2382", "promotion_reasons": ["strong_trend", "volume_confirmation"], "paper_only": True}),
    _f(17, "watchlist_item_with_demotion",     "WatchlistItem",
       {"symbol": "2412", "demotion_reasons": ["weak_volume", "trend_broken"], "paper_only": True}),
    _f(18, "watchlist_item_human_review",      "WatchlistItem",
       {"symbol": "2303", "human_review_reasons": ["low_liquidity"], "paper_only": True}),
    _f(19, "watchlist_item_quarantine",        "WatchlistItem",
       {"symbol": "2603", "no_entry_reasons": ["trend_broken", "institutional_selling", "risk_budget_exceeded"], "paper_only": True}),
    _f(20, "watchlist_item_promoted_candidate","WatchlistItem",
       {"symbol": "3711", "current_status": "promoted_candidate", "paper_only": True}),
    _f(21, "watchlist_item_second_wave",       "WatchlistItem",
       {"symbol": "4938", "current_status": "second_wave_candidate", "paper_only": True}),
    _f(22, "watchlist_item_abc_pullback",      "WatchlistItem",
       {"symbol": "6669", "current_status": "abc_pullback_candidate", "paper_only": True}),
    _f(23, "watchlist_item_breakout_candidate","WatchlistItem",
       {"symbol": "2379", "current_status": "breakout_candidate", "paper_only": True}),
    _f(24, "watchlist_item_downgraded",        "WatchlistItem",
       {"symbol": "2474", "current_status": "downgraded", "paper_only": True}),
    _f(25, "watchlist_item_removed",           "WatchlistItem",
       {"symbol": "2357", "current_status": "removed", "paper_only": True}),
    # --- PromotionDecision fixtures (26-38) ---
    _f(26, "promotion_decision_default",       "PromotionDecision",
       {"should_auto_apply": False, "paper_only": True}),
    _f(27, "promotion_decision_auto_apply_always_false", "PromotionDecision",
       {"should_auto_apply": False, "symbol": "2330", "paper_only": True}),
    _f(28, "promotion_decision_promote",       "PromotionDecision",
       {"symbol": "2330", "from_status": "active_watchlist", "to_status": "promoted_candidate",
        "promotion_score": 82.0, "should_auto_apply": False, "paper_only": True}),
    _f(29, "promotion_decision_demote",        "PromotionDecision",
       {"symbol": "2317", "from_status": "active_watchlist", "to_status": "downgraded",
        "promotion_score": 25.0, "should_auto_apply": False, "paper_only": True}),
    _f(30, "promotion_decision_remove",        "PromotionDecision",
       {"symbol": "2308", "from_status": "active_watchlist", "to_status": "removed",
        "promotion_score": 10.0, "should_auto_apply": False, "paper_only": True}),
    _f(31, "promotion_decision_quarantine",    "PromotionDecision",
       {"symbol": "2412", "from_status": "active_watchlist", "to_status": "quarantined_no_entry",
        "blocked_reasons": ["trend_broken"], "should_auto_apply": False, "paper_only": True}),
    _f(32, "promotion_decision_human_review",  "PromotionDecision",
       {"symbol": "2303", "requires_human_review": True, "should_auto_apply": False, "paper_only": True}),
    _f(33, "promotion_decision_high_risk_score","PromotionDecision",
       {"symbol": "2382", "risk_score": 85.0, "should_auto_apply": False, "paper_only": True}),
    _f(34, "promotion_decision_with_reasons",  "PromotionDecision",
       {"symbol": "2330", "reason_codes": ["strong_trend", "volume_ok"],
        "should_auto_apply": False, "paper_only": True}),
    _f(35, "promotion_decision_chip_score",    "PromotionDecision",
       {"symbol": "3711", "chip_score": 75.0, "should_auto_apply": False, "paper_only": True}),
    _f(36, "promotion_decision_theme_score",   "PromotionDecision",
       {"symbol": "4938", "theme_score": 60.0, "should_auto_apply": False, "paper_only": True}),
    _f(37, "promotion_decision_technical_score","PromotionDecision",
       {"symbol": "6669", "technical_score": 78.0, "should_auto_apply": False, "paper_only": True}),
    _f(38, "promotion_decision_liquidity_score","PromotionDecision",
       {"symbol": "2379", "liquidity_score": 65.0, "should_auto_apply": False, "paper_only": True}),
    # --- QueueSummary fixtures (39-46) ---
    _f(39, "queue_summary_default",            "QueueSummary",
       {"total_watchlist_count": 0, "paper_only": True}),
    _f(40, "queue_summary_with_promotions",    "QueueSummary",
       {"total_watchlist_count": 10, "promote_count": 3, "keep_count": 5,
        "demote_count": 1, "remove_count": 1, "paper_only": True}),
    _f(41, "queue_summary_grade_a",            "QueueSummary",
       {"weekly_rotation_grade": "A", "avg_promotion_score": 85.0, "paper_only": True}),
    _f(42, "queue_summary_grade_b",            "QueueSummary",
       {"weekly_rotation_grade": "B", "avg_promotion_score": 70.0, "paper_only": True}),
    _f(43, "queue_summary_grade_c",            "QueueSummary",
       {"weekly_rotation_grade": "C", "avg_promotion_score": 55.0, "paper_only": True}),
    _f(44, "queue_summary_grade_d",            "QueueSummary",
       {"weekly_rotation_grade": "D", "avg_promotion_score": 30.0, "paper_only": True}),
    _f(45, "queue_summary_top_promo",          "QueueSummary",
       {"top_promotion_candidates": ["2330", "2317"], "paper_only": True}),
    _f(46, "queue_summary_quarantine_reasons", "QueueSummary",
       {"top_quarantine_reasons": ["trend_broken", "volume_dry_up_failed"], "paper_only": True}),
    # --- WatchlistRotationResult fixtures (47-54) ---
    _f(47, "rotation_result_default",          "WatchlistRotationResult",
       {"should_auto_apply": False, "paper_only": True}),
    _f(48, "rotation_result_all_passed",       "WatchlistRotationResult",
       {"all_passed": True, "should_auto_apply": False, "paper_only": True}),
    _f(49, "rotation_result_with_promotions",  "WatchlistRotationResult",
       {"all_passed": True, "should_auto_apply": False, "rotation_version": "2.0.5", "paper_only": True}),
    _f(50, "rotation_result_paper_safety",     "WatchlistRotationResult",
       {"paper_only_safety_snapshot": True, "should_auto_apply": False, "paper_only": True}),
    _f(51, "rotation_result_human_review",     "WatchlistRotationResult",
       {"human_review_required": True, "should_auto_apply": False, "paper_only": True}),
    _f(52, "rotation_result_no_broker",        "WatchlistRotationResult",
       {"no_broker": True, "should_auto_apply": False, "paper_only": True}),
    _f(53, "rotation_result_research_only",    "WatchlistRotationResult",
       {"research_only": True, "should_auto_apply": False, "paper_only": True}),
    _f(54, "rotation_result_rotation_only",    "WatchlistRotationResult",
       {"rotation_only": True, "should_auto_apply": False, "paper_only": True}),
    # --- RotationExportResult fixtures (55-60) ---
    _f(55, "export_result_json",               "RotationExportResult",
       {"export_format": "json", "is_valid": True, "paper_only": True}),
    _f(56, "export_result_markdown",           "RotationExportResult",
       {"export_format": "markdown", "is_valid": True, "paper_only": True}),
    _f(57, "export_result_csv",                "RotationExportResult",
       {"export_format": "csv", "is_valid": True, "paper_only": True}),
    _f(58, "export_result_audit",              "RotationExportResult",
       {"export_format": "audit_snapshot", "is_valid": True, "paper_only": True}),
    _f(59, "export_result_paper_confirmed",    "RotationExportResult",
       {"paper_only_confirmed": True, "paper_only": True}),
    _f(60, "export_result_complete_status",    "RotationExportResult",
       {"export_status": "complete", "is_valid": True, "paper_only": True}),
    # --- RotationAuditSnapshot fixtures (61-65) ---
    _f(61, "audit_snapshot_default",           "RotationAuditSnapshot",
       {"paper_only": True, "export_format": "audit_snapshot"}),
    _f(62, "audit_snapshot_with_hash",         "RotationAuditSnapshot",
       {"reproducibility_hash": "abc123", "paper_only": True}),
    _f(63, "audit_snapshot_safety_info",       "RotationAuditSnapshot",
       {"safety_snapshot": "paper_only=True;no_real_orders=True", "paper_only": True}),
    _f(64, "audit_snapshot_complete",          "RotationAuditSnapshot",
       {"export_status": "complete", "paper_only": True}),
    _f(65, "audit_snapshot_with_metadata",     "RotationAuditSnapshot",
       {"run_metadata": "v2.0.5-rotation-test", "paper_only": True}),
    # --- PromotionQueueCSV fixtures (66-68) ---
    _f(66, "promo_csv_default",                "PromotionQueueCSV",
       {"is_valid": False, "row_count": 0, "paper_only": True}),
    _f(67, "promo_csv_valid",                  "PromotionQueueCSV",
       {"is_valid": True, "row_count": 3, "paper_only": True}),
    _f(68, "promo_csv_with_content",           "PromotionQueueCSV",
       {"csv_content": "symbol,from_status,to_status\n2330,active_watchlist,promoted_candidate",
        "is_valid": True, "paper_only": True}),
    # --- DemotionQueueCSV fixtures (69-71) ---
    _f(69, "demo_csv_default",                 "DemotionQueueCSV",
       {"is_valid": False, "row_count": 0, "paper_only": True}),
    _f(70, "demo_csv_valid",                   "DemotionQueueCSV",
       {"is_valid": True, "row_count": 2, "paper_only": True}),
    _f(71, "demo_csv_with_content",            "DemotionQueueCSV",
       {"csv_content": "symbol,from_status,to_status\n2317,active_watchlist,downgraded",
        "is_valid": True, "paper_only": True}),
    # --- V205HealthSummary / V205ReleaseSummary fixtures (72-75) ---
    _f(72, "health_summary_default",           "V205HealthSummary",
       {"version": "2.0.5", "paper_only": True}),
    _f(73, "health_summary_all_passed",        "V205HealthSummary",
       {"all_passed": True, "version": "2.0.5", "paper_only": True}),
    _f(74, "release_summary_default",          "V205ReleaseSummary",
       {"version": "2.0.5", "paper_only": True}),
    _f(75, "release_summary_not_sealed",       "V205ReleaseSummary",
       {"version": "2.0.5", "all_sealed": False, "paper_only": True}),
    # --- WatchlistRotationReport fixtures (76-78) ---
    _f(76, "rotation_report_default",          "WatchlistRotationReport",
       {"paper_only": True, "is_valid": False}),
    _f(77, "rotation_report_valid",            "WatchlistRotationReport",
       {"paper_only": True, "is_valid": True, "section_count": 3}),
    _f(78, "rotation_report_with_content",     "WatchlistRotationReport",
       {"paper_only": True, "is_valid": True, "report_content": "# Watchlist Rotation Report v2.0.5"}),
    # --- safety guard fixtures (79-80) ---
    _f(79, "safety_guard_paper_only",          "SAFETY",
       {"paper_only": True, "no_real_orders": True, "should_auto_apply": False,
        "broker_execution_disabled": True, "production_trading_blocked": True}),
    _f(80, "safety_guard_backward_compat",     "SAFETY",
       {"backward_compat_v204": True, "v204_version": "2.0.4", "paper_only": True}),
]

assert len(FIXTURES) == 80, f"Expected 80 fixtures, got {len(FIXTURES)}"
