"""
paper_trading/small_capital_strategy/portfolio_risk_report_scenarios_v199.py
v1.9.9 Paper Portfolio Risk Report & Position Sizing Policy Lab — Scenarios
[!] Paper Only. Research Only. Position Sizing Policy Only. Portfolio Risk Report Only.
[!] No Real Orders. Not Investment Advice.
"""
from __future__ import annotations
from typing import List, Dict, Any

_BASE = {
    "schema_version": "199",
    "paper_only": True,
    "research_only": True,
    "simulate_only": True,
    "validation_only": True,
    "portfolio_risk_report_only": True,
    "position_sizing_policy_only": True,
    "dashboard_only": True,
    "report_only": True,
    "audit_only": True,
    "no_real_orders": True,
    "no_broker": True,
    "no_margin": True,
    "no_leverage": True,
    "no_production_strategy_mutation": True,
    "no_automatic_rollback": True,
    "no_live_strategy_activation": True,
    "no_real_portfolio_rebalancing": True,
    "not_investment_advice": True,
    "demo_only": True,
    "not_for_production": True,
    "production_trading_blocked": True,
}

_SCENARIOS: List[Dict[str, Any]] = [
    {
        **_BASE,
        "id": "PRR199-001",
        "scenario_id": "PRR199-001",
        "name": "300k capital profile — default parameters verified",
        "description": "Verify the 300k capital profile has correct risk limits: normal risk 0.8%–1.5%, max loss $2,400–$4,500, cash buffer 5%, symbol max 20%, theme max 35%, industry max 40%.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-002",
        "scenario_id": "PRR199-002",
        "name": "A buy point normal sizing — low risk grade",
        "description": "A_PULLBACK_10MA entry with portfolio risk grade LOW, stop 5%, cash 20%. Expect full 1.0x size multiplier and ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-003",
        "scenario_id": "PRR199-003",
        "name": "A buy point normal sizing — moderate risk grade",
        "description": "A_PULLBACK_10MA entry with portfolio risk grade MODERATE. Still within threshold for normal sizing. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-004",
        "scenario_id": "PRR199-004",
        "name": "A buy point reduced sizing — elevated risk grade",
        "description": "A_PULLBACK_10MA entry with portfolio risk grade ELEVATED. Risk grade triggers size reduction. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-005",
        "scenario_id": "PRR199-005",
        "name": "A buy point blocked — high risk grade",
        "description": "A_PULLBACK_10MA entry with portfolio risk grade HIGH. Hard block triggered. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-006",
        "scenario_id": "PRR199-006",
        "name": "A buy point blocked — critical risk grade",
        "description": "A_PULLBACK_10MA entry with portfolio risk grade CRITICAL. Maximum severity block. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-007",
        "scenario_id": "PRR199-007",
        "name": "B breakout reduced sizing — 0.7x multiplier low risk",
        "description": "B_BREAKOUT_BASE entry at low risk grade. Size multiplier 0.7x. Expect ALLOW_REDUCED_SIZE because multiplier < 1.0.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-008",
        "scenario_id": "PRR199-008",
        "name": "B breakout reduced sizing — 0.7x multiplier moderate risk",
        "description": "B_BREAKOUT_BASE entry at moderate portfolio risk grade. Multiplier 0.7x still applies. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-009",
        "scenario_id": "PRR199-009",
        "name": "B breakout blocked — elevated risk grade",
        "description": "B_BREAKOUT_BASE entry at elevated portfolio risk grade. Elevated triggers size cap, already at 0.7x reduced. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-010",
        "scenario_id": "PRR199-010",
        "name": "B breakout blocked — high risk grade no entry",
        "description": "B_BREAKOUT_BASE entry with portfolio risk grade HIGH. No new entries allowed at high risk. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-011",
        "scenario_id": "PRR199-011",
        "name": "C reclaim 20MA half sizing — 0.5x multiplier low risk",
        "description": "C_RECLAIM_20MA entry at low portfolio risk grade. Multiplier 0.5x applied. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "C_RECLAIM_20MA",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-012",
        "scenario_id": "PRR199-012",
        "name": "C reclaim 20MA half sizing — moderate risk grade",
        "description": "C_RECLAIM_20MA entry at moderate portfolio risk. Multiplier 0.5x. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "C_RECLAIM_20MA",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-013",
        "scenario_id": "PRR199-013",
        "name": "C reclaim 20MA blocked — high risk grade",
        "description": "C_RECLAIM_20MA entry at high portfolio risk grade. Block overrides entry type. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "C_RECLAIM_20MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-014",
        "scenario_id": "PRR199-014",
        "name": "Test position sizing — 0.3x multiplier probe entry",
        "description": "TEST_POSITION entry type. Multiplier 0.3x at low risk grade. Expect TEST_POSITION_ONLY.",
        "entry_type": "TEST_POSITION",
        "expected_recommendation": "TEST_POSITION_ONLY",
    },
    {
        **_BASE,
        "id": "PRR199-015",
        "scenario_id": "PRR199-015",
        "name": "Test position sizing — 0.3x probe at moderate risk",
        "description": "TEST_POSITION entry at moderate portfolio risk grade. Expect TEST_POSITION_ONLY with 0.3x multiplier.",
        "entry_type": "TEST_POSITION",
        "expected_recommendation": "TEST_POSITION_ONLY",
    },
    {
        **_BASE,
        "id": "PRR199-016",
        "scenario_id": "PRR199-016",
        "name": "Add position sizing — 0.5x multiplier with unrealized gain",
        "description": "ADD_POSITION entry type with existing unrealized gain. Multiplier 0.5x. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "ADD_POSITION",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-017",
        "scenario_id": "PRR199-017",
        "name": "Reduce position — no new entry allowed",
        "description": "REDUCE_POSITION entry type. Multiplier 0.0x. No new position established. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "REDUCE_POSITION",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-018",
        "scenario_id": "PRR199-018",
        "name": "No entry condition — blocked at 0.0x",
        "description": "NO_ENTRY entry type. Multiplier 0.0x. Always blocked. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "NO_ENTRY",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-019",
        "scenario_id": "PRR199-019",
        "name": "Stop distance too wide — 20% stop blocks entry",
        "description": "Stop distance 20% exceeds 15% maximum threshold. Entry blocked regardless of entry type. Expect REQUIRE_TIGHTER_STOP.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "REQUIRE_TIGHTER_STOP",
    },
    {
        **_BASE,
        "id": "PRR199-020",
        "scenario_id": "PRR199-020",
        "name": "Stop distance too wide — 18% stop blocks B breakout",
        "description": "B_BREAKOUT_BASE with 18% stop distance. Exceeds 15% threshold. Expect REQUIRE_TIGHTER_STOP.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "REQUIRE_TIGHTER_STOP",
    },
    {
        **_BASE,
        "id": "PRR199-021",
        "scenario_id": "PRR199-021",
        "name": "Stop distance missing — entry blocked",
        "description": "No stop distance provided (None or zero). Missing stop blocks sizing calculation. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-022",
        "scenario_id": "PRR199-022",
        "name": "Max single trade loss at $2,400 — minimum loss scenario",
        "description": "300k capital, 0.8% risk pct, stop 5%. Max loss = $2,400 minimum boundary. Position size = $48,000. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-023",
        "scenario_id": "PRR199-023",
        "name": "Max single trade loss at $4,500 — maximum normal loss",
        "description": "300k capital, 1.5% risk pct, stop 5%. Max loss = $4,500 maximum normal boundary. Position size = $90,000. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-024",
        "scenario_id": "PRR199-024",
        "name": "Theme exposure exceeded — AI supply chain blocks entry",
        "description": "AI supply chain theme currently at 38% (exceeds 35% max). New candidate in same theme. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-025",
        "scenario_id": "PRR199-025",
        "name": "Theme exposure exceeded — semiconductor AI theme saturated",
        "description": "Semiconductor AI theme at 40% (exceeds 35% max). Candidate in same theme blocked. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-026",
        "scenario_id": "PRR199-026",
        "name": "Theme exposure at limit — exactly 35% triggers block",
        "description": "Theme at exactly 35% weight (max_single_theme_weight). Adds candidate in same theme. Block triggered at boundary. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-027",
        "scenario_id": "PRR199-027",
        "name": "Theme exposure under limit — 30% allows entry",
        "description": "Theme at 30% weight (below 35% max). Candidate in same theme allowed with normal sizing. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-028",
        "scenario_id": "PRR199-028",
        "name": "Industry exposure exceeded — reduces position size",
        "description": "Semiconductor industry at 42% (exceeds 40% max). Candidate in same industry. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-029",
        "scenario_id": "PRR199-029",
        "name": "Industry exposure at limit — exactly 40% reduces size",
        "description": "Industry at exactly 40% weight. Boundary condition reduces size. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-030",
        "scenario_id": "PRR199-030",
        "name": "Cash buffer too low — 2% cash blocks new entry",
        "description": "Current cash at 2% (below 5% minimum). Cash buffer condition triggered. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-031",
        "scenario_id": "PRR199-031",
        "name": "Cash buffer too low — 4% cash below 5% minimum",
        "description": "Current cash at 4%, just below 5% minimum buffer. Block triggered. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-032",
        "scenario_id": "PRR199-032",
        "name": "Cash buffer at minimum — exactly 5% allows entry",
        "description": "Current cash exactly at 5% minimum buffer. Boundary condition allows entry. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-033",
        "scenario_id": "PRR199-033",
        "name": "Weak market cash 50 percent mode — 30% cash blocks new entry",
        "description": "Market risk-off active, weak market mode requires 50% cash buffer. Current cash 30%. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-034",
        "scenario_id": "PRR199-034",
        "name": "Weak market cash 50 percent mode — 49% cash blocked",
        "description": "Weak market mode with 49% cash (below 50% required). Block triggered just below boundary. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-035",
        "scenario_id": "PRR199-035",
        "name": "Weak market cash 50 percent mode — exactly 50% cash allows",
        "description": "Weak market mode with exactly 50% cash (at boundary). Cash buffer satisfied. Expect RISK_OFF_MODE (market_risk_off still blocks).",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "RISK_OFF_MODE",
    },
    {
        **_BASE,
        "id": "PRR199-036",
        "scenario_id": "PRR199-036",
        "name": "High correlation cluster reduces size — 46% cluster weight",
        "description": "High correlation cluster (AI infrastructure) at 46% (exceeds 45% max). Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-037",
        "scenario_id": "PRR199-037",
        "name": "High correlation cluster at limit — exactly 45% reduces size",
        "description": "Correlation cluster at exactly 45% weight boundary. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-038",
        "scenario_id": "PRR199-038",
        "name": "High correlation cluster under limit — 40% allows normal",
        "description": "Correlation cluster at 40% (below 45% max). Normal sizing allowed. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-039",
        "scenario_id": "PRR199-039",
        "name": "AI supply chain concentration — blocks new AI candidate",
        "description": "AI supply chain theme at 36% exposure. Candidate NVDA in AI supply chain theme. Theme limit exceeded, new candidate blocked. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-040",
        "scenario_id": "PRR199-040",
        "name": "AI supply chain concentration — reduces size for partial add",
        "description": "AI supply chain theme at 32% (below 35% limit). Candidate is ADD_POSITION type. Half-size add allowed. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "ADD_POSITION",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-041",
        "scenario_id": "PRR199-041",
        "name": "Semiconductor concentration — blocks new semiconductor candidate",
        "description": "Semiconductor theme at 38% (exceeds 35% max). New semiconductor candidate blocked. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-042",
        "scenario_id": "PRR199-042",
        "name": "Semiconductor concentration — reduces industry size",
        "description": "Semiconductor industry at 41% (exceeds 40% max). Reduces position size for new semiconductor entry. Expect ALLOW_REDUCED_SIZE.",
        "entry_type": "C_RECLAIM_20MA",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-043",
        "scenario_id": "PRR199-043",
        "name": "Risk off mode — position cut active market panic",
        "description": "Market risk-off flag active. All new positions blocked or reduced. Expect RISK_OFF_MODE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "RISK_OFF_MODE",
    },
    {
        **_BASE,
        "id": "PRR199-044",
        "scenario_id": "PRR199-044",
        "name": "Risk off mode — B breakout blocked in panic market",
        "description": "Market risk-off active during broad market sell-off. B breakout blocked. Expect RISK_OFF_MODE.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "RISK_OFF_MODE",
    },
    {
        **_BASE,
        "id": "PRR199-045",
        "scenario_id": "PRR199-045",
        "name": "Risk off mode — max risk cut to 0.5% per trade",
        "description": "Market risk-off active. Risk per trade capped at 0.5% (risk_off_single_trade_risk_pct_max). Expect RISK_OFF_MODE.",
        "entry_type": "TEST_POSITION",
        "expected_recommendation": "RISK_OFF_MODE",
    },
    {
        **_BASE,
        "id": "PRR199-046",
        "scenario_id": "PRR199-046",
        "name": "Malformed sizing input — empty dict blocked",
        "description": "Empty sizing input dict provided. Malformed input hard block triggered. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-047",
        "scenario_id": "PRR199-047",
        "name": "Malformed sizing input — missing paper_only flag",
        "description": "Sizing input missing paper_only=True flag. Safety check fails. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-048",
        "scenario_id": "PRR199-048",
        "name": "Malformed sizing input — missing no_real_orders flag",
        "description": "Sizing input missing no_real_orders=True flag. Hard block. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-049",
        "scenario_id": "PRR199-049",
        "name": "Unsafe export path — production path blocked",
        "description": "Export path contains 'production' substring. Safety module blocks export. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-050",
        "scenario_id": "PRR199-050",
        "name": "Unsafe export path — live path blocked",
        "description": "Export path contains 'live' substring. is_safe_export_path returns False. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-051",
        "scenario_id": "PRR199-051",
        "name": "Broker request blocked — forbidden action detected",
        "description": "Input dict contains 'BROKER_ORDER' string. Forbidden action word block. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-052",
        "scenario_id": "PRR199-052",
        "name": "Real order request blocked — BUY action forbidden",
        "description": "Input contains 'BUY' forbidden action. Hard block. Sizing never executes order. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-053",
        "scenario_id": "PRR199-053",
        "name": "Real order request blocked — EXECUTE action forbidden",
        "description": "Input contains 'EXECUTE' forbidden action word. Assert_safe raises ValueError. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-054",
        "scenario_id": "PRR199-054",
        "name": "Real rebalance blocked — REBALANCE_REAL_PORTFOLIO forbidden",
        "description": "Request to rebalance real portfolio detected. Hard block condition. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-055",
        "scenario_id": "PRR199-055",
        "name": "Production mutation blocked — strategy mutation forbidden",
        "description": "Sizing input attempts production strategy mutation. Hard block. sizing_mutates_strategy must be False. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-056",
        "scenario_id": "PRR199-056",
        "name": "Complete risk budget dashboard — all panels rendered",
        "description": "Full risk budget dashboard with 12 panels: capital profile, risk budget, position sizing, entry rules, stop analysis, cash buffer, exposure limits, theme, industry, risk-off, no-entry, recommendations. Expect NO_CHANGE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "NO_CHANGE",
    },
    {
        **_BASE,
        "id": "PRR199-057",
        "scenario_id": "PRR199-057",
        "name": "Complete portfolio risk report — all sections exported",
        "description": "Full portfolio risk report export with all 12 defined sections. Report does not trigger rebalance or place real orders. Expect NO_CHANGE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "NO_CHANGE",
    },
    {
        **_BASE,
        "id": "PRR199-058",
        "scenario_id": "PRR199-058",
        "name": "Symbol weight at limit — 20% single symbol blocked",
        "description": "Single symbol at 20% of portfolio (max_single_symbol_weight). New position in same symbol blocked. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-059",
        "scenario_id": "PRR199-059",
        "name": "Symbol weight under limit — 15% allows new entry",
        "description": "Symbol at 15% weight (below 20% max). Normal sizing allowed. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-060",
        "scenario_id": "PRR199-060",
        "name": "Risk off mode — keep cash recommendation",
        "description": "Market risk-off active. No candidates with sufficient edge. Recommend keeping cash. Expect RISK_OFF_MODE.",
        "entry_type": "NO_ENTRY",
        "expected_recommendation": "RISK_OFF_MODE",
    },
    {
        **_BASE,
        "id": "PRR199-061",
        "scenario_id": "PRR199-061",
        "name": "Fixed fractional risk policy — position size from stop distance",
        "description": "300k capital, 1% risk, 5% stop distance. Max loss $3,000. Position size = $60,000 (20% of capital). Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-062",
        "scenario_id": "PRR199-062",
        "name": "Stop distance based sizing — tight 3% stop increases position size",
        "description": "3% stop distance with 1% risk. Position size = $100,000 (33% of capital). Risk budget check required. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-063",
        "scenario_id": "PRR199-063",
        "name": "Stop distance based sizing — wide 10% stop reduces position size",
        "description": "10% stop distance with 1.5% risk. Position size = $45,000 (15% of capital). Expect ALLOW_REDUCED_SIZE due to B multiplier.",
        "entry_type": "B_BREAKOUT_BASE",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-064",
        "scenario_id": "PRR199-064",
        "name": "No entry when risk exceeded — portfolio risk score 0.85",
        "description": "Portfolio risk score at 0.85 (CRITICAL grade). No entry when risk exceeded policy triggered. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-065",
        "scenario_id": "PRR199-065",
        "name": "Aggressive sizing scenario — 2% risk pct aggressive mode",
        "description": "Aggressive sizing with 2.0% risk pct (aggressive_single_trade_risk_pct_max). Low risk grade. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-066",
        "scenario_id": "PRR199-066",
        "name": "Risk off sizing cap — 0.5% risk per trade in risk-off mode",
        "description": "Risk-off mode caps risk at 0.5% per trade. Position size reduced significantly vs normal. Expect RISK_OFF_MODE.",
        "entry_type": "TEST_POSITION",
        "expected_recommendation": "RISK_OFF_MODE",
    },
    {
        **_BASE,
        "id": "PRR199-067",
        "scenario_id": "PRR199-067",
        "name": "Multi-theme portfolio — two themes below limit allows entry",
        "description": "AI theme at 25%, semiconductor theme at 20%. Both below limits. Normal A entry allowed. Expect ALLOW_NORMAL_SIZE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
    {
        **_BASE,
        "id": "PRR199-068",
        "scenario_id": "PRR199-068",
        "name": "Multi-theme portfolio — one theme exceeded blocks new entry",
        "description": "AI theme at 36% (over limit), semiconductor at 20%. Candidate in AI theme. Block triggered. Expect BLOCK_NEW_ENTRY.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
    },
    {
        **_BASE,
        "id": "PRR199-069",
        "scenario_id": "PRR199-069",
        "name": "Require more evidence — weak setup with uncertain entry",
        "description": "C_RECLAIM_20MA entry type with insufficient evidence for conviction. Require more confirmation before sizing up. Expect REQUIRE_MORE_EVIDENCE.",
        "entry_type": "C_RECLAIM_20MA",
        "expected_recommendation": "REQUIRE_MORE_EVIDENCE",
    },
    {
        **_BASE,
        "id": "PRR199-070",
        "scenario_id": "PRR199-070",
        "name": "Reduce existing exposure — risk grade elevated, trim positions",
        "description": "Portfolio risk grade ELEVATED with 8 open positions. Recommend reducing existing exposure before adding. Expect REDUCE_EXISTING_EXPOSURE.",
        "entry_type": "NO_ENTRY",
        "expected_recommendation": "REDUCE_EXISTING_EXPOSURE",
    },
    {
        **_BASE,
        "id": "PRR199-071",
        "scenario_id": "PRR199-071",
        "name": "Keep cash — no qualified entry candidates today",
        "description": "No entry candidates meet quality threshold. Risk grade LOW but no setups. Recommend keeping cash. Expect KEEP_CASH.",
        "entry_type": "NO_ENTRY",
        "expected_recommendation": "KEEP_CASH",
    },
    {
        **_BASE,
        "id": "PRR199-072",
        "scenario_id": "PRR199-072",
        "name": "Safety audit — all safety flags verified correct",
        "description": "Run full safety audit. All 28 safety flags verified. No forbidden actions in allowed list. All 22 hard block conditions present. Expect NO_CHANGE (audit pass).",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "NO_CHANGE",
    },
    {
        **_BASE,
        "id": "PRR199-073",
        "scenario_id": "PRR199-073",
        "name": "Health check — all modules import and verify",
        "description": "Full health check across all 8 modules: version, models, safety, engine, report, scenarios, fixtures, GUI panel, CLI. Expect NO_CHANGE (health pass).",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "NO_CHANGE",
    },
    {
        **_BASE,
        "id": "PRR199-074",
        "scenario_id": "PRR199-074",
        "name": "Release gate — all gate checks pass for v1.9.9",
        "description": "Full release gate for v1.9.9. Version, models, safety, engine, report, scenarios, fixtures, GUI, CLI all pass. Expect NO_CHANGE.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "NO_CHANGE",
    },
    {
        **_BASE,
        "id": "PRR199-075",
        "scenario_id": "PRR199-075",
        "name": "End-to-end position sizing workflow — A entry 300k capital",
        "description": "Full workflow: validate input, compute multiplier (1.0x), check no-entry conditions (none triggered), compute position size (300k * 1.5% / 5% = $90k), return ALLOW_NORMAL_SIZE with paper_only=True and sizing_executes_order=False.",
        "entry_type": "A_PULLBACK_10MA",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
    },
]

assert len(_SCENARIOS) == 75, f"Expected 75 scenarios, got {len(_SCENARIOS)}"


def get_scenarios() -> List[Dict[str, Any]]:
    return list(_SCENARIOS)


def get_scenario_by_id(sid: str) -> Dict[str, Any]:
    for s in _SCENARIOS:
        if s["id"] == sid or s["scenario_id"] == sid:
            return s
    return {}
