"""
paper_trading/small_capital_strategy/portfolio_risk_report_fixtures_v199.py
v1.9.9 Paper Portfolio Risk Report & Position Sizing Policy Lab — Fixtures
[!] Paper Only. Research Only. Position Sizing Policy Only. Portfolio Risk Report Only.
[!] No Real Orders. Not Investment Advice.
"""
from __future__ import annotations
from typing import List, Dict, Any

_BASE = {
    "schema_version": "199",
    "paper_only": True,
    "research_only": True,
    "simulate_only": True,
    "validation_only": True,
    "portfolio_risk_report_only": True,
    "position_sizing_policy_only": True,
    "dashboard_only": True,
    "report_only": True,
    "audit_only": True,
    "no_real_orders": True,
    "no_broker": True,
    "no_margin": True,
    "no_leverage": True,
    "no_production_strategy_mutation": True,
    "no_automatic_rollback": True,
    "no_live_strategy_activation": True,
    "no_real_portfolio_rebalancing": True,
    "not_investment_advice": True,
    "demo_only": True,
    "not_for_production": True,
    "production_trading_blocked": True,
}

_FIXTURES: List[Dict[str, Any]] = [
    {
        **_BASE,
        "id": "PRRF199-001",
        "fixture_id": "PRRF199-001",
        "name": "300k capital profile — default A entry, normal conditions",
        "description": "Standard 300k capital profile with A_PULLBACK_10MA entry, 5% stop, LOW risk grade, 20% cash. Expect normal size allowed.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-002",
        "fixture_id": "PRRF199-002",
        "name": "A entry normal size — 1.5% risk 5% stop = $90k position",
        "description": "300k capital, A_PULLBACK_10MA, 1.5% risk, 5% stop. Max loss = $4,500. Position = $90,000 = 30% of capital. Normal size allowed.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.40,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_position_amount": 90000.0,
        "expected_max_loss": 4500.0,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-003",
        "fixture_id": "PRRF199-003",
        "name": "A entry normal size — 0.8% risk 5% stop = $48k position",
        "description": "300k capital, A_PULLBACK_10MA, 0.8% risk, 5% stop. Max loss = $2,400. Position = $48,000 = 16% of capital. Normal size allowed.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_max_loss": 2400.0,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-004",
        "fixture_id": "PRRF199-004",
        "name": "B breakout reduced size — 0.7x multiplier LOW risk",
        "description": "B_BREAKOUT_BASE entry, 1.5% risk, 5% stop. Raw position $90k * 0.7 = $63k. Reduced size applied.",
        "capital_base": 300_000.0,
        "entry_type": "B_BREAKOUT_BASE",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_size_multiplier": 0.7,
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-005",
        "fixture_id": "PRRF199-005",
        "name": "B breakout blocked — HIGH risk grade",
        "description": "B_BREAKOUT_BASE entry with portfolio risk grade HIGH. No new entries at HIGH risk. Blocked.",
        "capital_base": 300_000.0,
        "entry_type": "B_BREAKOUT_BASE",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "HIGH",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-006",
        "fixture_id": "PRRF199-006",
        "name": "C reclaim half size — 0.5x multiplier LOW risk",
        "description": "C_RECLAIM_20MA entry, 1.5% risk, 5% stop. Raw $90k * 0.5 = $45k. Half size applied.",
        "capital_base": 300_000.0,
        "entry_type": "C_RECLAIM_20MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_size_multiplier": 0.5,
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-007",
        "fixture_id": "PRRF199-007",
        "name": "C reclaim blocked — CRITICAL risk grade",
        "description": "C_RECLAIM_20MA entry with portfolio risk grade CRITICAL. Max severity block. No entry allowed.",
        "capital_base": 300_000.0,
        "entry_type": "C_RECLAIM_20MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "CRITICAL",
        "current_cash_pct": 0.15,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-008",
        "fixture_id": "PRRF199-008",
        "name": "Test position — 0.3x multiplier probe entry LOW risk",
        "description": "TEST_POSITION entry, 1.5% risk, 5% stop. Raw $90k * 0.3 = $27k. Test/probe size.",
        "capital_base": 300_000.0,
        "entry_type": "TEST_POSITION",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_size_multiplier": 0.3,
        "expected_recommendation": "TEST_POSITION_ONLY",
        "expected_paper_action": "PAPER_TEST_POSITION_ONLY",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-009",
        "fixture_id": "PRRF199-009",
        "name": "Add position — 0.5x multiplier with existing gain",
        "description": "ADD_POSITION entry type with unrealized gain in existing position. Half-size add allowed at LOW risk.",
        "capital_base": 300_000.0,
        "entry_type": "ADD_POSITION",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_size_multiplier": 0.5,
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-010",
        "fixture_id": "PRRF199-010",
        "name": "Reduce position — 0.0x multiplier no new entry",
        "description": "REDUCE_POSITION entry type. Multiplier 0.0x. No new position. Position amount = $0.",
        "capital_base": 300_000.0,
        "entry_type": "REDUCE_POSITION",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_size_multiplier": 0.0,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-011",
        "fixture_id": "PRRF199-011",
        "name": "No entry type — 0.0x multiplier always blocked",
        "description": "NO_ENTRY entry type. Multiplier 0.0x. Always blocked regardless of other conditions.",
        "capital_base": 300_000.0,
        "entry_type": "NO_ENTRY",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.50,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_size_multiplier": 0.0,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-012",
        "fixture_id": "PRRF199-012",
        "name": "Stop distance 20% — too wide, blocks entry",
        "description": "A_PULLBACK_10MA with 20% stop distance. Exceeds 15% max. REQUIRE_TIGHTER_STOP triggered.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.20,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "REQUIRE_TIGHTER_STOP",
        "expected_paper_action": "PAPER_REQUIRE_HUMAN_REVIEW",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-013",
        "fixture_id": "PRRF199-013",
        "name": "Stop distance 16% — just above 15% threshold, blocked",
        "description": "A_PULLBACK_10MA with 16% stop distance. Just above 15% max threshold. Stop too wide block triggered.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.16,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "REQUIRE_TIGHTER_STOP",
        "expected_paper_action": "PAPER_REQUIRE_HUMAN_REVIEW",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-014",
        "fixture_id": "PRRF199-014",
        "name": "Stop distance 15% — at max threshold, allowed",
        "description": "A_PULLBACK_10MA with exactly 15% stop distance. At boundary. Entry allowed with normal size.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.15,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-015",
        "fixture_id": "PRRF199-015",
        "name": "Stop distance 0% — missing stop, blocked",
        "description": "Stop distance of 0.0 (missing/invalid). Hard block on missing_stop_distance. Position size undefined.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.0,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-016",
        "fixture_id": "PRRF199-016",
        "name": "Max single trade loss $2,400 boundary — 0.8% risk 5% stop",
        "description": "300k capital, 0.8% risk, 5% stop. Max loss exactly $2,400. Minimum normal loss boundary. Allowed.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_max_loss": 2400.0,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-017",
        "fixture_id": "PRRF199-017",
        "name": "Max single trade loss $4,500 boundary — 1.5% risk 5% stop",
        "description": "300k capital, 1.5% risk, 5% stop. Max loss exactly $4,500. Maximum normal loss boundary. Allowed.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.40,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_max_loss": 4500.0,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-018",
        "fixture_id": "PRRF199-018",
        "name": "Theme exposure 38% — AI supply chain blocks new candidate",
        "description": "AI supply chain theme at 38% (exceeds 35% max). Candidate in AI supply chain. Block triggered.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"AI_SUPPLY_CHAIN": 0.38},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "AI_SUPPLY_CHAIN",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-019",
        "fixture_id": "PRRF199-019",
        "name": "Theme exposure exactly 35% — boundary blocks new entry",
        "description": "AI theme at exactly 35% weight (boundary). Candidate in same theme. Block triggered at limit.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {"AI": 0.35},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "AI",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-020",
        "fixture_id": "PRRF199-020",
        "name": "Theme exposure 30% — below limit, allows entry",
        "description": "AI theme at 30% (below 35% limit). Candidate in AI theme. Normal sizing allowed.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"AI": 0.30},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "AI",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-021",
        "fixture_id": "PRRF199-021",
        "name": "Industry exposure 42% — semiconductor industry reduces size",
        "description": "Semiconductor industry at 42% (exceeds 40% max). Candidate in semiconductor. Reduce size condition.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {"SEMICONDUCTOR": 0.42},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-022",
        "fixture_id": "PRRF199-022",
        "name": "Industry exposure exactly 40% — boundary reduces size",
        "description": "Industry at exactly 40% boundary. check_industry_exposure returns reduce_size=True.",
        "capital_base": 300_000.0,
        "entry_type": "B_BREAKOUT_BASE",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {"SOFTWARE": 0.40},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-023",
        "fixture_id": "PRRF199-023",
        "name": "Industry exposure 35% — below limit, allows normal sizing",
        "description": "Industry at 35% (below 40% limit). No size reduction triggered. Normal sizing for A entry.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {"CLOUD": 0.35},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-024",
        "fixture_id": "PRRF199-024",
        "name": "Cash buffer 2% — well below 5% minimum, blocks entry",
        "description": "Cash at 2% (below 5% minimum). Cash buffer too low hard block.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.02,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-025",
        "fixture_id": "PRRF199-025",
        "name": "Cash buffer 4.9% — just below 5% minimum, blocks entry",
        "description": "Cash at 4.9% (fractionally below 5%). Block triggered at boundary.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.049,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-026",
        "fixture_id": "PRRF199-026",
        "name": "Cash buffer exactly 5% — at minimum, allows entry",
        "description": "Cash at exactly 5% minimum boundary. Cash buffer satisfied. A entry allowed.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.05,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-027",
        "fixture_id": "PRRF199-027",
        "name": "Weak market mode 30% cash — below 50% required, blocks",
        "description": "Market risk-off active. Weak market mode requires 50% cash. Current 30%. Block triggered.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": True,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "RISK_OFF_MODE",
        "expected_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-028",
        "fixture_id": "PRRF199-028",
        "name": "Weak market mode 49% cash — just below 50%, blocks",
        "description": "Market risk-off active with 49% cash. Just below 50% weak market threshold.",
        "capital_base": 300_000.0,
        "entry_type": "B_BREAKOUT_BASE",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.49,
        "market_risk_off": True,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "RISK_OFF_MODE",
        "expected_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-029",
        "fixture_id": "PRRF199-029",
        "name": "Weak market mode 60% cash — above 50%, risk-off still active",
        "description": "Market risk-off active with 60% cash (above 50% threshold). Cash ok but risk-off mode blocks new entry.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.60,
        "market_risk_off": True,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "RISK_OFF_MODE",
        "expected_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-030",
        "fixture_id": "PRRF199-030",
        "name": "High correlation cluster 46% — reduces size",
        "description": "AI infrastructure correlation cluster at 46% (exceeds 45% max). check_correlation_cluster returns reduce_size=True.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.46,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-031",
        "fixture_id": "PRRF199-031",
        "name": "High correlation cluster exactly 45% — boundary reduces size",
        "description": "Correlation cluster at exactly 45% boundary. Limit exceeded at boundary. reduce_size=True.",
        "capital_base": 300_000.0,
        "entry_type": "B_BREAKOUT_BASE",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.45,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-032",
        "fixture_id": "PRRF199-032",
        "name": "High correlation cluster 40% — below limit, allows normal size",
        "description": "Correlation cluster at 40% (below 45% limit). No size reduction. A entry normal size.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.40,
        "candidate_theme": "",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-033",
        "fixture_id": "PRRF199-033",
        "name": "AI supply chain theme 38% — blocks NVDA candidate",
        "description": "AI_SUPPLY_CHAIN theme at 38%. Candidate NVDA in same theme. check_theme_exposure blocks.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"AI_SUPPLY_CHAIN": 0.38},
        "industry_exposures": {},
        "symbol_weights": {"NVDA": 0.12},
        "high_correlation_cluster_weight": 0.30,
        "candidate_theme": "AI_SUPPLY_CHAIN",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-034",
        "fixture_id": "PRRF199-034",
        "name": "AI supply chain theme 32% — allows MSFT candidate",
        "description": "AI_SUPPLY_CHAIN theme at 32% (below 35%). Candidate MSFT allowed with normal A entry size.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"AI_SUPPLY_CHAIN": 0.32},
        "industry_exposures": {},
        "symbol_weights": {"MSFT": 0.10},
        "high_correlation_cluster_weight": 0.25,
        "candidate_theme": "AI_SUPPLY_CHAIN",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-035",
        "fixture_id": "PRRF199-035",
        "name": "Semiconductor theme 40% — blocks new semiconductor B entry",
        "description": "SEMICONDUCTOR theme at 40% (exceeds 35% max). Candidate in semiconductor theme. Block triggered.",
        "capital_base": 300_000.0,
        "entry_type": "B_BREAKOUT_BASE",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"SEMICONDUCTOR": 0.40},
        "industry_exposures": {"SEMICONDUCTOR": 0.38},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.35,
        "candidate_theme": "SEMICONDUCTOR",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-036",
        "fixture_id": "PRRF199-036",
        "name": "Semiconductor industry 41% — reduces C reclaim entry",
        "description": "SEMICONDUCTOR industry at 41% (exceeds 40% max). C reclaim entry size reduced.",
        "capital_base": 300_000.0,
        "entry_type": "C_RECLAIM_20MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"SEMICONDUCTOR": 0.28},
        "industry_exposures": {"SEMICONDUCTOR": 0.41},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.30,
        "candidate_theme": "SEMICONDUCTOR",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-037",
        "fixture_id": "PRRF199-037",
        "name": "Risk off mode — market panic, all entries blocked",
        "description": "Market risk-off active (broad market sell-off). All new entries blocked. RISK_OFF_MODE paper action.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "MODERATE",
        "current_cash_pct": 0.55,
        "market_risk_off": True,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "RISK_OFF_MODE",
        "expected_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-038",
        "fixture_id": "PRRF199-038",
        "name": "Risk off mode — B entry blocked with 0.5% risk cap",
        "description": "Market risk-off with B breakout entry. Max risk capped at 0.5%. Entry blocked by risk-off condition.",
        "capital_base": 300_000.0,
        "entry_type": "B_BREAKOUT_BASE",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.60,
        "market_risk_off": True,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "RISK_OFF_MODE",
        "expected_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-039",
        "fixture_id": "PRRF199-039",
        "name": "Risk off mode — test position in risk-off environment",
        "description": "Market risk-off with TEST_POSITION entry type. Even smallest size blocked by risk-off mode.",
        "capital_base": 300_000.0,
        "entry_type": "TEST_POSITION",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.70,
        "market_risk_off": True,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_recommendation": "RISK_OFF_MODE",
        "expected_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-040",
        "fixture_id": "PRRF199-040",
        "name": "Missing paper_only flag — validation blocked",
        "description": "Sizing input missing paper_only=True flag. validate_sizing_input returns blocked=True.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "missing_flag": "paper_only",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-041",
        "fixture_id": "PRRF199-041",
        "name": "Missing no_real_orders flag — validation blocked",
        "description": "Sizing input missing no_real_orders=True flag. Hard block: missing_no_broker_flags.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "missing_flag": "no_real_orders",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-042",
        "fixture_id": "PRRF199-042",
        "name": "Missing not_investment_advice flag — validation blocked",
        "description": "Sizing input missing not_investment_advice=True flag. Hard block: missing_not_investment_advice_flags.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "missing_flag": "not_investment_advice",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-043",
        "fixture_id": "PRRF199-043",
        "name": "Unsafe export path — production path blocked",
        "description": "Export to path containing 'production' substring. is_safe_export_path returns False. Export blocked.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_export_path": "C:/production/reports/risk_report.json",
        "expected_export_safe": False,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-044",
        "fixture_id": "PRRF199-044",
        "name": "Unsafe export path — live path blocked",
        "description": "Export to path containing 'live' substring. is_safe_export_path returns False.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_export_path": "C:/live/trading/reports/",
        "expected_export_safe": False,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-045",
        "fixture_id": "PRRF199-045",
        "name": "Safe export path — paper reports path allowed",
        "description": "Export to 'C:/Users/Rossi/paper_reports/' path. is_safe_export_path returns True.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_export_path": "C:/Users/Rossi/paper_reports/risk_report_v199.json",
        "expected_export_safe": True,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-046",
        "fixture_id": "PRRF199-046",
        "name": "BUY forbidden action — assert_safe raises ValueError",
        "description": "assert_safe('BUY') raises ValueError. Forbidden action blocked. sizing_executes_order always False.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_forbidden_action": "BUY",
        "expected_assert_safe_raises": True,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-047",
        "fixture_id": "PRRF199-047",
        "name": "SELL forbidden action — assert_safe raises ValueError",
        "description": "assert_safe('SELL') raises ValueError. Paper-only sizing never places sell orders.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_forbidden_action": "SELL",
        "expected_assert_safe_raises": True,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-048",
        "fixture_id": "PRRF199-048",
        "name": "REBALANCE_REAL_PORTFOLIO forbidden — assert_safe raises",
        "description": "assert_safe('REBALANCE_REAL_PORTFOLIO') raises ValueError. Real portfolio rebalancing blocked.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_forbidden_action": "REBALANCE_REAL_PORTFOLIO",
        "expected_assert_safe_raises": True,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-049",
        "fixture_id": "PRRF199-049",
        "name": "Safety audit — all 28 flags verified correct",
        "description": "run_safety_audit() returns all_safe=True. 28 safety flags, 15 forbidden actions, 20 allowed actions, 22 hard block conditions verified.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_safety_audit_all_safe": True,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-050",
        "fixture_id": "PRRF199-050",
        "name": "Risk grade LOW — score 0.1",
        "description": "compute_risk_grade(0.1) returns 'LOW'. Score in [0.0, 0.2) range.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_risk_score": 0.1,
        "expected_risk_grade": "LOW",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-051",
        "fixture_id": "PRRF199-051",
        "name": "Risk grade MODERATE — score 0.3",
        "description": "compute_risk_grade(0.3) returns 'MODERATE'. Score in [0.2, 0.4) range.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "MODERATE",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_risk_score": 0.3,
        "expected_risk_grade": "MODERATE",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-052",
        "fixture_id": "PRRF199-052",
        "name": "Risk grade ELEVATED — score 0.5",
        "description": "compute_risk_grade(0.5) returns 'ELEVATED'. Score in [0.4, 0.6) range. Reduces size.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "ELEVATED",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_risk_score": 0.5,
        "expected_risk_grade": "ELEVATED",
        "expected_recommendation": "ALLOW_REDUCED_SIZE",
        "expected_paper_action": "PAPER_ALLOW_REDUCED_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-053",
        "fixture_id": "PRRF199-053",
        "name": "Risk grade HIGH — score 0.7",
        "description": "compute_risk_grade(0.7) returns 'HIGH'. Score in [0.6, 0.8) range. Blocks new entry.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "HIGH",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_risk_score": 0.7,
        "expected_risk_grade": "HIGH",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-054",
        "fixture_id": "PRRF199-054",
        "name": "Risk grade CRITICAL — score 0.9",
        "description": "compute_risk_grade(0.9) returns 'CRITICAL'. Score in [0.8, 1.0) range. Blocks new entry.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "CRITICAL",
        "current_cash_pct": 0.15,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_risk_score": 0.9,
        "expected_risk_grade": "CRITICAL",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-055",
        "fixture_id": "PRRF199-055",
        "name": "Risk grade INVALID — score -0.1",
        "description": "compute_risk_grade(-0.1) returns 'INVALID'. Negative score out of valid range.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_risk_score": -0.1,
        "expected_risk_grade": "INVALID",
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-056",
        "fixture_id": "PRRF199-056",
        "name": "Capital profile export — all 13 fields verified",
        "description": "export_capital_profile(300000) returns dict with all 13 capital profile fields including paper_only, no_real_orders, not_investment_advice.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_section": "capital_profile",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-057",
        "fixture_id": "PRRF199-057",
        "name": "Risk budget export — 300k capital 20% max risk = $60k budget",
        "description": "export_risk_budget(300000) with 0% used. Total budget $60,000. Remaining $60,000. pct_used 0.0.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_section": "risk_budget",
        "expected_total_budget": 60000.0,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-058",
        "fixture_id": "PRRF199-058",
        "name": "Entry sizing rules export — all 7 entry types with multipliers",
        "description": "export_entry_sizing_rules() returns 7 rules: A=1.0, B=0.7, C=0.5, TEST=0.3, ADD=0.5, REDUCE=0.0, NO_ENTRY=0.0.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_rules_count": 7,
        "expected_a_multiplier": 1.0,
        "expected_b_multiplier": 0.7,
        "expected_c_multiplier": 0.5,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-059",
        "fixture_id": "PRRF199-059",
        "name": "Stop distance analysis — 5% stop, $90k implied size",
        "description": "export_stop_distance_analysis(0.05) with 1.5% risk: max_loss=$4,500, implied_position=$90,000. Not blocked.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_implied_position": 90000.0,
        "expected_max_loss": 4500.0,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-060",
        "fixture_id": "PRRF199-060",
        "name": "Stop distance analysis — 0 stop blocked",
        "description": "export_stop_distance_analysis(0.0) returns blocked=True, block_reason='missing_stop_distance'.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.0,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_stop_blocked": True,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-061",
        "fixture_id": "PRRF199-061",
        "name": "Cash buffer status — 20% cash, normal market, ok",
        "description": "export_cash_buffer_status(0.20) with weak_market_mode=False. Required 5%, have 20%. cash_buffer_ok=True.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_cash_buffer_ok": True,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-062",
        "fixture_id": "PRRF199-062",
        "name": "Cash buffer status — 3% cash, normal market, blocked",
        "description": "export_cash_buffer_status(0.03) with weak_market_mode=False. Required 5%, have 3%. block_new_entry=True.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.03,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_cash_buffer_ok": False,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-063",
        "fixture_id": "PRRF199-063",
        "name": "Exposure limits export — theme violation detected",
        "description": "export_exposure_limits with AI theme at 37%. theme_violations returned. any_limit_exceeded=True.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"AI": 0.37},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "AI",
        "expected_any_limit_exceeded": True,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-064",
        "fixture_id": "PRRF199-064",
        "name": "Exposure limits export — no violations, all clear",
        "description": "export_exposure_limits with all exposures below limits. any_limit_exceeded=False. Normal sizing.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"AI": 0.20, "CLOUD": 0.15},
        "industry_exposures": {"SOFTWARE": 0.25},
        "symbol_weights": {"NVDA": 0.10, "MSFT": 0.08},
        "high_correlation_cluster_weight": 0.30,
        "candidate_theme": "CLOUD",
        "expected_any_limit_exceeded": False,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-065",
        "fixture_id": "PRRF199-065",
        "name": "Risk off status export — risk_off_active True",
        "description": "export_risk_off_status(True) returns paper_action='PAPER_RISK_OFF_MODE', risk_off_max_risk_pct=0.005.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.60,
        "market_risk_off": True,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_risk_off_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_recommendation": "RISK_OFF_MODE",
        "expected_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-066",
        "fixture_id": "PRRF199-066",
        "name": "Risk off status export — risk_off_active False",
        "description": "export_risk_off_status(False) returns paper_action='PAPER_KEEP_CASH'. Normal market mode.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_risk_off_paper_action": "PAPER_KEEP_CASH",
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-067",
        "fixture_id": "PRRF199-067",
        "name": "Full risk report export — all 9 sections present",
        "description": "export_full_risk_report returns dict with 9 sections. sections_count=9. All paper flags set. No rebalance triggered.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_sections_count": 9,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-068",
        "fixture_id": "PRRF199-068",
        "name": "Version module — all counts verified",
        "description": "Version module verifies: 7 entry types, 11 sizing policies, 6 risk grades, 10 recommendations, 7 paper actions, 18 CLI commands, 3 GUI tabs, 22 hard block conditions, 10 forbidden actions.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_entry_types_count": 7,
        "expected_policies_count": 11,
        "expected_risk_grades_count": 6,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-069",
        "fixture_id": "PRRF199-069",
        "name": "Models module — all 25 model names verified",
        "description": "_ALL_MODEL_NAMES contains exactly 25 model names. All models instantiate with paper_only=True, no_real_orders=True.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_models_count": 25,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-070",
        "fixture_id": "PRRF199-070",
        "name": "Engine compute_position_size — 300k 1.5% risk 5% stop = $90k",
        "description": "compute_position_size(300000, 0.015, 0.05, 1.0). raw=$90000, adjusted=$90000, pct=0.3, max_loss=$4500.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.40,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_risk_pct": 0.015,
        "test_size_multiplier": 1.0,
        "expected_raw_position": 90000.0,
        "expected_adjusted_position": 90000.0,
        "expected_max_loss": 4500.0,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-071",
        "fixture_id": "PRRF199-071",
        "name": "Engine compute_position_size — risk-off cap 0.5% reduces to $3k",
        "description": "compute_position_size(300000, 0.015, 0.05, 1.0, risk_off=True). Risk capped at 0.5%. max_loss=$1,500. Position=$30,000.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.60,
        "market_risk_off": True,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "test_risk_pct": 0.015,
        "test_size_multiplier": 1.0,
        "expected_risk_off_max_loss": 1500.0,
        "expected_recommendation": "RISK_OFF_MODE",
        "expected_paper_action": "PAPER_RISK_OFF_MODE",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-072",
        "fixture_id": "PRRF199-072",
        "name": "Engine run_position_sizing_report — valid input full workflow",
        "description": "run_position_sizing_report with fully valid input. Returns allowed=True, recommendation=ALLOW_NORMAL_SIZE, sizing_executes_order=False, sizing_mutates_strategy=False.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_sizing_executes_order": False,
        "expected_sizing_mutates_strategy": False,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-073",
        "fixture_id": "PRRF199-073",
        "name": "Multiple exposure violations — all tracked in report",
        "description": "Theme AI at 37%, industry SEMIS at 42%, symbol NVDA at 22%. All three violations tracked in exposure_limits section.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.20,
        "market_risk_off": False,
        "theme_exposures": {"AI": 0.37},
        "industry_exposures": {"SEMICONDUCTOR": 0.42},
        "symbol_weights": {"NVDA": 0.22},
        "high_correlation_cluster_weight": 0.35,
        "candidate_theme": "AI",
        "expected_any_limit_exceeded": True,
        "expected_recommendation": "BLOCK_NEW_ENTRY",
        "expected_paper_action": "PAPER_BLOCK_NEW_ENTRY",
        "expected_blocked": True,
    },
    {
        **_BASE,
        "id": "PRRF199-074",
        "fixture_id": "PRRF199-074",
        "name": "Dashboard model — paper flags verified, no mutation",
        "description": "PaperRiskReportDashboard() has dashboard_mutates_strategy=False, dashboard_places_real_order=False, paper_only=True, panels_count=12.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.30,
        "market_risk_off": False,
        "theme_exposures": {},
        "industry_exposures": {},
        "symbol_weights": {},
        "high_correlation_cluster_weight": 0.0,
        "candidate_theme": "",
        "expected_dashboard_mutates": False,
        "expected_dashboard_places_order": False,
        "expected_panels_count": 12,
        "expected_recommendation": "NO_CHANGE",
        "expected_paper_action": "PAPER_KEEP_CASH",
        "expected_blocked": False,
    },
    {
        **_BASE,
        "id": "PRRF199-075",
        "fixture_id": "PRRF199-075",
        "name": "End-to-end v1.9.9 position sizing — complete paper workflow",
        "description": "Full paper workflow fixture: 300k capital, A_PULLBACK_10MA, 5% stop, LOW risk, 25% cash, no exposure issues. Position $90k, max loss $4,500, ALLOW_NORMAL_SIZE, paper_only=True, no real orders, not investment advice.",
        "capital_base": 300_000.0,
        "entry_type": "A_PULLBACK_10MA",
        "stop_distance_pct": 0.05,
        "portfolio_risk_grade": "LOW",
        "current_cash_pct": 0.25,
        "market_risk_off": False,
        "theme_exposures": {"AI": 0.15, "CLOUD": 0.10},
        "industry_exposures": {"SOFTWARE": 0.20, "SEMICONDUCTOR": 0.15},
        "symbol_weights": {"MSFT": 0.08, "NVDA": 0.10, "GOOGL": 0.07},
        "high_correlation_cluster_weight": 0.25,
        "candidate_theme": "AI",
        "expected_position_amount": 90000.0,
        "expected_max_loss": 4500.0,
        "expected_size_multiplier": 1.0,
        "expected_sizing_executes_order": False,
        "expected_sizing_mutates_strategy": False,
        "expected_sizing_rebalances_real_portfolio": False,
        "expected_recommendation": "ALLOW_NORMAL_SIZE",
        "expected_paper_action": "PAPER_ALLOW_NORMAL_SIZE",
        "expected_blocked": False,
    },
]

assert len(_FIXTURES) == 75, f"Expected 75 fixtures, got {len(_FIXTURES)}"


def get_fixtures() -> List[Dict[str, Any]]:
    return list(_FIXTURES)


def get_fixture_by_id(fid: str) -> Dict[str, Any]:
    for f in _FIXTURES:
        if f["id"] == fid or f["fixture_id"] == fid:
            return f
    return {}
