"""
paper_trading/small_capital_strategy/stable_rollup_scenarios_v179.py
Scenarios for Small Capital Strategy Stable Rollup v1.7.9. 50 scenarios.
[!] Research Only. Paper Only. No Real Orders. Not Investment Advice.
"""
from __future__ import annotations
from typing import Any, Dict, List, Optional

_SCHEMA  = "179"
_POLICY  = "1.7.9-small-capital-strategy-stable-rollup"

_SCENARIOS: List[Dict[str, Any]] = [
    # ── PAPER_ENTRY_ALLOWED (10) ──────────────────────────────────────────────
    {"id": "SC179-001", "name": "All v1.7.0~v1.7.8 compat PASS + safety PASS → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "full_rollup",
     "compat_all_pass": True, "safety_all_safe": True, "cli_all_registered": True,
     "gui_tabs_present": True, "health_all_pass": True, "gate_all_pass": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-002", "name": "Version compat v1.7.0 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.0", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-003", "name": "Version compat v1.7.1 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.1", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-004", "name": "Version compat v1.7.2 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.2", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-005", "name": "Version compat v1.7.3 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.3", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-006", "name": "Version compat v1.7.4 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.4", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-007", "name": "Version compat v1.7.5 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.5", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-008", "name": "Version compat v1.7.6 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.6", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-009", "name": "Version compat v1.7.7 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.7", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-010", "name": "Version compat v1.7.8 OK → PAPER_ENTRY_ALLOWED",
     "expected_action": "PAPER_ENTRY_ALLOWED", "category": "version_compat",
     "target_version": "v1.7.8", "importable": True, "version_match": True, "safety_ok": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    # ── PAPER_PLAN_READY (5) ─────────────────────────────────────────────────
    {"id": "SC179-011", "name": "Safety audit all_safe → PAPER_PLAN_READY",
     "expected_action": "PAPER_PLAN_READY", "category": "safety",
     "safety_all_safe": True, "health_all_pass": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-012", "name": "CLI all 12 stable commands registered → PAPER_PLAN_READY",
     "expected_action": "PAPER_PLAN_READY", "category": "cli",
     "cli_all_registered": True, "cli_count": 12,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-013", "name": "GUI 3 stable tabs present + render clean → PAPER_PLAN_READY",
     "expected_action": "PAPER_PLAN_READY", "category": "gui",
     "gui_tabs_present": True, "render_clean": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-014", "name": "All fixtures have safety flags → PAPER_PLAN_READY",
     "expected_action": "PAPER_PLAN_READY", "category": "fixture",
     "fixture_audit_pass": True, "total_fixtures_min": 50,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-015", "name": "All scenarios no forbidden actions → PAPER_PLAN_READY",
     "expected_action": "PAPER_PLAN_READY", "category": "scenario",
     "scenario_audit_pass": True, "total_scenarios_min": 50,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    # ── PAPER_ADD_ALLOWED (5) ────────────────────────────────────────────────
    {"id": "SC179-016", "name": "Health 50+ checks PASS → PAPER_ADD_ALLOWED",
     "expected_action": "PAPER_ADD_ALLOWED", "category": "health",
     "health_all_pass": True, "health_count_min": 50,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-017", "name": "Gate 50+ checks PASS → PAPER_ADD_ALLOWED",
     "expected_action": "PAPER_ADD_ALLOWED", "category": "gate",
     "gate_all_pass": True, "gate_count_min": 50,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-018", "name": "Regression audit clean → PAPER_ADD_ALLOWED",
     "expected_action": "PAPER_ADD_ALLOWED", "category": "regression",
     "regression_clean": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-019", "name": "v1.7.0 health PASS → PAPER_ADD_ALLOWED",
     "expected_action": "PAPER_ADD_ALLOWED", "category": "health",
     "target_version": "v1.7.0", "health_pass": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-020", "name": "v1.7.8 gate PASS → PAPER_ADD_ALLOWED",
     "expected_action": "PAPER_ADD_ALLOWED", "category": "gate",
     "target_version": "v1.7.8", "gate_pass": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    # ── OBSERVE (5) ──────────────────────────────────────────────────────────
    {"id": "SC179-021", "name": "Rollup v1.7.9 version check → OBSERVE",
     "expected_action": "OBSERVE", "category": "version_compat",
     "rollup_version": "1.7.9", "check": "version_metadata",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-022", "name": "Manifest structure valid → OBSERVE",
     "expected_action": "OBSERVE", "category": "full_rollup",
     "manifest_valid": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-023", "name": "Models importable → OBSERVE",
     "expected_action": "OBSERVE", "category": "full_rollup",
     "models_importable": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-024", "name": "Report builds → OBSERVE",
     "expected_action": "OBSERVE", "category": "full_rollup",
     "report_buildable": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-025", "name": "Safety no_margin=True → OBSERVE",
     "expected_action": "OBSERVE", "category": "safety",
     "no_margin": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    # ── WAIT (8) ─────────────────────────────────────────────────────────────
    {"id": "SC179-026", "name": "v1.7.1 compat pending → WAIT",
     "expected_action": "WAIT", "category": "version_compat",
     "target_version": "v1.7.1", "check": "import_pending",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-027", "name": "CLI audit in progress → WAIT",
     "expected_action": "WAIT", "category": "cli",
     "audit_status": "in_progress",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-028", "name": "GUI audit render pending → WAIT",
     "expected_action": "WAIT", "category": "gui",
     "audit_status": "render_pending",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-029", "name": "Fixture audit loading → WAIT",
     "expected_action": "WAIT", "category": "fixture",
     "audit_status": "loading",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-030", "name": "Scenario audit loading → WAIT",
     "expected_action": "WAIT", "category": "scenario",
     "audit_status": "loading",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-031", "name": "Health check running → WAIT",
     "expected_action": "WAIT", "category": "health",
     "health_status": "running",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-032", "name": "Gate check running → WAIT",
     "expected_action": "WAIT", "category": "gate",
     "gate_status": "running",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-033", "name": "Report building → WAIT",
     "expected_action": "WAIT", "category": "full_rollup",
     "report_status": "building",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    # ── REDUCE_RISK (5) ──────────────────────────────────────────────────────
    {"id": "SC179-034", "name": "Fixture safety violation detected → REDUCE_RISK",
     "expected_action": "REDUCE_RISK", "category": "fixture",
     "violation_detected": True, "fixture_safety_fail": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-035", "name": "Scenario forbidden action detected → REDUCE_RISK",
     "expected_action": "REDUCE_RISK", "category": "scenario",
     "forbidden_action_detected": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-036", "name": "Regression issue found → REDUCE_RISK",
     "expected_action": "REDUCE_RISK", "category": "regression",
     "regression_issue": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-037", "name": "GUI render error detected → REDUCE_RISK",
     "expected_action": "REDUCE_RISK", "category": "gui",
     "render_error_detected": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-038", "name": "CLI command missing → REDUCE_RISK",
     "expected_action": "REDUCE_RISK", "category": "cli",
     "cli_missing": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    # ── REVIEW_REQUIRED (5) ──────────────────────────────────────────────────
    {"id": "SC179-039", "name": "Version compat partial fail → REVIEW_REQUIRED",
     "expected_action": "REVIEW_REQUIRED", "category": "version_compat",
     "compat_partial_fail": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-040", "name": "Health 1 check fail → REVIEW_REQUIRED",
     "expected_action": "REVIEW_REQUIRED", "category": "health",
     "health_partial_fail": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-041", "name": "Gate 1 check fail → REVIEW_REQUIRED",
     "expected_action": "REVIEW_REQUIRED", "category": "gate",
     "gate_partial_fail": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-042", "name": "Safety flag anomaly → REVIEW_REQUIRED",
     "expected_action": "REVIEW_REQUIRED", "category": "safety",
     "safety_anomaly": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-043", "name": "GUI tab missing → REVIEW_REQUIRED",
     "expected_action": "REVIEW_REQUIRED", "category": "gui",
     "tab_missing": True,
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    # ── BLOCKED (5) ──────────────────────────────────────────────────────────
    {"id": "SC179-044", "name": "real_order requested → BLOCKED",
     "expected_action": "BLOCKED", "category": "safety",
     "real_order_requested": True, "block_reason": "REAL_ORDER_BLOCKED",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-045", "name": "broker_execution requested → BLOCKED",
     "expected_action": "BLOCKED", "category": "safety",
     "broker_execution_requested": True, "block_reason": "BROKER_BLOCKED",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-046", "name": "margin requested → BLOCKED",
     "expected_action": "BLOCKED", "category": "safety",
     "margin_requested": True, "block_reason": "MARGIN_BLOCKED",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-047", "name": "production_db_write attempted → BLOCKED",
     "expected_action": "BLOCKED", "category": "safety",
     "production_db_write": True, "block_reason": "PRODUCTION_WRITE_ATTEMPTED",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-048", "name": "Safety audit FAIL → BLOCKED",
     "expected_action": "BLOCKED", "category": "safety",
     "safety_fail": True, "block_reason": "SAFETY_AUDIT_FAIL",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    # ── NO_TRADE (2) ─────────────────────────────────────────────────────────
    {"id": "SC179-049", "name": "Compat check fails → NO_TRADE",
     "expected_action": "NO_TRADE", "category": "version_compat",
     "compat_fail": True, "reason": "VERSION_COMPAT_FAIL",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
    {"id": "SC179-050", "name": "All gates fail → NO_TRADE",
     "expected_action": "NO_TRADE", "category": "gate",
     "all_gates_fail": True, "reason": "ALL_GATES_FAIL",
     "paper_only": True, "research_only": True, "no_real_orders": True,
     "no_broker": True, "not_investment_advice": True, "demo_only": True, "not_for_production": True},
]


def get_scenarios() -> List[Dict[str, Any]]:
    return list(_SCENARIOS)


def count_scenarios() -> int:
    return len(_SCENARIOS)


def get_scenario_by_id(sid: str) -> Optional[Dict[str, Any]]:
    for s in _SCENARIOS:
        if s["id"] == sid:
            return s
    return None


def get_scenarios_by_action(action: str) -> List[Dict[str, Any]]:
    return [s for s in _SCENARIOS if s["expected_action"] == action]
