"""
paper_trading/stable_rollup/capability_matrix_v169.py
Capability matrix for Live Paper Trading Stable Rollup v1.6.9.
[!] RESEARCH ONLY. PAPER ONLY. NO REAL ORDERS. NO BROKER.
"""
from __future__ import annotations
from typing import List, Optional

CAPABILITY_MATRIX: List[dict] = [
    {
        "capability": "paper_trading",
        "introduced_in": "1.6.0",
        "enhanced_in": ["1.6.1", "1.6.2", "1.6.3", "1.6.8"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": False,
        "dependencies": [],
        "health_coverage": ["paper_trading.health_v160"],
        "gate_coverage": ["release.live_paper_trading_release_gate_v160"],
        "tests_count": 400,
        "limitations": ["Simulation only", "No broker connectivity"],
    },
    {
        "capability": "market_data_session",
        "introduced_in": "1.6.1",
        "enhanced_in": ["1.6.3", "1.6.8"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["paper_trading"],
        "health_coverage": ["paper_trading.market_data.health_v161"],
        "gate_coverage": ["release.market_data_session_release_gate_v161"],
        "tests_count": 300,
        "limitations": ["Historical data replay only"],
    },
    {
        "capability": "strategy_orchestration",
        "introduced_in": "1.6.2",
        "enhanced_in": ["1.6.8"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": False,
        "dependencies": ["paper_trading", "market_data_session"],
        "health_coverage": ["paper_trading.strategy.health_v162"],
        "gate_coverage": ["release.paper_strategy_orchestration_release_gate_v162"],
        "tests_count": 350,
        "limitations": ["Paper orders only"],
    },
    {
        "capability": "session_operations",
        "introduced_in": "1.6.3",
        "enhanced_in": ["1.6.6", "1.6.8"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["paper_trading", "market_data_session"],
        "health_coverage": ["paper_trading.operations.health_v163"],
        "gate_coverage": ["release.session_operations_observability_release_gate_v163"],
        "tests_count": 280,
        "limitations": ["Observability only"],
    },
    {
        "capability": "analytics",
        "introduced_in": "1.6.4",
        "enhanced_in": ["1.6.8"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["session_operations"],
        "health_coverage": ["paper_trading.analytics.health_v164"],
        "gate_coverage": ["release.operational_analytics_review_release_gate_v164"],
        "tests_count": 320,
        "limitations": ["Analytics and review only, no automated actions"],
    },
    {
        "capability": "failure_injection",
        "introduced_in": "1.6.5",
        "enhanced_in": [],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": False,
        "dependencies": ["paper_trading"],
        "health_coverage": ["paper_trading.failure_validation.health_v165"],
        "gate_coverage": ["release.failure_injection_recovery_release_gate_v165"],
        "tests_count": 250,
        "limitations": ["Simulated failures only"],
    },
    {
        "capability": "recovery_validation",
        "introduced_in": "1.6.5",
        "enhanced_in": [],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["failure_injection"],
        "health_coverage": ["paper_trading.failure_validation.health_v165"],
        "gate_coverage": ["release.failure_injection_recovery_release_gate_v165"],
        "tests_count": 200,
        "limitations": ["Validation only"],
    },
    {
        "capability": "multi_session_coordination",
        "introduced_in": "1.6.6",
        "enhanced_in": ["1.6.6.1", "1.6.8"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": False,
        "dependencies": ["session_operations"],
        "health_coverage": ["paper_trading.multi_session.health_v166"],
        "gate_coverage": ["release.multi_session_coordination_release_gate_v166"],
        "tests_count": 400,
        "limitations": ["Paper sessions only, no real coordination"],
    },
    {
        "capability": "fixture_governance",
        "introduced_in": "1.6.6.1",
        "enhanced_in": ["1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": [],
        "health_coverage": [],
        "gate_coverage": ["release.multi_session_fixture_governance_release_gate_v1661"],
        "tests_count": 100,
        "limitations": ["Fixture governance and safety markers only"],
    },
    {
        "capability": "replay_lineage",
        "introduced_in": "1.6.6.2",
        "enhanced_in": ["1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["multi_session_coordination"],
        "health_coverage": [],
        "gate_coverage": [],
        "tests_count": 80,
        "limitations": ["Lineage tracing only"],
    },
    {
        "capability": "performance_attribution",
        "introduced_in": "1.6.7",
        "enhanced_in": ["1.6.8", "1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["paper_trading", "analytics"],
        "health_coverage": ["paper_trading.performance_attribution.health_v167"],
        "gate_coverage": ["release.paper_performance_attribution_release_gate_v167"],
        "tests_count": 600,
        "limitations": ["Paper performance only, no real attribution"],
    },
    {
        "capability": "operational_integration",
        "introduced_in": "1.6.8",
        "enhanced_in": ["1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["paper_trading", "analytics", "performance_attribution"],
        "health_coverage": ["paper_trading.operational_integration.health_v168"],
        "gate_coverage": ["release.operational_integration_hardening_release_gate_v168"],
        "tests_count": 700,
        "limitations": ["Integration simulation only"],
    },
    {
        "capability": "stable_rollup",
        "introduced_in": "1.6.9",
        "enhanced_in": [],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["operational_integration"],
        "health_coverage": ["paper_trading.stable_rollup.health_v169"],
        "gate_coverage": ["release.live_paper_trading_stable_rollup_release_gate_v169"],
        "tests_count": 500,
        "limitations": ["Rollup consolidation only", "Read-only"],
    },
    {
        "capability": "cli",
        "introduced_in": "1.6.0",
        "enhanced_in": ["1.6.1", "1.6.2", "1.6.3", "1.6.4", "1.6.5", "1.6.6", "1.6.7", "1.6.8", "1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": [],
        "health_coverage": [],
        "gate_coverage": [],
        "tests_count": 200,
        "limitations": ["Read-only CLI commands"],
    },
    {
        "capability": "gui",
        "introduced_in": "1.6.0",
        "enhanced_in": ["1.6.1", "1.6.2", "1.6.3", "1.6.4", "1.6.5", "1.6.6", "1.6.7", "1.6.8", "1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": [],
        "health_coverage": [],
        "gate_coverage": [],
        "tests_count": 150,
        "limitations": ["Headless-safe only, no broker UI"],
    },
    {
        "capability": "health",
        "introduced_in": "1.6.0",
        "enhanced_in": ["1.6.1", "1.6.2", "1.6.3", "1.6.4", "1.6.5", "1.6.6", "1.6.7", "1.6.8", "1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": [],
        "health_coverage": [],
        "gate_coverage": [],
        "tests_count": 100,
        "limitations": ["Health check only"],
    },
    {
        "capability": "gate",
        "introduced_in": "1.6.0",
        "enhanced_in": ["1.6.1", "1.6.2", "1.6.3", "1.6.4", "1.6.5", "1.6.6", "1.6.7", "1.6.8", "1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["health"],
        "health_coverage": [],
        "gate_coverage": [],
        "tests_count": 100,
        "limitations": ["Gate check only"],
    },
    {
        "capability": "reporting",
        "introduced_in": "1.6.4",
        "enhanced_in": ["1.6.7", "1.6.8", "1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["analytics"],
        "health_coverage": [],
        "gate_coverage": [],
        "tests_count": 150,
        "limitations": ["Reports are research only"],
    },
    {
        "capability": "deterministic_replay",
        "introduced_in": "1.6.0",
        "enhanced_in": ["1.6.5", "1.6.6.2", "1.6.8", "1.6.9"],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": ["paper_trading", "market_data_session"],
        "health_coverage": [],
        "gate_coverage": [],
        "tests_count": 200,
        "limitations": ["Deterministic simulation only"],
    },
    {
        "capability": "read_only_operation",
        "introduced_in": "1.6.9",
        "enhanced_in": [],
        "current_status": "AVAILABLE",
        "production_ready": False,
        "paper_only": True,
        "research_only": True,
        "read_only": True,
        "dependencies": [],
        "health_coverage": [],
        "gate_coverage": [],
        "tests_count": 80,
        "limitations": ["Enforced read-only across all modules"],
    },
]


def get_matrix() -> List[dict]:
    """Return the full capability matrix."""
    return list(CAPABILITY_MATRIX)


def get_capability(name: str) -> Optional[dict]:
    """Return capability entry by name, or None."""
    for cap in CAPABILITY_MATRIX:
        if cap["capability"] == name:
            return dict(cap)
    return None


def validate_matrix() -> dict:
    """Validate the capability matrix."""
    issues = []
    names_seen = set()

    for cap in CAPABILITY_MATRIX:
        name = cap.get("capability", "")
        if not name:
            issues.append("Entry missing 'capability' field")
            continue
        if name in names_seen:
            issues.append(f"Duplicate capability: {name!r}")
        names_seen.add(name)

        if cap.get("production_ready", True) is not False:
            issues.append(f"Capability {name!r}: production_ready must be False")

        if not cap.get("paper_only", False):
            issues.append(f"Capability {name!r}: paper_only must be True")

    total = len(CAPABILITY_MATRIX)
    return {
        "status": "PASS" if not issues else "FAIL",
        "issues": issues,
        "total": total,
        "unique": len(names_seen),
    }
