"""
paper_trading/stable_rollup/safety_v169.py
Safety constants and validation for Live Paper Trading Stable Rollup v1.6.9.
[!] RESEARCH ONLY. PAPER ONLY. NO REAL ORDERS. NO BROKER.
"""
from __future__ import annotations

# ── Positive safety flags (these must be True) ───────────────────────────────
LIVE_PAPER_STABLE_ROLLUP_AVAILABLE = True
LIVE_PAPER_STABLE_ROLLUP_RESEARCH_ONLY = True
LIVE_PAPER_STABLE_ROLLUP_PAPER_ONLY = True
LIVE_PAPER_STABLE_ROLLUP_READ_ONLY = True
LIVE_PAPER_STABLE_ROLLUP_DETERMINISTIC = True
LIVE_PAPER_STABLE_ROLLUP_SEALED = True
NO_REAL_ORDERS = True
PRODUCTION_TRADING_BLOCKED = True

# ── Negative safety flags (these must be False) ──────────────────────────────
REAL_TRADING_ENABLED = False
REAL_ACCOUNT_ENABLED = False
REAL_ORDER_ENABLED = False
BROKER_EXECUTION_ENABLED = False
PRODUCTION_TRADING_ENABLED = False
PRODUCTION_LEDGER_WRITE_ENABLED = False
LIVE_EXECUTION_ENABLED = False
AUTO_SESSION_CONTROL_ENABLED = False
AUTO_PROCESS_CONTROL_ENABLED = False
AUTO_SERVICE_CONTROL_ENABLED = False
AUTO_CAPITAL_REALLOCATION_ENABLED = False
AUTO_RISK_OVERRIDE_ENABLED = False
EXTERNAL_COORDINATION_ENABLED = False
NETWORK_TRADING_ENABLED = False
SHIOAJI_ENABLED = False
REAL_LEDGER_WRITE_ENABLED = False
PRODUCTION_PROCESS_CONTROL_ENABLED = False
SESSION_CONTROL_ENABLED = False
CREDENTIAL_ACCESS_ENABLED = False
SECRET_ACCESS_ENABLED = False
LIVE_FALLBACK_ENABLED = False
EXTERNAL_DB_ENABLED = False
EXTERNAL_MESSAGE_BROKER_ENABLED = False
EXTERNAL_LOCK_SERVICE_ENABLED = False

SAFETY_CAPABILITY_NAMES = [
    "LIVE_PAPER_STABLE_ROLLUP_AVAILABLE",
    "LIVE_PAPER_STABLE_ROLLUP_RESEARCH_ONLY",
    "LIVE_PAPER_STABLE_ROLLUP_PAPER_ONLY",
    "LIVE_PAPER_STABLE_ROLLUP_READ_ONLY",
    "LIVE_PAPER_STABLE_ROLLUP_DETERMINISTIC",
    "LIVE_PAPER_STABLE_ROLLUP_SEALED",
    "NO_REAL_ORDERS",
    "PRODUCTION_TRADING_BLOCKED",
    "REAL_TRADING_ENABLED",
    "REAL_ACCOUNT_ENABLED",
    "REAL_ORDER_ENABLED",
    "BROKER_EXECUTION_ENABLED",
    "PRODUCTION_TRADING_ENABLED",
    "PRODUCTION_LEDGER_WRITE_ENABLED",
    "LIVE_EXECUTION_ENABLED",
    "AUTO_SESSION_CONTROL_ENABLED",
    "AUTO_PROCESS_CONTROL_ENABLED",
    "AUTO_SERVICE_CONTROL_ENABLED",
    "AUTO_CAPITAL_REALLOCATION_ENABLED",
    "AUTO_RISK_OVERRIDE_ENABLED",
    "EXTERNAL_COORDINATION_ENABLED",
    "NETWORK_TRADING_ENABLED",
    "SHIOAJI_ENABLED",
    "REAL_LEDGER_WRITE_ENABLED",
]

# Flags that must be True for safety
_REQUIRED_TRUE = {
    "LIVE_PAPER_STABLE_ROLLUP_AVAILABLE": LIVE_PAPER_STABLE_ROLLUP_AVAILABLE,
    "LIVE_PAPER_STABLE_ROLLUP_RESEARCH_ONLY": LIVE_PAPER_STABLE_ROLLUP_RESEARCH_ONLY,
    "LIVE_PAPER_STABLE_ROLLUP_PAPER_ONLY": LIVE_PAPER_STABLE_ROLLUP_PAPER_ONLY,
    "LIVE_PAPER_STABLE_ROLLUP_READ_ONLY": LIVE_PAPER_STABLE_ROLLUP_READ_ONLY,
    "LIVE_PAPER_STABLE_ROLLUP_DETERMINISTIC": LIVE_PAPER_STABLE_ROLLUP_DETERMINISTIC,
    "LIVE_PAPER_STABLE_ROLLUP_SEALED": LIVE_PAPER_STABLE_ROLLUP_SEALED,
    "NO_REAL_ORDERS": NO_REAL_ORDERS,
    "PRODUCTION_TRADING_BLOCKED": PRODUCTION_TRADING_BLOCKED,
}

# Flags that must be False for safety
_REQUIRED_FALSE = {
    "REAL_TRADING_ENABLED": REAL_TRADING_ENABLED,
    "REAL_ACCOUNT_ENABLED": REAL_ACCOUNT_ENABLED,
    "REAL_ORDER_ENABLED": REAL_ORDER_ENABLED,
    "BROKER_EXECUTION_ENABLED": BROKER_EXECUTION_ENABLED,
    "PRODUCTION_TRADING_ENABLED": PRODUCTION_TRADING_ENABLED,
    "PRODUCTION_LEDGER_WRITE_ENABLED": PRODUCTION_LEDGER_WRITE_ENABLED,
    "LIVE_EXECUTION_ENABLED": LIVE_EXECUTION_ENABLED,
    "AUTO_SESSION_CONTROL_ENABLED": AUTO_SESSION_CONTROL_ENABLED,
    "AUTO_PROCESS_CONTROL_ENABLED": AUTO_PROCESS_CONTROL_ENABLED,
    "AUTO_SERVICE_CONTROL_ENABLED": AUTO_SERVICE_CONTROL_ENABLED,
    "AUTO_CAPITAL_REALLOCATION_ENABLED": AUTO_CAPITAL_REALLOCATION_ENABLED,
    "AUTO_RISK_OVERRIDE_ENABLED": AUTO_RISK_OVERRIDE_ENABLED,
    "EXTERNAL_COORDINATION_ENABLED": EXTERNAL_COORDINATION_ENABLED,
    "NETWORK_TRADING_ENABLED": NETWORK_TRADING_ENABLED,
    "SHIOAJI_ENABLED": SHIOAJI_ENABLED,
    "REAL_LEDGER_WRITE_ENABLED": REAL_LEDGER_WRITE_ENABLED,
    "PRODUCTION_PROCESS_CONTROL_ENABLED": PRODUCTION_PROCESS_CONTROL_ENABLED,
    "SESSION_CONTROL_ENABLED": SESSION_CONTROL_ENABLED,
    "CREDENTIAL_ACCESS_ENABLED": CREDENTIAL_ACCESS_ENABLED,
    "SECRET_ACCESS_ENABLED": SECRET_ACCESS_ENABLED,
    "LIVE_FALLBACK_ENABLED": LIVE_FALLBACK_ENABLED,
    "EXTERNAL_DB_ENABLED": EXTERNAL_DB_ENABLED,
    "EXTERNAL_MESSAGE_BROKER_ENABLED": EXTERNAL_MESSAGE_BROKER_ENABLED,
    "EXTERNAL_LOCK_SERVICE_ENABLED": EXTERNAL_LOCK_SERVICE_ENABLED,
}


def get_safety_flags() -> dict:
    """Return all safety flags as a dictionary."""
    flags = {}
    flags.update(_REQUIRED_TRUE)
    flags.update(_REQUIRED_FALSE)
    return flags


def validate_safety() -> dict:
    """Check all safety flags are correct. Returns {status, passed, failed, checks}."""
    checks = []
    passed = 0
    failed = 0

    for name, expected_value in _REQUIRED_TRUE.items():
        ok = expected_value is True
        checks.append({"flag": name, "expected": True, "actual": expected_value, "ok": ok})
        if ok:
            passed += 1
        else:
            failed += 1

    for name, expected_value in _REQUIRED_FALSE.items():
        ok = expected_value is False
        checks.append({"flag": name, "expected": False, "actual": expected_value, "ok": ok})
        if ok:
            passed += 1
        else:
            failed += 1

    status = "PASS" if failed == 0 else "FAIL"
    return {
        "status": status,
        "passed": passed,
        "failed": failed,
        "checks": checks,
    }


def is_safe() -> bool:
    """Return True only if all safety flags are correct."""
    result = validate_safety()
    return result["failed"] == 0
