"""
replay/challenge_template.py — 12 built-in challenge templates v1.2.7

[!] Challenge Training Only. Simulation Only. No Real Orders. Not Investment Advice.
[!] No Broker commands. No live orders. No API tokens. No automatic decisions.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

NO_REAL_ORDERS = True
RESEARCH_ONLY = True


# ---------------------------------------------------------------------------
# Template definitions
# ---------------------------------------------------------------------------

CHALLENGE_TEMPLATES: List[Dict[str, Any]] = [
    {
        "template_id": "FREE_DECISION_PRACTICE",
        "title": "Free Decision Practice",
        "description": "Untimed free-form decision practice. No constraints on time or steps.",
        "challenge_type": "FREE_DECISION",
        "difficulty": "BEGINNER",
        "objective": "Make a well-reasoned simulation decision with thesis and risk plan.",
        "required_data": ["D1_context", "session_state"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN", "WRITE_CHECKLIST",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_ADD",
                            "DECIDE_REDUCE", "DECIDE_EXIT", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": None,
        "step_limit": None,
        "action_limit": None,
        "hint_policy": {"max_hints": 5, "penalty_per_hint": 3.0},
        "score_policy": {"process_weight": 0.80, "outcome_weight": 0.20},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1"],
        "optional_timeframes": ["M60", "M20", "M5"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "TIMED_PULLBACK_DECISION",
        "title": "Timed Pullback Decision",
        "description": "Timed challenge: recognize a pullback and decide within time limit.",
        "challenge_type": "TIMED_DECISION",
        "difficulty": "INTERMEDIATE",
        "objective": "Identify pullback setup and make simulation decision within time limit.",
        "required_data": ["D1_context", "M60_context", "session_state"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": 600,
        "step_limit": None,
        "action_limit": 20,
        "hint_policy": {"max_hints": 2, "penalty_per_hint": 5.0},
        "score_policy": {"process_weight": 0.80, "outcome_weight": 0.20},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1", "M60"],
        "optional_timeframes": ["M20", "M5"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "BREAKOUT_CONFIRMATION",
        "title": "Breakout Confirmation",
        "description": "Identify a genuine breakout vs false breakout without chasing.",
        "challenge_type": "BREAKOUT",
        "difficulty": "INTERMEDIATE",
        "objective": "Confirm breakout with volume and multi-timeframe alignment before deciding.",
        "required_data": ["D1_context", "M60_context", "volume_data"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN", "WRITE_CHECKLIST",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": 900,
        "step_limit": None,
        "action_limit": 25,
        "hint_policy": {"max_hints": 2, "penalty_per_hint": 5.0},
        "score_policy": {"process_weight": 0.80, "outcome_weight": 0.20},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1", "M60"],
        "optional_timeframes": ["M20"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "NO_CHASE_DISCIPLINE",
        "title": "No Chase Discipline",
        "description": "Practice not chasing price after a breakout or gap-up.",
        "challenge_type": "NO_CHASE",
        "difficulty": "INTERMEDIATE",
        "objective": "Recognize chase-prone situation; choose WAIT or SKIP; document reason.",
        "required_data": ["D1_context", "session_state"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN",
                            "DECIDE_WAIT", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": ["DECIDE_ENTER"],
        "time_limit": 600,
        "step_limit": None,
        "action_limit": 15,
        "hint_policy": {"max_hints": 3, "penalty_per_hint": 5.0},
        "score_policy": {"process_weight": 0.85, "outcome_weight": 0.15},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1"],
        "optional_timeframes": ["M60"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "NO_PANIC_SELL_DISCIPLINE",
        "title": "No Panic Sell Discipline",
        "description": "Practice holding through volatility without panic-selling.",
        "challenge_type": "NO_PANIC_SELL",
        "difficulty": "INTERMEDIATE",
        "objective": "Recognize panic-prone scenario; choose WAIT or document rational exit only.",
        "required_data": ["D1_context", "M60_context", "session_state"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN", "WRITE_CHECKLIST",
                            "DECIDE_WAIT", "DECIDE_EXIT", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": 600,
        "step_limit": None,
        "action_limit": 20,
        "hint_policy": {"max_hints": 3, "penalty_per_hint": 5.0},
        "score_policy": {"process_weight": 0.85, "outcome_weight": 0.15},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1", "M60"],
        "optional_timeframes": [],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "DO_NOT_REBUY_YET",
        "title": "Do Not Rebuy Yet",
        "description": "Practice waiting before re-entering a position after a stop-out.",
        "challenge_type": "DO_NOT_REBUY_YET",
        "difficulty": "ADVANCED",
        "objective": "Recognize stop-out scenario; resist premature re-entry; wait for new setup.",
        "required_data": ["D1_context", "session_state", "prior_trade_context"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN",
                            "DECIDE_WAIT", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": ["DECIDE_ENTER", "DECIDE_ADD"],
        "time_limit": 600,
        "step_limit": None,
        "action_limit": 15,
        "hint_policy": {"max_hints": 1, "penalty_per_hint": 8.0},
        "score_policy": {"process_weight": 0.85, "outcome_weight": 0.15},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1"],
        "optional_timeframes": ["M60"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "BOTTOM_REVERSAL_CONFIRMATION",
        "title": "Bottom Reversal Confirmation",
        "description": "Identify potential bottom reversal with multi-timeframe confirmation.",
        "challenge_type": "BOTTOM_REVERSAL",
        "difficulty": "ADVANCED",
        "objective": "Build thesis for reversal with confirmation criteria and invalidation levels.",
        "required_data": ["D1_context", "M60_context", "M20_context"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN", "WRITE_CHECKLIST",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": 900,
        "step_limit": None,
        "action_limit": 30,
        "hint_policy": {"max_hints": 1, "penalty_per_hint": 8.0},
        "score_policy": {"process_weight": 0.80, "outcome_weight": 0.20},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1", "M60", "M20"],
        "optional_timeframes": ["M5"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "RISK_CONTROL_UNDER_PRESSURE",
        "title": "Risk Control Under Pressure",
        "description": "Timed challenge: build complete risk plan under time pressure.",
        "challenge_type": "RISK_CONTROL",
        "difficulty": "ADVANCED",
        "objective": "Define stop plan, position size rationale, and invalidation condition.",
        "required_data": ["D1_context", "session_state"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME",
                            "WRITE_THESIS", "WRITE_RISK_PLAN", "WRITE_CHECKLIST",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": 480,
        "step_limit": None,
        "action_limit": 15,
        "hint_policy": {"max_hints": 1, "penalty_per_hint": 8.0},
        "score_policy": {"process_weight": 0.85, "outcome_weight": 0.15},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1"],
        "optional_timeframes": [],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "STRATEGY_CONFLICT_REVIEW",
        "title": "Strategy Conflict Review",
        "description": "Two strategy signals conflict — decide how to handle the conflict.",
        "challenge_type": "STRATEGY_CONFLICT",
        "difficulty": "ADVANCED",
        "objective": "Identify strategy conflict, document reasoning, and make a disciplined decision.",
        "required_data": ["D1_context", "strategy_signals", "conflict_summary"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": 900,
        "step_limit": None,
        "action_limit": 25,
        "hint_policy": {"max_hints": 1, "penalty_per_hint": 8.0},
        "score_policy": {"process_weight": 0.85, "outcome_weight": 0.15},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1"],
        "optional_timeframes": ["M60"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "MULTI_TIMEFRAME_CONFLICT",
        "title": "Multi-Timeframe Conflict",
        "description": "Timeframes disagree — identify conflict and navigate the decision.",
        "challenge_type": "TIMEFRAME_CONFLICT",
        "difficulty": "ADVANCED",
        "objective": "Identify D1/M60/M20 conflict; choose primary context; document reasoning.",
        "required_data": ["D1_context", "M60_context", "M20_context", "conflict_summary"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": 900,
        "step_limit": None,
        "action_limit": 25,
        "hint_policy": {"max_hints": 1, "penalty_per_hint": 8.0},
        "score_policy": {"process_weight": 0.85, "outcome_weight": 0.15},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1", "M60", "M20"],
        "optional_timeframes": ["M5"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "POINT_IN_TIME_INTEGRITY",
        "title": "Point-in-Time Integrity",
        "description": "Use only point-in-time data. Identify if any future data is present.",
        "challenge_type": "POINT_IN_TIME",
        "difficulty": "EXPERT",
        "objective": "Verify all decisions use only past data; identify any data integrity issues.",
        "required_data": ["pit_context", "raw_bars"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME",
                            "WRITE_THESIS", "WRITE_RISK_PLAN",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_SKIP",
                            "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": ["REQUEST_HINT"],
        "time_limit": 600,
        "step_limit": None,
        "action_limit": 15,
        "hint_policy": {"max_hints": 0, "penalty_per_hint": 0.0},
        "score_policy": {"process_weight": 0.90, "outcome_weight": 0.10},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1"],
        "optional_timeframes": [],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
    {
        "template_id": "JOURNAL_DISCIPLINE",
        "title": "Journal Discipline",
        "description": "Complete a full journal entry with thesis, risk plan, and checklist.",
        "challenge_type": "JOURNAL_DISCIPLINE",
        "difficulty": "BEGINNER",
        "objective": "Complete all required journal fields before making a decision.",
        "required_data": ["D1_context", "session_state"],
        "allowed_actions": ["VIEW_CONTEXT", "VIEW_TIMEFRAME", "VIEW_STRATEGY",
                            "WRITE_THESIS", "WRITE_RISK_PLAN", "WRITE_CHECKLIST",
                            "DECIDE_WAIT", "DECIDE_ENTER", "DECIDE_SKIP",
                            "REQUEST_HINT", "PAUSE", "RESUME", "COMPLETE", "CANCEL"],
        "prohibited_actions": [],
        "time_limit": None,
        "step_limit": None,
        "action_limit": 30,
        "hint_policy": {"max_hints": 5, "penalty_per_hint": 3.0},
        "score_policy": {"process_weight": 0.85, "outcome_weight": 0.15},
        "review_policy": {"outcome_reveal": "explicit_only"},
        "required_timeframes": ["D1"],
        "optional_timeframes": ["M60"],
        "qualification": "TRAINING",
        "no_broker": True,
        "no_live_orders": True,
        "no_auto_decision": True,
    },
]

TEMPLATE_IDS = [t["template_id"] for t in CHALLENGE_TEMPLATES]


def get_template(template_id: str) -> Dict[str, Any]:
    """Return template by ID or empty dict if not found."""
    for t in CHALLENGE_TEMPLATES:
        if t["template_id"] == template_id:
            return dict(t)
    return {}


def list_templates() -> List[Dict[str, Any]]:
    """Return all built-in templates (summary view)."""
    return [
        {
            "template_id":    t["template_id"],
            "title":          t["title"],
            "challenge_type": t["challenge_type"],
            "difficulty":     t["difficulty"],
            "time_limit":     t.get("time_limit"),
            "max_hints":      t.get("hint_policy", {}).get("max_hints", 0),
            "no_broker":      t.get("no_broker", True),
            "no_auto_decision": t.get("no_auto_decision", True),
        }
        for t in CHALLENGE_TEMPLATES
    ]
