"""
replay/stable_capability_matrix.py — ReplayStableCapabilityMatrix for v1.2.9.

[!] Research Only. No Real Orders. Not Investment Advice.
[!] Replay Training Stable Rollup. No broker. No trading. Simulation Only.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

NO_REAL_ORDERS = True
RESEARCH_ONLY = True


class ReplayStableCapabilityMatrix:
    """
    Builds the capability matrix for all 16 stable replay capabilities.

    [!] Research Only. No Real Orders. Not Investment Advice.
    """

    RESEARCH_ONLY = True
    NO_REAL_ORDERS = True

    def build(self) -> List[Dict[str, Any]]:
        """Return list of 16 capability dicts.

        Each dict includes: capability_id, module, introduced_version,
        current_status, health_command, CLI_available, GUI_available,
        report_available, backward_compatible, safety_qualified,
        research_only, no_real_orders, notes.
        """
        return [
            {
                "capability_id": "replay_session_step",
                "module": "replay_foundation",
                "introduced_version": "1.2.0",
                "current_status": "STABLE",
                "health_command": "replay-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Core replay session step engine. Future data firewall. Point-in-time only.",
            },
            {
                "capability_id": "scenario_library",
                "module": "scenario_manager",
                "introduced_version": "1.2.1",
                "current_status": "STABLE",
                "health_command": "replay-scenario-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Scenario templates never contain future answers. No future data embedded.",
            },
            {
                "capability_id": "session_fork_checkpoint",
                "module": "session_manager",
                "introduced_version": "1.2.1",
                "current_status": "STABLE",
                "health_command": "replay-session-manager-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Fork/checkpoint never copies future data. Session compare read-only.",
            },
            {
                "capability_id": "decision_journal",
                "module": "decision_journal",
                "introduced_version": "1.2.2",
                "current_status": "STABLE",
                "health_command": "replay-journal-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Simulation decisions only. No paper orders. No broker. Append-only JSONL.",
            },
            {
                "capability_id": "process_outcome_scoring",
                "module": "scoring_mistake_taxonomy",
                "introduced_version": "1.2.3",
                "current_status": "STABLE",
                "health_command": "replay-scoring-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Process scores use NO future data. Outcome reveal EXPLICIT ONLY.",
            },
            {
                "capability_id": "mistake_taxonomy",
                "module": "scoring_mistake_taxonomy",
                "introduced_version": "1.2.3",
                "current_status": "STABLE",
                "health_command": "replay-scoring-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "31-type taxonomy. Mistakes start SUGGESTED. System cannot auto-confirm.",
            },
            {
                "capability_id": "strategy_replay",
                "module": "strategy_knowledge",
                "introduced_version": "1.2.4",
                "current_status": "STABLE",
                "health_command": "replay-strategy-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Point-in-time verified. No forward return. Auto strategy decision DISABLED.",
            },
            {
                "capability_id": "multi_timeframe_sync",
                "module": "multi_timeframe",
                "introduced_version": "1.2.5",
                "current_status": "STABLE",
                "health_command": "replay-timeframe-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "D1/M60/M20/M5/M1 synchronized. No future K-lines. No bfill. No centered rolling.",
            },
            {
                "capability_id": "review_queue",
                "module": "review_dashboard",
                "introduced_version": "1.2.6",
                "current_status": "STABLE",
                "health_command": "replay-review-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "No auto review complete. No auto outcome reveal. No auto decision.",
            },
            {
                "capability_id": "challenge_mode",
                "module": "challenge_mode",
                "introduced_version": "1.2.7",
                "current_status": "STABLE",
                "health_command": "replay-challenge-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Hidden future. Outcome hidden. Deterministic seed. No public leaderboard.",
            },
            {
                "capability_id": "challenge_personal_leaderboard",
                "module": "challenge_mode",
                "introduced_version": "1.2.7",
                "current_status": "STABLE",
                "health_command": "replay-challenge-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": False,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Local personal records only. Network score submission DISABLED.",
            },
            {
                "capability_id": "dataset_registry",
                "module": "dataset_registry",
                "introduced_version": "1.2.8",
                "current_status": "STABLE",
                "health_command": "replay-registry-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Dataset registry only. No auto overwrite. Frozen datasets immutable.",
            },
            {
                "capability_id": "session_registry",
                "module": "session_registry",
                "introduced_version": "1.2.8",
                "current_status": "STABLE",
                "health_command": "replay-registry-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": True,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Session registry only. No auto rebind. Portable packages use relative paths only.",
            },
            {
                "capability_id": "stable_health_check",
                "module": "stable_rollup",
                "introduced_version": "1.2.9",
                "current_status": "STABLE",
                "health_command": "replay-stable-health",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": False,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Aggregates all stable audit results. FAIL count>0 exits 1.",
            },
            {
                "capability_id": "stable_manifest",
                "module": "stable_rollup",
                "introduced_version": "1.2.9",
                "current_status": "STABLE",
                "health_command": "replay-stable-manifest",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": False,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "Stable release manifest. No absolute paths. No secrets.",
            },
            {
                "capability_id": "capability_matrix",
                "module": "stable_rollup",
                "introduced_version": "1.2.9",
                "current_status": "STABLE",
                "health_command": "replay-stable-capabilities",
                "CLI_available": True,
                "GUI_available": True,
                "report_available": True,
                "backward_compatible": False,
                "safety_qualified": True,
                "research_only": True,
                "no_real_orders": True,
                "notes": "16-capability matrix. All safety-qualified. Research only.",
            },
        ]
