"""
portfolio/walk_forward/enums_v154.py — Walk-forward Backtest Enums v1.5.4
[!] Research Only. No Real Orders. Historical Simulation Only.
"""
from __future__ import annotations
from enum import Enum

RESEARCH_ONLY = True
HISTORICAL_SIMULATION_ONLY = True
ENUM_VERSION = "1.5.4"


class WindowType(Enum):
    ROLLING = "ROLLING"
    EXPANDING = "EXPANDING"
    ANCHORED = "ANCHORED"


class WindowStatus(Enum):
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    INSUFFICIENT_TRAINING_DATA = "INSUFFICIENT_TRAINING_DATA"
    INSUFFICIENT_VALIDATION_DATA = "INSUFFICIENT_VALIDATION_DATA"
    PIT_BLOCKED = "PIT_BLOCKED"
    LINEAGE_BLOCKED = "LINEAGE_BLOCKED"
    INVALID = "INVALID"


class ReplayStatus(Enum):
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    NOT_BACKTESTABLE = "NOT_BACKTESTABLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    FAILED = "FAILED"


class RebalanceFrequency(Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    EVENT_DRIVEN = "EVENT_DRIVEN"


class SimulatedTransactionType(Enum):
    """All values are SIMULATION_ONLY, NOT_REAL_ORDER."""
    HYPOTHETICAL_BUY = "HYPOTHETICAL_BUY"        # SIMULATION_ONLY, NOT_REAL_ORDER
    HYPOTHETICAL_SELL = "HYPOTHETICAL_SELL"      # SIMULATION_ONLY, NOT_REAL_ORDER
    HYPOTHETICAL_HOLD = "HYPOTHETICAL_HOLD"      # SIMULATION_ONLY, NOT_REAL_ORDER
    CASH_DEPOSIT = "CASH_DEPOSIT"                # SIMULATION_ONLY, NOT_REAL_ORDER
    CASH_WITHDRAWAL = "CASH_WITHDRAWAL"          # SIMULATION_ONLY, NOT_REAL_ORDER
    DIVIDEND = "DIVIDEND"                        # SIMULATION_ONLY, NOT_REAL_ORDER
    FEE = "FEE"                                  # SIMULATION_ONLY, NOT_REAL_ORDER
    TAX = "TAX"                                  # SIMULATION_ONLY, NOT_REAL_ORDER
    CORPORATE_ACTION = "CORPORATE_ACTION"        # SIMULATION_ONLY, NOT_REAL_ORDER

    SIMULATION_ONLY = True
    NOT_REAL_ORDER = True


class CostModelType(Enum):
    FIXED = "FIXED"
    PERCENTAGE = "PERCENTAGE"
    TIERED = "TIERED"
    POLICY_VERSIONED = "POLICY_VERSIONED"


class SlippageModelType(Enum):
    NONE_DISCLOSED = "NONE_DISCLOSED"
    FIXED_BPS = "FIXED_BPS"
    VOLUME_PARTICIPATION = "VOLUME_PARTICIPATION"
    VOLATILITY_ADJUSTED = "VOLATILITY_ADJUSTED"


class WalkForwardResultStatus(Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    UNSTABLE = "UNSTABLE"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"


class RegimeType(Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"
    SIDEWAYS = "SIDEWAYS"
    LIQUIDITY_STRESS = "LIQUIDITY_STRESS"
    UNKNOWN = "UNKNOWN"


class ExecutionTimingType(Enum):
    SAME_CLOSE = "SAME_CLOSE"
    NEXT_OPEN = "NEXT_OPEN"
    NEXT_CLOSE = "NEXT_CLOSE"
